/* eslint-disable */
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import { derived, writable, type Readable } from 'svelte/store';
import type { Formatters, Locales, TranslationFunctions, Translations } from './i18n-types';
import { i18nObject, loadedFormatters, loadedLocales, locales } from './i18n-util';
import en from './en';
import ja from './ja';

// Load all locales
// Type assertions needed due to typesafe-i18n template literal type constraints
loadedLocales['en'] = en as Translations;
loadedLocales['ja'] = ja as Translations;

const locale = writable<Locales>('en');

export const LL = derived<typeof locale, TranslationFunctions>(locale, $locale => {
	return i18nObject($locale);
});

export const setLocale = (newLocale: Locales) => {
	locale.set(newLocale);
};

export const getLocale = (): Locales => {
	let currentLocale: Locales = 'en';
	locale.subscribe(value => currentLocale = value)();
	return currentLocale;
};
