// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​u​t​h​r​i​m
	 */
	app_title: string
	/**
	 * O​p​e​n​I​D​ ​C​o​n​n​e​c​t​ ​P​r​o​v​i​d​e​r​ ​o​n​ ​C​l​o​u​d​f​l​a​r​e​ ​W​o​r​k​e​r​s
	 */
	app_subtitle: string
	/**
	 * F​r​o​n​t​e​n​d​ ​S​t​a​c​k​ ​T​e​s​t
	 */
	test_title: string
	/**
	 * T​e​s​t​ ​M​e​l​t​ ​U​I​ ​(​H​e​a​d​l​e​s​s​ ​C​o​m​p​o​n​e​n​t​s​)​:
	 */
	test_meltui: string
	/**
	 * P​r​i​m​a​r​y​ ​B​u​t​t​o​n
	 */
	button_primary: string
	/**
	 * S​e​c​o​n​d​a​r​y​ ​B​u​t​t​o​n
	 */
	button_secondary: string
	/**
	 * G​h​o​s​t​ ​B​u​t​t​o​n
	 */
	button_ghost: string
	/**
	 * O​p​e​n​ ​D​i​a​l​o​g
	 */
	button_openDialog: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	form_email: string
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
	 */
	form_emailPlaceholder: string
	/**
	 * S​u​c​c​e​s​s
	 */
	badge_success: string
	/**
	 * W​a​r​n​i​n​g
	 */
	badge_warning: string
	/**
	 * E​r​r​o​r
	 */
	badge_error: string
	/**
	 * I​n​f​o
	 */
	badge_info: string
	/**
	 * M​e​l​t​ ​U​I​ ​D​i​a​l​o​g
	 */
	dialog_title: string
	/**
	 * T​h​i​s​ ​i​s​ ​a​ ​t​e​s​t​ ​d​i​a​l​o​g​ ​u​s​i​n​g​ ​M​e​l​t​ ​U​I​,​ ​a​ ​h​e​a​d​l​e​s​s​,​ ​a​c​c​e​s​s​i​b​l​e​ ​c​o​m​p​o​n​e​n​t​ ​l​i​b​r​a​r​y​ ​f​o​r​ ​S​v​e​l​t​e​.
	 */
	dialog_description: string
	/**
	 * C​a​n​c​e​l
	 */
	dialog_cancel: string
	/**
	 * C​o​n​f​i​r​m
	 */
	dialog_confirm: string
	/**
	 * C​l​o​s​e
	 */
	dialog_close: string
	/**
	 * S​v​e​l​t​e​K​i​t​ ​v​5​ ​+​ ​U​n​o​C​S​S​ ​+​ ​M​e​l​t​ ​U​I​ ​+​ ​C​l​o​u​d​f​l​a​r​e​ ​P​a​g​e​s
	 */
	footer_stack: string
	/**
	 * S​w​i​t​c​h​ ​L​a​n​g​u​a​g​e
	 */
	language_switch: string
	/**
	 * E​n​g​l​i​s​h
	 */
	language_english: string
	/**
	 * J​a​p​a​n​e​s​e
	 */
	language_japanese: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	common_email: string
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
	 */
	common_emailPlaceholder: string
	/**
	 * F​u​l​l​ ​n​a​m​e
	 */
	common_name: string
	/**
	 * J​o​h​n​ ​D​o​e
	 */
	common_namePlaceholder: string
	/**
	 * C​o​n​t​i​n​u​e
	 */
	common_continue: string
	/**
	 * C​a​n​c​e​l
	 */
	common_cancel: string
	/**
	 * B​a​c​k​ ​t​o​ ​l​o​g​i​n
	 */
	common_backToLogin: string
	/**
	 * o​r
	 */
	common_or: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	common_loading: string
	/**
	 * W​e​l​c​o​m​e​ ​b​a​c​k
	 */
	login_title: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	login_subtitle: string
	/**
	 * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	login_continueWithPasskey: string
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	login_signInWithPasskey: string
	/**
	 * S​e​n​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	login_sendCode: string
	/**
	 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​C​r​e​a​t​e​ ​o​n​e
	 */
	login_createAccount: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	login_errorEmailRequired: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	login_errorEmailInvalid: string
	/**
	 * S​i​g​n​ ​U​p
	 */
	header_signUp: string
	/**
	 * L​o​g​i​n
	 */
	header_login: string
	/**
	 * L​o​g​o​u​t
	 */
	header_logout: string
	/**
	 * C​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	register_title: string
	/**
	 * G​e​t​ ​s​t​a​r​t​e​d​ ​w​i​t​h​ ​A​u​t​h​r​i​m
	 */
	register_subtitle: string
	/**
	 * C​r​e​a​t​e​ ​A​c​c​o​u​n​t​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	register_createWithPasskey: string
	/**
	 * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	register_sendCode: string
	/**
	 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​S​i​g​n​ ​i​n
	 */
	register_alreadyHaveAccount: string
	/**
	 * B​y​ ​c​r​e​a​t​i​n​g​ ​a​n​ ​a​c​c​o​u​n​t​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​o​u​r​ ​T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e​ ​a​n​d​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y
	 */
	register_termsAgreement: string
	/**
	 * N​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	register_errorNameRequired: string
	/**
	 * C​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l
	 */
	emailCode_title: string
	/**
	 * W​e​'​v​e​ ​s​e​n​t​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​t​o
	 */
	emailCode_subtitle: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​6​-​d​i​g​i​t​ ​c​o​d​e​ ​f​r​o​m​ ​y​o​u​r​ ​e​m​a​i​l​.​ ​T​h​e​ ​c​o​d​e​ ​w​i​l​l​ ​e​x​p​i​r​e​ ​i​n​ ​5​ ​m​i​n​u​t​e​s​.
	 */
	emailCode_instructions: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
	 */
	emailCode_codeLabel: string
	/**
	 * V​e​r​i​f​y
	 */
	emailCode_verifyButton: string
	/**
	 * R​e​s​e​n​d​ ​c​o​d​e
	 */
	emailCode_resendButton: string
	/**
	 * R​e​s​e​n​d​ ​i​n​ ​{​s​e​c​o​n​d​s​}​s
	 * @param {unknown} seconds
	 */
	emailCode_resendTimer: RequiredParams<'seconds'>
	/**
	 * C​o​d​e​ ​s​e​n​t​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	emailCode_resendSuccess: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​s​u​c​c​e​s​s​f​u​l​!​ ​R​e​d​i​r​e​c​t​i​n​g​.​.​.
	 */
	emailCode_success: string
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​c​o​d​e
	 */
	emailCode_errorInvalid: string
	/**
	 * S​e​s​s​i​o​n​ ​m​i​s​m​a​t​c​h​.​ ​P​l​e​a​s​e​ ​r​e​q​u​e​s​t​ ​a​ ​n​e​w​ ​c​o​d​e​.
	 */
	emailCode_errorSessionMismatch: string
	/**
	 * {​c​l​i​e​n​t​N​a​m​e​}​ ​w​a​n​t​s​ ​t​o​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 * @param {string} clientName
	 */
	consent_title: RequiredParams<'clientName'>
	/**
	 * T​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​r​e​q​u​e​s​t​i​n​g​ ​a​c​c​e​s​s​ ​t​o​ ​y​o​u​r​ ​A​u​t​h​r​i​m​ ​a​c​c​o​u​n​t
	 */
	consent_subtitle: string
	/**
	 * T​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​:
	 */
	consent_scopesTitle: string
	/**
	 * Y​o​u​ ​a​r​e​ ​s​i​g​n​e​d​ ​i​n​ ​a​s
	 */
	consent_userInfo: string
	/**
	 * N​o​t​ ​y​o​u​?​ ​S​w​i​t​c​h​ ​a​c​c​o​u​n​t
	 */
	consent_notYou: string
	/**
	 * A​l​l​o​w
	 */
	consent_allowButton: string
	/**
	 * D​e​n​y
	 */
	consent_denyButton: string
	/**
	 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
	 */
	consent_privacyPolicy: string
	/**
	 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
	 */
	consent_termsOfService: string
	/**
	 * V​e​r​i​f​y​ ​y​o​u​r​ ​i​d​e​n​t​i​t​y
	 */
	consent_scope_openid: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​(​n​a​m​e​,​ ​p​i​c​t​u​r​e​)
	 */
	consent_scope_profile: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	consent_scope_email: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r
	 */
	consent_scope_phone: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​a​d​d​r​e​s​s
	 */
	consent_scope_address: string
	/**
	 * M​a​i​n​t​a​i​n​ ​a​c​c​e​s​s​ ​w​h​e​n​ ​y​o​u​'​r​e​ ​n​o​t​ ​u​s​i​n​g​ ​t​h​e​ ​a​p​p
	 */
	consent_scope_offline_access: string
	/**
	 * O​o​p​s​!​ ​S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	error_title: string
	/**
	 * W​e​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​n​ ​e​r​r​o​r​ ​w​h​i​l​e​ ​p​r​o​c​e​s​s​i​n​g​ ​y​o​u​r​ ​r​e​q​u​e​s​t
	 */
	error_subtitle: string
	/**
	 * I​f​ ​t​h​i​s​ ​p​r​o​b​l​e​m​ ​p​e​r​s​i​s​t​s​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​s​u​p​p​o​r​t
	 */
	error_contactSupport: string
	/**
	 * E​r​r​o​r​ ​c​o​d​e
	 */
	error_errorCode: string
	/**
	 * T​h​e​ ​r​e​q​u​e​s​t​ ​i​s​ ​m​i​s​s​i​n​g​ ​a​ ​r​e​q​u​i​r​e​d​ ​p​a​r​a​m​e​t​e​r​ ​o​r​ ​i​s​ ​o​t​h​e​r​w​i​s​e​ ​m​a​l​f​o​r​m​e​d
	 */
	error_invalid_request: string
	/**
	 * Y​o​u​ ​d​e​n​i​e​d​ ​t​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​r​e​q​u​e​s​t
	 */
	error_access_denied: string
	/**
	 * T​h​e​ ​c​l​i​e​n​t​ ​i​s​ ​n​o​t​ ​a​u​t​h​o​r​i​z​e​d​ ​t​o​ ​r​e​q​u​e​s​t​ ​a​n​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​c​o​d​e
	 */
	error_unauthorized_client: string
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​d​o​e​s​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​t​h​i​s​ ​r​e​s​p​o​n​s​e​ ​t​y​p​e
	 */
	error_unsupported_response_type: string
	/**
	 * T​h​e​ ​r​e​q​u​e​s​t​e​d​ ​s​c​o​p​e​ ​i​s​ ​i​n​v​a​l​i​d​,​ ​u​n​k​n​o​w​n​,​ ​o​r​ ​m​a​l​f​o​r​m​e​d
	 */
	error_invalid_scope: string
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r
	 */
	error_server_error: string
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​i​s​ ​t​e​m​p​o​r​a​r​i​l​y​ ​u​n​a​b​l​e​ ​t​o​ ​h​a​n​d​l​e​ ​t​h​e​ ​r​e​q​u​e​s​t
	 */
	error_temporarily_unavailable: string
	/**
	 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
	 */
	error_unknown: string
	/**
	 * D​e​v​i​c​e​ ​V​e​r​i​f​i​c​a​t​i​o​n
	 */
	device_title: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​c​o​d​e​ ​s​h​o​w​n​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e
	 */
	device_subtitle: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​8​-​c​h​a​r​a​c​t​e​r​ ​c​o​d​e​ ​d​i​s​p​l​a​y​e​d​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​t​o​ ​a​u​t​h​o​r​i​z​e​ ​i​t
	 */
	device_instructions: string
	/**
	 * S​c​a​n​ ​t​h​i​s​ ​Q​R​ ​c​o​d​e
	 */
	device_qrCodeLabel: string
	/**
	 * o​r​ ​e​n​t​e​r​ ​c​o​d​e​ ​m​a​n​u​a​l​l​y
	 */
	device_orManual: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
	 */
	device_codeLabel: string
	/**
	 * X​X​X​X​-​X​X​X​X
	 */
	device_codePlaceholder: string
	/**
	 * A​p​p​r​o​v​e
	 */
	device_approveButton: string
	/**
	 * D​e​n​y
	 */
	device_denyButton: string
	/**
	 * D​e​v​i​c​e​ ​a​u​t​h​o​r​i​z​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​c​l​o​s​e​ ​t​h​i​s​ ​w​i​n​d​o​w​.
	 */
	device_success: string
	/**
	 * D​e​v​i​c​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​d​e​n​i​e​d
	 */
	device_denied: string
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	device_errorInvalidCode: string
	/**
	 * T​h​i​s​ ​c​o​d​e​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​b​e​e​n​ ​u​s​e​d
	 */
	device_errorAlreadyUsed: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	device_errorGeneric: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​t​h​e​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	device_errorCodeRequired: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	admin_sidebar_dashboard: string
	/**
	 * U​s​e​r​s
	 */
	admin_sidebar_users: string
	/**
	 * C​l​i​e​n​t​s
	 */
	admin_sidebar_clients: string
	/**
	 * S​e​s​s​i​o​n​s
	 */
	admin_sidebar_sessions: string
	/**
	 * A​u​d​i​t​ ​L​o​g
	 */
	admin_sidebar_audit_log: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	admin_sidebar_settings: string
	/**
	 * S​C​I​M​ ​T​o​k​e​n​s
	 */
	admin_sidebar_scim_tokens: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	admin_dashboard_title: string
	/**
	 * A​c​t​i​v​e​ ​U​s​e​r​s
	 */
	admin_dashboard_activeUsers: string
	/**
	 * T​o​t​a​l​ ​U​s​e​r​s
	 */
	admin_dashboard_totalUsers: string
	/**
	 * O​A​u​t​h​ ​C​l​i​e​n​t​s
	 */
	admin_dashboard_clients: string
	/**
	 * T​o​d​a​y​'​s​ ​L​o​g​i​n​s
	 */
	admin_dashboard_todayLogins: string
	/**
	 * R​e​c​e​n​t​ ​A​c​t​i​v​i​t​y
	 */
	admin_dashboard_recentActivity: string
	/**
	 * U​s​e​r​ ​M​a​n​a​g​e​m​e​n​t
	 */
	admin_users_title: string
	/**
	 * S​e​a​r​c​h​ ​b​y​ ​e​m​a​i​l​ ​o​r​ ​n​a​m​e
	 */
	admin_users_search: string
	/**
	 * A​d​d​ ​U​s​e​r
	 */
	admin_users_addUser: string
	/**
	 * F​i​l​t​e​r
	 */
	admin_users_filter: string
	/**
	 * A​l​l
	 */
	admin_users_all: string
	/**
	 * V​e​r​i​f​i​e​d
	 */
	admin_users_verified: string
	/**
	 * U​n​v​e​r​i​f​i​e​d
	 */
	admin_users_unverified: string
	/**
	 * E​m​a​i​l
	 */
	admin_users_email: string
	/**
	 * N​a​m​e
	 */
	admin_users_name: string
	/**
	 * S​t​a​t​u​s
	 */
	admin_users_status: string
	/**
	 * C​r​e​a​t​e​d
	 */
	admin_users_created: string
	/**
	 * L​a​s​t​ ​L​o​g​i​n
	 */
	admin_users_lastLogin: string
	/**
	 * A​c​t​i​o​n​s
	 */
	admin_users_actions: string
	/**
	 * E​d​i​t
	 */
	admin_users_edit: string
	/**
	 * D​e​l​e​t​e
	 */
	admin_users_delete: string
	/**
	 * V​i​e​w
	 */
	admin_users_view: string
	/**
	 * U​s​e​r​ ​D​e​t​a​i​l​s
	 */
	admin_user_detail_title: string
	/**
	 * B​a​s​i​c​ ​I​n​f​o​r​m​a​t​i​o​n
	 */
	admin_user_detail_basicInfo: string
	/**
	 * C​u​s​t​o​m​ ​F​i​e​l​d​s
	 */
	admin_user_detail_customFields: string
	/**
	 * R​e​g​i​s​t​e​r​e​d​ ​P​a​s​s​k​e​y​s
	 */
	admin_user_detail_passkeys: string
	/**
	 * A​c​t​i​v​e​ ​S​e​s​s​i​o​n​s
	 */
	admin_user_detail_sessions: string
	/**
	 * S​a​v​e​ ​C​h​a​n​g​e​s
	 */
	admin_user_detail_save: string
	/**
	 * D​e​l​e​t​e​ ​U​s​e​r
	 */
	admin_user_detail_deleteUser: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​u​s​e​r​?
	 */
	admin_user_detail_deleteConfirm: string
	/**
	 * C​l​i​e​n​t​ ​M​a​n​a​g​e​m​e​n​t
	 */
	admin_clients_title: string
	/**
	 * S​e​a​r​c​h​ ​b​y​ ​c​l​i​e​n​t​ ​n​a​m​e​ ​o​r​ ​I​D
	 */
	admin_clients_search: string
	/**
	 * R​e​g​i​s​t​e​r​ ​C​l​i​e​n​t
	 */
	admin_clients_registerClient: string
	/**
	 * C​l​i​e​n​t​ ​I​D
	 */
	admin_clients_clientId: string
	/**
	 * C​l​i​e​n​t​ ​N​a​m​e
	 */
	admin_clients_clientName: string
	/**
	 * G​r​a​n​t​ ​T​y​p​e​s
	 */
	admin_clients_grantTypes: string
	/**
	 * C​r​e​a​t​e​d
	 */
	admin_clients_created: string
	/**
	 * A​c​t​i​o​n​s
	 */
	admin_clients_actions: string
	/**
	 * C​l​i​e​n​t​ ​D​e​t​a​i​l​s
	 */
	admin_client_detail_title: string
	/**
	 * B​a​s​i​c​ ​I​n​f​o​r​m​a​t​i​o​n
	 */
	admin_client_detail_basicInfo: string
	/**
	 * R​e​d​i​r​e​c​t​ ​U​R​I​s
	 */
	admin_client_detail_redirectUris: string
	/**
	 * G​r​a​n​t​ ​T​y​p​e​s
	 */
	admin_client_detail_grantTypes: string
	/**
	 * S​c​o​p​e​s
	 */
	admin_client_detail_scopes: string
	/**
	 * S​a​v​e​ ​C​h​a​n​g​e​s
	 */
	admin_client_detail_save: string
	/**
	 * R​e​g​e​n​e​r​a​t​e​ ​S​e​c​r​e​t
	 */
	admin_client_detail_regenerateSecret: string
	/**
	 * D​e​l​e​t​e​ ​C​l​i​e​n​t
	 */
	admin_client_detail_deleteClient: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	admin_settings_title: string
	/**
	 * G​e​n​e​r​a​l
	 */
	admin_settings_general: string
	/**
	 * A​p​p​e​a​r​a​n​c​e
	 */
	admin_settings_appearance: string
	/**
	 * S​e​c​u​r​i​t​y
	 */
	admin_settings_security: string
	/**
	 * E​m​a​i​l
	 */
	admin_settings_email: string
	/**
	 * A​d​v​a​n​c​e​d
	 */
	admin_settings_advanced: string
	/**
	 * A​u​d​i​t​ ​L​o​g
	 */
	admin_audit_title: string
	/**
	 * T​i​m​e​s​t​a​m​p
	 */
	admin_audit_timestamp: string
	/**
	 * U​s​e​r
	 */
	admin_audit_user: string
	/**
	 * A​c​t​i​o​n
	 */
	admin_audit_action: string
	/**
	 * R​e​s​o​u​r​c​e
	 */
	admin_audit_resource: string
	/**
	 * I​P​ ​A​d​d​r​e​s​s
	 */
	admin_audit_ip: string
	/**
	 * S​t​a​t​u​s
	 */
	admin_audit_status: string
	/**
	 * E​x​p​o​r​t
	 */
	admin_audit_export: string
}

export type TranslationFunctions = {
	/**
	 * Authrim
	 */
	app_title: () => LocalizedString
	/**
	 * OpenID Connect Provider on Cloudflare Workers
	 */
	app_subtitle: () => LocalizedString
	/**
	 * Frontend Stack Test
	 */
	test_title: () => LocalizedString
	/**
	 * Test Melt UI (Headless Components):
	 */
	test_meltui: () => LocalizedString
	/**
	 * Primary Button
	 */
	button_primary: () => LocalizedString
	/**
	 * Secondary Button
	 */
	button_secondary: () => LocalizedString
	/**
	 * Ghost Button
	 */
	button_ghost: () => LocalizedString
	/**
	 * Open Dialog
	 */
	button_openDialog: () => LocalizedString
	/**
	 * Email address
	 */
	form_email: () => LocalizedString
	/**
	 * you@example.com
	 */
	form_emailPlaceholder: () => LocalizedString
	/**
	 * Success
	 */
	badge_success: () => LocalizedString
	/**
	 * Warning
	 */
	badge_warning: () => LocalizedString
	/**
	 * Error
	 */
	badge_error: () => LocalizedString
	/**
	 * Info
	 */
	badge_info: () => LocalizedString
	/**
	 * Melt UI Dialog
	 */
	dialog_title: () => LocalizedString
	/**
	 * This is a test dialog using Melt UI, a headless, accessible component library for Svelte.
	 */
	dialog_description: () => LocalizedString
	/**
	 * Cancel
	 */
	dialog_cancel: () => LocalizedString
	/**
	 * Confirm
	 */
	dialog_confirm: () => LocalizedString
	/**
	 * Close
	 */
	dialog_close: () => LocalizedString
	/**
	 * SvelteKit v5 + UnoCSS + Melt UI + Cloudflare Pages
	 */
	footer_stack: () => LocalizedString
	/**
	 * Switch Language
	 */
	language_switch: () => LocalizedString
	/**
	 * English
	 */
	language_english: () => LocalizedString
	/**
	 * Japanese
	 */
	language_japanese: () => LocalizedString
	/**
	 * Email address
	 */
	common_email: () => LocalizedString
	/**
	 * you@example.com
	 */
	common_emailPlaceholder: () => LocalizedString
	/**
	 * Full name
	 */
	common_name: () => LocalizedString
	/**
	 * John Doe
	 */
	common_namePlaceholder: () => LocalizedString
	/**
	 * Continue
	 */
	common_continue: () => LocalizedString
	/**
	 * Cancel
	 */
	common_cancel: () => LocalizedString
	/**
	 * Back to login
	 */
	common_backToLogin: () => LocalizedString
	/**
	 * or
	 */
	common_or: () => LocalizedString
	/**
	 * Loading...
	 */
	common_loading: () => LocalizedString
	/**
	 * Welcome back
	 */
	login_title: () => LocalizedString
	/**
	 * Sign in to your account
	 */
	login_subtitle: () => LocalizedString
	/**
	 * Continue with Passkey
	 */
	login_continueWithPasskey: () => LocalizedString
	/**
	 * Sign in with Passkey
	 */
	login_signInWithPasskey: () => LocalizedString
	/**
	 * Send verification code
	 */
	login_sendCode: () => LocalizedString
	/**
	 * Don't have an account? Create one
	 */
	login_createAccount: () => LocalizedString
	/**
	 * Email address is required
	 */
	login_errorEmailRequired: () => LocalizedString
	/**
	 * Please enter a valid email address
	 */
	login_errorEmailInvalid: () => LocalizedString
	/**
	 * Sign Up
	 */
	header_signUp: () => LocalizedString
	/**
	 * Login
	 */
	header_login: () => LocalizedString
	/**
	 * Logout
	 */
	header_logout: () => LocalizedString
	/**
	 * Create your account
	 */
	register_title: () => LocalizedString
	/**
	 * Get started with Authrim
	 */
	register_subtitle: () => LocalizedString
	/**
	 * Create Account with Passkey
	 */
	register_createWithPasskey: () => LocalizedString
	/**
	 * Sign up with verification code
	 */
	register_sendCode: () => LocalizedString
	/**
	 * Already have an account? Sign in
	 */
	register_alreadyHaveAccount: () => LocalizedString
	/**
	 * By creating an account, you agree to our Terms of Service and Privacy Policy
	 */
	register_termsAgreement: () => LocalizedString
	/**
	 * Name is required
	 */
	register_errorNameRequired: () => LocalizedString
	/**
	 * Check your email
	 */
	emailCode_title: () => LocalizedString
	/**
	 * We've sent a verification code to
	 */
	emailCode_subtitle: () => LocalizedString
	/**
	 * Enter the 6-digit code from your email. The code will expire in 5 minutes.
	 */
	emailCode_instructions: () => LocalizedString
	/**
	 * Verification Code
	 */
	emailCode_codeLabel: () => LocalizedString
	/**
	 * Verify
	 */
	emailCode_verifyButton: () => LocalizedString
	/**
	 * Resend code
	 */
	emailCode_resendButton: () => LocalizedString
	/**
	 * Resend in {seconds}s
	 */
	emailCode_resendTimer: (arg: { seconds: unknown }) => LocalizedString
	/**
	 * Code sent successfully
	 */
	emailCode_resendSuccess: () => LocalizedString
	/**
	 * Verification successful! Redirecting...
	 */
	emailCode_success: () => LocalizedString
	/**
	 * Invalid or expired code
	 */
	emailCode_errorInvalid: () => LocalizedString
	/**
	 * Session mismatch. Please request a new code.
	 */
	emailCode_errorSessionMismatch: () => LocalizedString
	/**
	 * {clientName} wants to access your account
	 */
	consent_title: (arg: { clientName: string }) => LocalizedString
	/**
	 * This application is requesting access to your Authrim account
	 */
	consent_subtitle: () => LocalizedString
	/**
	 * This application will be able to:
	 */
	consent_scopesTitle: () => LocalizedString
	/**
	 * You are signed in as
	 */
	consent_userInfo: () => LocalizedString
	/**
	 * Not you? Switch account
	 */
	consent_notYou: () => LocalizedString
	/**
	 * Allow
	 */
	consent_allowButton: () => LocalizedString
	/**
	 * Deny
	 */
	consent_denyButton: () => LocalizedString
	/**
	 * Privacy Policy
	 */
	consent_privacyPolicy: () => LocalizedString
	/**
	 * Terms of Service
	 */
	consent_termsOfService: () => LocalizedString
	/**
	 * Verify your identity
	 */
	consent_scope_openid: () => LocalizedString
	/**
	 * View your profile information (name, picture)
	 */
	consent_scope_profile: () => LocalizedString
	/**
	 * View your email address
	 */
	consent_scope_email: () => LocalizedString
	/**
	 * View your phone number
	 */
	consent_scope_phone: () => LocalizedString
	/**
	 * View your address
	 */
	consent_scope_address: () => LocalizedString
	/**
	 * Maintain access when you're not using the app
	 */
	consent_scope_offline_access: () => LocalizedString
	/**
	 * Oops! Something went wrong
	 */
	error_title: () => LocalizedString
	/**
	 * We encountered an error while processing your request
	 */
	error_subtitle: () => LocalizedString
	/**
	 * If this problem persists, please contact support
	 */
	error_contactSupport: () => LocalizedString
	/**
	 * Error code
	 */
	error_errorCode: () => LocalizedString
	/**
	 * The request is missing a required parameter or is otherwise malformed
	 */
	error_invalid_request: () => LocalizedString
	/**
	 * You denied the authorization request
	 */
	error_access_denied: () => LocalizedString
	/**
	 * The client is not authorized to request an authorization code
	 */
	error_unauthorized_client: () => LocalizedString
	/**
	 * The authorization server does not support this response type
	 */
	error_unsupported_response_type: () => LocalizedString
	/**
	 * The requested scope is invalid, unknown, or malformed
	 */
	error_invalid_scope: () => LocalizedString
	/**
	 * The authorization server encountered an unexpected error
	 */
	error_server_error: () => LocalizedString
	/**
	 * The authorization server is temporarily unable to handle the request
	 */
	error_temporarily_unavailable: () => LocalizedString
	/**
	 * An unknown error occurred
	 */
	error_unknown: () => LocalizedString
	/**
	 * Device Verification
	 */
	device_title: () => LocalizedString
	/**
	 * Enter the code shown on your device
	 */
	device_subtitle: () => LocalizedString
	/**
	 * Enter the 8-character code displayed on your device to authorize it
	 */
	device_instructions: () => LocalizedString
	/**
	 * Scan this QR code
	 */
	device_qrCodeLabel: () => LocalizedString
	/**
	 * or enter code manually
	 */
	device_orManual: () => LocalizedString
	/**
	 * Verification Code
	 */
	device_codeLabel: () => LocalizedString
	/**
	 * XXXX-XXXX
	 */
	device_codePlaceholder: () => LocalizedString
	/**
	 * Approve
	 */
	device_approveButton: () => LocalizedString
	/**
	 * Deny
	 */
	device_denyButton: () => LocalizedString
	/**
	 * Device authorized successfully! You can now close this window.
	 */
	device_success: () => LocalizedString
	/**
	 * Device authorization denied
	 */
	device_denied: () => LocalizedString
	/**
	 * Invalid or expired verification code
	 */
	device_errorInvalidCode: () => LocalizedString
	/**
	 * This code has already been used
	 */
	device_errorAlreadyUsed: () => LocalizedString
	/**
	 * Verification failed. Please try again.
	 */
	device_errorGeneric: () => LocalizedString
	/**
	 * Please enter the verification code
	 */
	device_errorCodeRequired: () => LocalizedString
	/**
	 * Dashboard
	 */
	admin_sidebar_dashboard: () => LocalizedString
	/**
	 * Users
	 */
	admin_sidebar_users: () => LocalizedString
	/**
	 * Clients
	 */
	admin_sidebar_clients: () => LocalizedString
	/**
	 * Sessions
	 */
	admin_sidebar_sessions: () => LocalizedString
	/**
	 * Audit Log
	 */
	admin_sidebar_audit_log: () => LocalizedString
	/**
	 * Settings
	 */
	admin_sidebar_settings: () => LocalizedString
	/**
	 * SCIM Tokens
	 */
	admin_sidebar_scim_tokens: () => LocalizedString
	/**
	 * Dashboard
	 */
	admin_dashboard_title: () => LocalizedString
	/**
	 * Active Users
	 */
	admin_dashboard_activeUsers: () => LocalizedString
	/**
	 * Total Users
	 */
	admin_dashboard_totalUsers: () => LocalizedString
	/**
	 * OAuth Clients
	 */
	admin_dashboard_clients: () => LocalizedString
	/**
	 * Today's Logins
	 */
	admin_dashboard_todayLogins: () => LocalizedString
	/**
	 * Recent Activity
	 */
	admin_dashboard_recentActivity: () => LocalizedString
	/**
	 * User Management
	 */
	admin_users_title: () => LocalizedString
	/**
	 * Search by email or name
	 */
	admin_users_search: () => LocalizedString
	/**
	 * Add User
	 */
	admin_users_addUser: () => LocalizedString
	/**
	 * Filter
	 */
	admin_users_filter: () => LocalizedString
	/**
	 * All
	 */
	admin_users_all: () => LocalizedString
	/**
	 * Verified
	 */
	admin_users_verified: () => LocalizedString
	/**
	 * Unverified
	 */
	admin_users_unverified: () => LocalizedString
	/**
	 * Email
	 */
	admin_users_email: () => LocalizedString
	/**
	 * Name
	 */
	admin_users_name: () => LocalizedString
	/**
	 * Status
	 */
	admin_users_status: () => LocalizedString
	/**
	 * Created
	 */
	admin_users_created: () => LocalizedString
	/**
	 * Last Login
	 */
	admin_users_lastLogin: () => LocalizedString
	/**
	 * Actions
	 */
	admin_users_actions: () => LocalizedString
	/**
	 * Edit
	 */
	admin_users_edit: () => LocalizedString
	/**
	 * Delete
	 */
	admin_users_delete: () => LocalizedString
	/**
	 * View
	 */
	admin_users_view: () => LocalizedString
	/**
	 * User Details
	 */
	admin_user_detail_title: () => LocalizedString
	/**
	 * Basic Information
	 */
	admin_user_detail_basicInfo: () => LocalizedString
	/**
	 * Custom Fields
	 */
	admin_user_detail_customFields: () => LocalizedString
	/**
	 * Registered Passkeys
	 */
	admin_user_detail_passkeys: () => LocalizedString
	/**
	 * Active Sessions
	 */
	admin_user_detail_sessions: () => LocalizedString
	/**
	 * Save Changes
	 */
	admin_user_detail_save: () => LocalizedString
	/**
	 * Delete User
	 */
	admin_user_detail_deleteUser: () => LocalizedString
	/**
	 * Are you sure you want to delete this user?
	 */
	admin_user_detail_deleteConfirm: () => LocalizedString
	/**
	 * Client Management
	 */
	admin_clients_title: () => LocalizedString
	/**
	 * Search by client name or ID
	 */
	admin_clients_search: () => LocalizedString
	/**
	 * Register Client
	 */
	admin_clients_registerClient: () => LocalizedString
	/**
	 * Client ID
	 */
	admin_clients_clientId: () => LocalizedString
	/**
	 * Client Name
	 */
	admin_clients_clientName: () => LocalizedString
	/**
	 * Grant Types
	 */
	admin_clients_grantTypes: () => LocalizedString
	/**
	 * Created
	 */
	admin_clients_created: () => LocalizedString
	/**
	 * Actions
	 */
	admin_clients_actions: () => LocalizedString
	/**
	 * Client Details
	 */
	admin_client_detail_title: () => LocalizedString
	/**
	 * Basic Information
	 */
	admin_client_detail_basicInfo: () => LocalizedString
	/**
	 * Redirect URIs
	 */
	admin_client_detail_redirectUris: () => LocalizedString
	/**
	 * Grant Types
	 */
	admin_client_detail_grantTypes: () => LocalizedString
	/**
	 * Scopes
	 */
	admin_client_detail_scopes: () => LocalizedString
	/**
	 * Save Changes
	 */
	admin_client_detail_save: () => LocalizedString
	/**
	 * Regenerate Secret
	 */
	admin_client_detail_regenerateSecret: () => LocalizedString
	/**
	 * Delete Client
	 */
	admin_client_detail_deleteClient: () => LocalizedString
	/**
	 * Settings
	 */
	admin_settings_title: () => LocalizedString
	/**
	 * General
	 */
	admin_settings_general: () => LocalizedString
	/**
	 * Appearance
	 */
	admin_settings_appearance: () => LocalizedString
	/**
	 * Security
	 */
	admin_settings_security: () => LocalizedString
	/**
	 * Email
	 */
	admin_settings_email: () => LocalizedString
	/**
	 * Advanced
	 */
	admin_settings_advanced: () => LocalizedString
	/**
	 * Audit Log
	 */
	admin_audit_title: () => LocalizedString
	/**
	 * Timestamp
	 */
	admin_audit_timestamp: () => LocalizedString
	/**
	 * User
	 */
	admin_audit_user: () => LocalizedString
	/**
	 * Action
	 */
	admin_audit_action: () => LocalizedString
	/**
	 * Resource
	 */
	admin_audit_resource: () => LocalizedString
	/**
	 * IP Address
	 */
	admin_audit_ip: () => LocalizedString
	/**
	 * Status
	 */
	admin_audit_status: () => LocalizedString
	/**
	 * Export
	 */
	admin_audit_export: () => LocalizedString
}

export type Formatters = {}
