import type { TenantDatasetKind } from './dataset-registry.js';
import type { TenantPortableDependency } from './reference-contract.js';
import type { TenantBackupSelection, TenantPortableSourceIdentity } from './selection-contract.js';

/** Server-side limit for closing writer admission at snapshot start, not export duration. */
export const TENANT_BACKUP_BEGIN_BUDGET_MS = 2_000;

/** Internal modules, not additional operator-facing selection switches. */
export const TENANT_PORTABILITY_MODULES = [
  'tenant-runtime',
  'applications',
  'authorization',
  'consent',
  'mapping',
  'flows-ui',
  'federation',
  'credentials',
  'integrations',
  'placement-rebuild',
  'users',
  'admin',
  'logs',
  'artifacts',
] as const;

export type TenantPortabilityModuleId = (typeof TENANT_PORTABILITY_MODULES)[number];
export type TenantPortableStore = 'database' | 'kv' | 'durable_object' | 'object' | 'environment';

/** Stable logical dataset name. Never a deployment-specific database/bucket/DO identifier. */
export interface TenantPortableDataset {
  id: string;
  module: TenantPortabilityModuleId;
  kind: TenantDatasetKind;
  store: TenantPortableStore;
  schemaVersion: number;
  disposition: 'include' | 'rebuild' | 'external' | 'unsupported';
}

export interface TenantPortabilityContext {
  operationId: string;
  source: TenantPortableSourceIdentity;
  selection: TenantBackupSelection;
  snapshotId: string;
  inventoryDigestSha256: string;
  /** Every mutating adapter checks this against its durable operation before writing. */
  fencingToken: string;
  signal: AbortSignal;
}

export interface TenantPortablePage<T> {
  items: readonly T[];
  /** Null marks completion. Cursors are scoped to module, snapshot and inventory digest. */
  nextCursor: string | null;
}

export interface TenantPortableValidationIssue {
  code: string;
  datasetId: string;
  recordId?: string;
}

export interface TenantPortableModulePlan {
  module: TenantPortabilityModuleId;
  version: 1;
  inputDigestSha256: string;
  targetFingerprintSha256: string;
  references: readonly TenantPortableDependency[];
  issues: readonly TenantPortableValidationIssue[];
}

/**
 * Storage adapters are supplied by the implementation, never loaded from a bundle.
 * Validation and planning have no writes. Import writes only into a fenced staging
 * target; the operation coordinator owns activation after all modules verify.
 */
export interface TenantPortabilityModule {
  id: TenantPortabilityModuleId;
  version: 1;
  enumerate(
    context: TenantPortabilityContext,
    cursor: string | null
  ): Promise<TenantPortablePage<TenantPortableDataset>>;
  exportChunk(
    context: TenantPortabilityContext,
    datasetId: string,
    cursor: string | null,
    maxBytes: number
  ): Promise<{ bytes: Uint8Array; nextCursor: string | null }>;
  validate(
    context: TenantPortabilityContext,
    datasetId: string,
    bytes: Uint8Array
  ): Promise<readonly TenantPortableValidationIssue[]>;
  plan(context: TenantPortabilityContext): Promise<TenantPortableModulePlan>;
  importChunk(
    context: TenantPortabilityContext,
    plan: TenantPortableModulePlan,
    datasetId: string,
    chunkId: string,
    bytes: Uint8Array
  ): Promise<void>;
  verify(
    context: TenantPortabilityContext,
    plan: TenantPortableModulePlan
  ): Promise<readonly TenantPortableValidationIssue[]>;
}

/** One receipt for every selected dataset, including empty and unavailable datasets. */
export interface TenantPortableDatasetReceipt {
  datasetId: string;
  schemaVersion: number;
  snapshotId: string;
  inventoryDigestSha256: string;
  status: 'captured' | 'rebuild_ready' | 'external_resolved' | 'unavailable';
}

/**
 * Completeness check before finalizing a bundle. These receipts are generated by trusted
 * adapters, not supplied by the client. Their presence does not replace adapter verification,
 * ownership checks, cryptographic validation or source-protection checks.
 */
export function validateTenantPortableDatasetCoverage(
  expected: readonly TenantPortableDataset[],
  receipts: readonly TenantPortableDatasetReceipt[],
  snapshot: { id: string; inventoryDigestSha256: string }
): TenantPortableValidationIssue[] {
  const issues: TenantPortableValidationIssue[] = [];
  const datasets = new Map<string, TenantPortableDataset>();
  const seen = new Set<string>();
  // An empty dataset still has a descriptor and a receipt. No descriptors cannot
  // prove a selected module was enumerated successfully.
  if (expected.length === 0) {
    issues.push({ code: 'missing_dataset_inventory', datasetId: '' });
  }
  for (const dataset of expected) {
    if (datasets.has(dataset.id)) {
      issues.push({ code: 'duplicate_dataset', datasetId: dataset.id });
    }
    datasets.set(dataset.id, dataset);
    if (!(TENANT_PORTABILITY_MODULES as readonly string[]).includes(dataset.module)) {
      issues.push({ code: 'unknown_module', datasetId: dataset.id });
    }
    if (dataset.disposition === 'unsupported') {
      issues.push({ code: 'unsupported_dataset', datasetId: dataset.id });
    }
  }
  for (const receipt of receipts) {
    const dataset = datasets.get(receipt.datasetId);
    if (!dataset) {
      issues.push({ code: 'unexpected_dataset', datasetId: receipt.datasetId });
      continue;
    }
    if (seen.has(receipt.datasetId)) {
      issues.push({ code: 'duplicate_receipt', datasetId: receipt.datasetId });
    }
    seen.add(receipt.datasetId);
    if (
      receipt.schemaVersion !== dataset.schemaVersion ||
      receipt.snapshotId !== snapshot.id ||
      receipt.inventoryDigestSha256 !== snapshot.inventoryDigestSha256
    ) {
      issues.push({ code: 'receipt_identity_mismatch', datasetId: dataset.id });
    }
    const requiredStatus = {
      include: 'captured',
      rebuild: 'rebuild_ready',
      external: 'external_resolved',
      unsupported: null,
    }[dataset.disposition];
    if (receipt.status !== requiredStatus) {
      issues.push({ code: 'dataset_not_ready', datasetId: dataset.id });
    }
  }
  for (const dataset of expected) {
    if (!seen.has(dataset.id)) {
      issues.push({ code: 'missing_dataset_receipt', datasetId: dataset.id });
    }
  }
  return issues;
}
