// Keep the portability inventory independent of Worker runtime globals.
export type TenantSettingValueType = 'number' | 'boolean' | 'string' | 'duration' | 'enum' | 'json';

/** Handling obligations, not permission to export or proof of an implemented adapter. */
export type TenantSettingHandling =
  | 'value'
  | 'key_reference'
  | 'logical_reference'
  | 'environment_mapping'
  | 'url_or_asset'
  | 'structured';

export interface TenantSettingFieldPolicy {
  category: string;
  key: string;
  type: TenantSettingValueType;
  handling: TenantSettingHandling;
}

// Explicit reviewed keys: do not derive this inventory dynamically from live metadata.
// A new field, moved category or changed type must fail the coverage check for review.
// Structured strings include JSON, CSS and HTML: their nested references need module
// validation. URL fields are never automatically fetched by the backup importer.
const REVIEWED_FIELDS: readonly [string, TenantSettingValueType, TenantSettingHandling, string][] =
  [
    [
      'oauth',
      'duration',
      'value',
      `
    oauth.access_token_expiry
    oauth.id_token_expiry
    oauth.refresh_token_expiry
    oauth.auth_code_ttl
    oauth.state_expiry
    oauth.nonce_expiry
    oauth.refresh_token_absolute_expiry
    oauth.par_default_ttl
    oauth.par_fapi_ttl
    oauth.https_request_uri_timeout_ms
  `,
    ],
    [
      'oauth',
      'boolean',
      'value',
      `
    oauth.refresh_token_rotation
    oauth.refresh_id_token_reissue
    oauth.offline_access_required
    oauth.refresh_token_sliding_window_enabled
    oauth.refresh_token_absolute_expiry_enabled
    oauth.state_required
    oauth.userinfo_require_openid
    oauth.sso_enabled
    oauth.https_request_uri_enabled
    oauth.id_token_signing_alg_client_override
  `,
    ],
    [
      'oauth',
      'enum',
      'value',
      `
    oauth.error_response_format
    oauth.error_id_mode
    oauth.id_token_signing_alg
  `,
    ],
    [
      'oauth',
      'number',
      'value',
      `
    oauth.max_codes_per_user
    oauth.https_request_uri_max_size
  `,
    ],
    [
      'oauth',
      'string',
      'url_or_asset',
      `
    oauth.https_request_uri_allowed_domains
  `,
    ],
    [
      'session',
      'duration',
      'value',
      `
    session.default_ttl
    session.max_ttl
    session.ttl.email_code
    session.ttl.directory_password
    session.ttl.direct_auth
    session.ttl.passkey
    session.ttl.passkey_registration
    session.ttl.admin_passkey
    session.ttl.guest
    session.ttl.did
    session.backchannel_logout_token_exp
    session.backchannel_request_timeout_ms
    session.backchannel_retry_initial_delay_ms
    session.backchannel_retry_max_delay_ms
  `,
    ],
    [
      'session',
      'boolean',
      'value',
      `
    session.refresh_default
  `,
    ],
    [
      'session',
      'number',
      'value',
      `
    session.backchannel_retry_max_attempts
    session.backchannel_retry_backoff_multiplier
  `,
    ],
    [
      'session',
      'enum',
      'value',
      `
    session.backchannel_on_failure
  `,
    ],
    [
      'security',
      'boolean',
      'value',
      `
    security.fapi_enabled
    security.fapi_strict_dpop
    security.fapi_allow_public_clients
    security.dpop_bound_access_tokens
    security.dpop_nonce_enabled
    security.pkce_required
    security.par_required
    security.https_redirect_only
    security.require_signed_request_object
    security.require_encrypted_request_object
  `,
    ],
    [
      'security',
      'string',
      'url_or_asset',
      `
    security.trusted_redirect_origins
  `,
    ],
    [
      'ciba',
      'duration',
      'value',
      `
    ciba.expires_in
    ciba.poll_interval
    ciba.slow_down_increment
    ciba.min_expires_in
    ciba.max_expires_in
    ciba.min_interval
    ciba.max_interval
    ciba.auth_request_ttl
    ciba.ping_notification_timeout_ms
    ciba.push_notification_timeout_ms
    ciba.notifier_default_timeout_ms
    ciba.notifier_max_timeout_ms
    ciba.notifier_retry_delay_base_ms
  `,
    ],
    [
      'ciba',
      'number',
      'value',
      `
    ciba.max_poll_count
    ciba.max_binding_message_length
  `,
    ],
    [
      'ciba',
      'boolean',
      'value',
      `
    ciba.binding_message_required
    ciba.user_code_enabled
  `,
    ],
    [
      'rate-limit',
      'number',
      'value',
      `
    rate_limit.strict
    rate_limit.moderate
    rate_limit.lenient
    rate_limit.email_max_requests
    rate_limit.auth_max_failed_attempts
  `,
    ],
    [
      'rate-limit',
      'duration',
      'value',
      `
    rate_limit.email_window
  `,
    ],
    [
      'device-flow',
      'duration',
      'value',
      `
    device_flow.expires_in
    device_flow.poll_interval
    device_flow.slow_down_increment
    device_flow.min_expires_in
    device_flow.max_expires_in
    device_flow.min_interval
    device_flow.max_interval
  `,
    ],
    [
      'device-flow',
      'number',
      'value',
      `
    device_flow.max_poll_count
    device_flow.user_code_length
  `,
    ],
    [
      'device-flow',
      'enum',
      'value',
      `
    device_flow.user_code_charset
  `,
    ],
    [
      'tokens',
      'boolean',
      'value',
      `
    tokens.exchange_enabled
    tokens.exchange_delegation_enabled
    tokens.exchange_impersonation_enabled
    tokens.introspection_strict_validation
    tokens.introspection_extended_claims
  `,
    ],
    [
      'tokens',
      'string',
      'value',
      `
    tokens.rbac_id_token_claims
    tokens.rbac_access_token_claims
  `,
    ],
    [
      'external-idp',
      'boolean',
      'value',
      `
    external_idp.jit_provisioning_enabled
    external_idp.jit_update_on_login
  `,
    ],
    [
      'external-idp',
      'json',
      'structured',
      `
    external_idp.jit_update_fields
  `,
    ],
    [
      'credentials',
      'duration',
      'value',
      `
    credentials.email_code_ttl
  `,
    ],
    [
      'federation',
      'boolean',
      'value',
      `
    federation.saml_enabled
  `,
    ],
    [
      'federation',
      'duration',
      'value',
      `
    federation.saml_assertion_ttl
    federation.saml_request_ttl
    federation.saml_artifact_ttl
    federation.saml_artifact_resolution_timeout
    federation.scim_token_max_expiry
    federation.scim_token_default_expiry
  `,
    ],
    [
      'federation',
      'enum',
      'value',
      `
    federation.saml_sso_binding
    federation.saml_slo_binding
    federation.saml_nameid_format
  `,
    ],
    [
      'client',
      'boolean',
      'value',
      `
    client.app_login_enabled
    client.sso_enabled
  `,
    ],
    [
      'client',
      'string',
      'url_or_asset',
      `
    client.default_audience
    client.default_resource
  `,
    ],
    [
      'feature-flags',
      'boolean',
      'value',
      `
    feature.enable_abac
    feature.enable_rebac
    feature.enable_policy_logging
    feature.enable_verified_attributes
    feature.enable_custom_rules
    feature.enable_policy_embedding
    feature.enable_id_level_permissions
    feature.enable_sd_jwt
    feature.enable_client_credentials
    feature.enable_custom_claims
    feature.enable_custom_claim_schemas
    feature.enable_custom_claim_schemas_introspection
    feature.enable_check_api
    feature.conformance_enabled
    feature.enable_flow_engine
  `,
    ],
    [
      'limits',
      'number',
      'value',
      `
    limits.max_embedded_permissions
    limits.max_resource_permissions
    limits.max_custom_claims
    limits.custom_claim_schemas_max_per_target
    limits.token_exchange_max_resource_params
    limits.token_exchange_max_audience_params
  `,
    ],
    [
      'tenant',
      'string',
      'url_or_asset',
      `
    tenant.allowed_origins
    tenant.allowed_domains
    tenant.allowed_identifiers
    tenant.logo_uri
    tenant.ui_base_url
  `,
    ],
    [
      'tenant',
      'enum',
      'value',
      `
    tenant.user_id_format
    tenant.browser_public_client_mode
    tenant.saml_attribute_release_failure_message_mode
  `,
    ],
    [
      'tenant',
      'string',
      'logical_reference',
      `
    tenant.audit_profile_id
    tenant.residency_profile_id
  `,
    ],
    [
      'tenant',
      'string',
      'value',
      `
    tenant.name
    tenant.ui_login_path
    tenant.ui_consent_path
    tenant.ui_reauth_path
    tenant.ui_error_path
  `,
    ],
    [
      'discovery',
      'string',
      'value',
      `
    discovery.claims_supported
    discovery.acr_values_supported
  `,
    ],
    [
      'plugin',
      'boolean',
      'value',
      `
    plugin.enabled
    plugin.auto_update_check
    plugin.notifier_resend_enabled
    plugin.notifier_console_enabled
  `,
    ],
    [
      'plugin',
      'duration',
      'value',
      `
    plugin.execution_timeout_ms
  `,
    ],
    [
      'plugin',
      'number',
      'value',
      `
    plugin.memory_limit_mb
  `,
    ],
    [
      'infrastructure',
      'string',
      'logical_reference',
      `
    infra.default_audit_profile_id
    infra.default_residency_profile_id
  `,
    ],
    [
      'assurance',
      'boolean',
      'value',
      `
    assurance.enabled
    assurance.include_in_id_token
    assurance.include_in_access_token
    assurance.fal2_requires_dpop
    assurance.fal3_requires_par
  `,
    ],
    [
      'assurance',
      'enum',
      'value',
      `
    assurance.default_aal
    assurance.default_fal
    assurance.default_ial
  `,
    ],
    [
      'assurance',
      'number',
      'value',
      `
    assurance.scim_max_ial
  `,
    ],
    [
      'assurance',
      'string',
      'structured',
      `
    assurance.scope_aal_requirements
    assurance.upstream_acr_mappings
    assurance.outbound_acr_mappings
    assurance.scope_ial_requirements
    assurance.ial_assurance_values
    assurance.saml_authn_context_aal
    assurance.ida_profile
  `,
    ],
    [
      'check-api-audit',
      'boolean',
      'value',
      `
    audit.check_api_enabled
  `,
    ],
    [
      'check-api-audit',
      'enum',
      'value',
      `
    audit.check_api_mode
    audit.check_api_log_allow
  `,
    ],
    [
      'check-api-audit',
      'number',
      'value',
      `
    audit.check_api_sample_rate
    audit.check_api_retention_days
  `,
    ],
    [
      'dcr',
      'boolean',
      'value',
      `
    dcr.enabled
    dcr.require_initial_access_token
    dcr.scope_restriction_enabled
    dcr.allow_duplicate_software_id
  `,
    ],
    [
      'login-ui',
      'enum',
      'value',
      `
    login-ui.theme
    login-ui.theme_template
    login-ui.page_layout
    login-ui.font_family
    login-ui.font_scale
    login-ui.logo_display
    login-ui.default_locale
    login-ui.topbar_position
    login-ui.language_switcher_position
    login-ui.header_style
    login-ui.footer_style
    login-ui.logo_layout
    login-ui.split_frame
    login-ui.split_panel_side
    login-ui.split_panel_width
    login-ui.split_background_mode
    login-ui.brand_content_mode
    login-ui.brand_position
    login-ui.brand_align
  `,
    ],
    [
      'login-ui',
      'number',
      'value',
      `
    login-ui.published_version
    login-ui.login_panel_background_opacity
    login-ui.account_page_published_version
  `,
    ],
    [
      'login-ui',
      'string',
      'value',
      `
    login-ui.published_at
    login-ui.background_color
    login-ui.accent_color
    login-ui.title_color
    login-ui.text_color
    login-ui.copy_color
    login-ui.brand_name
    login-ui.brand_panel_title
    login-ui.brand_panel_text
    login-ui.supported_locales
    login-ui.login_panel_background_color
    login-ui.login_panel_background_gradient_color
    login-ui.header_text
    login-ui.account_page_published_at
  `,
    ],
    [
      'login-ui',
      'string',
      'structured',
      `
    login-ui.published_snapshot
    login-ui.rollback_snapshot
    login-ui.custom_css
    login-ui.text_localizations
    login-ui.footer_text
    login-ui.footer_links
    login-ui.custom_blocks
    login-ui.custom_themes
    login-ui.account_pages
    login-ui.account_page_draft
    login-ui.account_page_published
  `,
    ],
    [
      'login-ui',
      'string',
      'url_or_asset',
      `
    login-ui.logo_url
    login-ui.favicon_url
    login-ui.thumbnail_url
    login-ui.background_image_url
    login-ui.login_panel_background_image_url
  `,
    ],
    [
      'login-ui',
      'json',
      'structured',
      `
    login-ui.primary_locales
  `,
    ],
    [
      'login-ui',
      'boolean',
      'value',
      `
    login-ui.show_english_language_names
    login-ui.header_enabled
    login-ui.subtitle_enabled
    login-ui.footer_enabled
    login-ui.powered_by_enabled
    login-ui.auth_switch_link_enabled
    login-ui.theme_toggle_enabled
    login-ui.language_select_enabled
  `,
    ],
    [
      'authentication-methods',
      'boolean',
      'value',
      `
    authentication-methods.email_otp.guest_upgrade_enabled
    authentication-methods.passkey.guest_upgrade_enabled
    authentication-methods.guest.login_enabled
    authentication-methods.passkey.login_enabled
    authentication-methods.passkey.signup_enabled
    authentication-methods.passkey.reauth_enabled
    authentication-methods.passkey.account_link_enabled
    authentication-methods.email_otp.login_enabled
    authentication-methods.email_otp.signup_enabled
    authentication-methods.email_otp.reauth_enabled
    authentication-methods.email_otp.account_link_enabled
    authentication-methods.totp.login_enabled
    authentication-methods.totp.signup_enabled
    authentication-methods.totp.reauth_enabled
    authentication-methods.totp.account_link_enabled
    authentication-methods.human_verification.login_enabled
    authentication-methods.human_verification.signup_enabled
    authentication-methods.human_verification.reauth_enabled
    authentication-methods.directory_password.enabled
  `,
    ],
    [
      'authentication-methods',
      'duration',
      'value',
      `
    authentication-methods.cache_ttl
  `,
    ],
    [
      'authentication-methods',
      'string',
      'structured',
      `
    authentication-methods.external_providers
  `,
    ],
    [
      'authentication-methods',
      'string',
      'value',
      `
    authentication-methods.totp.preset
    authentication-methods.totp.default_acr
  `,
    ],
    [
      'authentication-methods',
      'json',
      'structured',
      `
    authentication-methods.totp.requirement_policy
    authentication-methods.external_provider_usage
  `,
    ],
    [
      'authentication-methods',
      'string',
      'logical_reference',
      `
    authentication-methods.human_verification.provider
  `,
    ],
    [
      'account-lifecycle',
      'boolean',
      'value',
      `
    account-lifecycle.guest.deletion_enabled
    account-lifecycle.guest.upgrade_enabled
  `,
    ],
    [
      'account-lifecycle',
      'number',
      'value',
      `
    account-lifecycle.guest.deletion_after_days
    account-lifecycle.guest.upgrade_hold_minutes
  `,
    ],
    [
      'diagnostic-logging',
      'boolean',
      'value',
      `
    diagnostic-logging.enabled
    diagnostic-logging.http_request_enabled
    diagnostic-logging.http_response_enabled
    diagnostic-logging.token_validation_enabled
    diagnostic-logging.auth_decision_enabled
    diagnostic-logging.r2_output_enabled
    diagnostic-logging.filter_pii
    diagnostic-logging.filter_tokens
    diagnostic-logging.http_body_schema_aware
    diagnostic-logging.sdk_ingest_enabled
    diagnostic-logging.merged_output_enabled
  `,
    ],
    [
      'diagnostic-logging',
      'enum',
      'value',
      `
    diagnostic-logging.log_level
    diagnostic-logging.output_format
    diagnostic-logging.buffer_strategy
    diagnostic-logging.storage_mode.default
  `,
    ],
    [
      'diagnostic-logging',
      'string',
      'environment_mapping',
      `
    diagnostic-logging.r2_bucket_binding
    diagnostic-logging.r2_path_prefix
  `,
    ],
    [
      'diagnostic-logging',
      'number',
      'value',
      `
    diagnostic-logging.batch_size
    diagnostic-logging.batch_interval_ms
    diagnostic-logging.token_hash_prefix_length
    diagnostic-logging.retention_days
  `,
    ],
    [
      'diagnostic-logging',
      'string',
      'value',
      `
    diagnostic-logging.http_safe_headers
  `,
    ],
    [
      'diagnostic-logging',
      'string',
      'structured',
      `
    diagnostic-logging.storage_mode.by_client
  `,
    ],
    [
      'dr-backup',
      'string',
      'environment_mapping',
      `
    dr-backup.storage_destination_id
  `,
    ],
    [
      'login-entry',
      'boolean',
      'value',
      `
    login-entry.override_enabled
    login-entry.allow_manual_tenant_entry
    login-entry.remember_last_tenant
    login-entry.redirect_default_login_to_discovery
    login-entry.require_common_discovery_before_login
    login-entry.skip_discovery_if_only_one_tenant
    login-entry.redirect_tenant_discover_to_common_entry
  `,
    ],
    [
      'login-entry',
      'enum',
      'value',
      `
    login-entry.mode
    login-entry.email_resolution_policy
    login-entry.selection_policy
    login-entry.post_login_behavior
  `,
    ],
    [
      'login-entry',
      'string',
      'structured',
      `
    login-entry.discovery_methods
  `,
    ],
    [
      'login-entry',
      'string',
      'url_or_asset',
      `
    login-entry.post_login_redirect_url
    login-entry.app_login_redirect_uri
    login-entry.app_login_final_return_to
  `,
    ],
    [
      'login-entry',
      'string',
      'logical_reference',
      `
    login-entry.app_login_client_id
    login-entry.app_login_scope
  `,
    ],
    [
      'tenant-discovery-ui',
      'boolean',
      'value',
      `
    tenant-discovery-ui.override_enabled
    tenant-discovery-ui.inherit_from_login_ui
  `,
    ],
    [
      'tenant-discovery-ui',
      'enum',
      'value',
      `
    tenant-discovery-ui.theme
  `,
    ],
    [
      'tenant-discovery-ui',
      'string',
      'value',
      `
    tenant-discovery-ui.brand_name
    tenant-discovery-ui.page_title
    tenant-discovery-ui.kicker_text
    tenant-discovery-ui.title_text
    tenant-discovery-ui.subtitle_text
  `,
    ],
    [
      'tenant-discovery-ui',
      'string',
      'url_or_asset',
      `
    tenant-discovery-ui.logo_url
  `,
    ],
    [
      'support-ops',
      'boolean',
      'value',
      `
    support_ops.allow_self_approval
  `,
    ],
    [
      'support-ops',
      'enum',
      'value',
      `
    support_ops.duty_separation
  `,
    ],
    [
      'self-service',
      'boolean',
      'value',
      `
    self-service.account_page_enabled
  `,
    ],
    [
      'self-service',
      'string',
      'value',
      `
    self-service.account_page_path
  `,
    ],
    [
      'self-service',
      'number',
      'value',
      `
    self-service.reauth_ttl_seconds
  `,
    ],
    [
      'service-site',
      'boolean',
      'value',
      `
    service-site.fallback_enabled
  `,
    ],
    [
      'oauth',
      'enum',
      'value',
      `
    oauth.error_locale
  `,
    ],
    [
      'oauth',
      'json',
      'structured',
      `
    oauth.response_types_supported
    oauth.token_endpoint_auth_methods_supported
  `,
    ],
    [
      'security',
      'boolean',
      'value',
      `
    security.allow_unsigned_request_object
    security.fapi_require_private_key_jwt
    security.fapi_message_signing_enabled
    security.require_jarm
  `,
    ],
    [
      'security',
      'enum',
      'value',
      `
    security.dpop_required
    security.fapi_client_assertion_audience
    security.default_authorization_signing_alg
  `,
    ],
    [
      'security',
      'string',
      'value',
      `
    security.request_object_signing_algs
    security.authorization_signing_algs
  `,
    ],
    [
      'security',
      'json',
      'url_or_asset',
      `
    security.dpop_nonce_resource_overrides
  `,
    ],
    [
      'security',
      'number',
      'value',
      `
    security.request_object_max_age_seconds
    security.request_object_max_lifetime_seconds
    security.request_object_clock_skew_seconds
  `,
    ],
    [
      'feature-flags',
      'boolean',
      'value',
      `
    feature.enable_rar
    feature.enable_ai_scopes
    feature.enable_ai_ephemeral_auth
    feature.enable_id_jag
  `,
    ],
    [
      'tokens',
      'string',
      'value',
      `
    tokens.exchange_allowed_subject_token_types
  `,
    ],
    [
      'tokens',
      'string',
      'url_or_asset',
      `
    tokens.introspection_expected_audience
  `,
    ],
    [
      'tokens',
      'json',
      'url_or_asset',
      `
    tokens.id_jag_allowed_issuers
  `,
    ],
    [
      'tokens',
      'number',
      'value',
      `
    tokens.id_jag_max_token_lifetime
  `,
    ],
    [
      'tokens',
      'boolean',
      'value',
      `
    tokens.id_jag_include_tenant_claim
    tokens.id_jag_require_confidential_client
  `,
    ],
    [
      'limits',
      'number',
      'value',
      `
    limits.check_api_batch_size
  `,
    ],
    [
      'session',
      'boolean',
      'value',
      `
    session.backchannel_enabled
    session.backchannel_include_sub
    session.backchannel_include_sid
    session.frontchannel_enabled
    session.session_management_enabled
    session.check_session_iframe_enabled
    session.logout_webhook_enabled
    session.logout_webhook_include_sub
    session.logout_webhook_include_sid
  `,
    ],
    [
      'rate-limit',
      'number',
      'value',
      `
    rate_limit.public_read
    rate_limit.login_start
    rate_limit.send_challenge
    rate_limit.loadtest
    rate_limit.strict_window_seconds
    rate_limit.moderate_window_seconds
    rate_limit.lenient_window_seconds
    rate_limit.public_read_window_seconds
    rate_limit.login_start_window_seconds
    rate_limit.send_challenge_window_seconds
    rate_limit.loadtest_window_seconds
  `,
    ],
    [
      'external-idp',
      'boolean',
      'value',
      `
    external_idp.jit_require_verified_email
    external_idp.jit_join_all_matching_orgs
    external_idp.jit_allow_user_without_org
    external_idp.jit_allow_unverified_domain_mappings
  `,
    ],
    [
      'external-idp',
      'string',
      'logical_reference',
      `
    external_idp.jit_allowed_provider_ids
    external_idp.jit_default_role_id
  `,
    ],
    [
      'tenant',
      'string',
      'value',
      `
    tenant.ui_device_path
    tenant.ui_device_authorize_path
    tenant.ui_logout_complete_path
    tenant.ui_logged_out_path
    tenant.ui_register_path
  `,
    ],
  ];

export const TENANT_SETTING_FIELD_POLICIES: readonly TenantSettingFieldPolicy[] =
  REVIEWED_FIELDS.flatMap(([category, type, handling, keys]) =>
    keys
      .trim()
      .split(/\s+/)
      .map((key) => ({ category, type, handling, key }))
  );

export function checkTenantSettingFieldCoverage(
  actual: readonly { category: string; key: string; type: string }[],
  policies: readonly TenantSettingFieldPolicy[] = TENANT_SETTING_FIELD_POLICIES
): { unclassified: string[]; stale: string[]; duplicates: string[]; changedShape: string[] } {
  const declared = new Map<string, TenantSettingFieldPolicy>();
  const observed = new Set<string>();
  const duplicates = new Set<string>();
  const unclassified = new Set<string>();
  const changedShape = new Set<string>();
  for (const policy of policies) {
    if (declared.has(policy.key)) duplicates.add(policy.key);
    declared.set(policy.key, policy);
  }
  for (const field of actual) {
    if (observed.has(field.key)) duplicates.add(field.key);
    observed.add(field.key);
    const policy = declared.get(field.key);
    if (!policy) unclassified.add(field.key);
    else if (policy.category !== field.category || policy.type !== field.type) {
      changedShape.add(field.key);
    }
  }
  return {
    unclassified: [...unclassified].sort(),
    stale: [...declared.keys()].filter((key) => !observed.has(key)).sort(),
    duplicates: [...duplicates].sort(),
    changedShape: [...changedShape].sort(),
  };
}
