// Keep the portability inventory independent of Worker runtime globals.
export type TenantSettingValueType = 'number' | 'boolean' | 'string' | 'duration' | 'enum' | 'json';

/** Handling obligations, not permission to export or proof of an implemented adapter. */
export type TenantSettingHandling =
  | 'value'
  | 'key_reference'
  | 'logical_reference'
  | 'environment_mapping'
  | 'url_or_asset'
  | 'structured';

export interface TenantSettingFieldPolicy {
  category: string;
  key: string;
  type: TenantSettingValueType;
  handling: TenantSettingHandling;
}

// Explicit reviewed keys: do not derive this inventory dynamically from live metadata.
// A new field, moved category or changed type must fail the coverage check for review.
// Structured strings include JSON, CSS and HTML: their nested references need module
// validation. URL fields are never automatically fetched by the backup importer.
const REVIEWED_FIELDS: readonly [string, TenantSettingValueType, TenantSettingHandling, string][] =
  [
    [
      'oauth',
      'duration',
      'value',
      `
    oauth.access_token_expiry
    oauth.id_token_expiry
    oauth.refresh_token_expiry
    oauth.auth_code_ttl
    oauth.state_expiry
    oauth.nonce_expiry
    oauth.refresh_token_absolute_expiry
    oauth.par_default_ttl
    oauth.par_fapi_ttl
    oauth.https_request_uri_timeout_ms
  `,
    ],
    [
      'oauth',
      'boolean',
      'value',
      `
    oauth.refresh_token_rotation
    oauth.refresh_id_token_reissue
    oauth.offline_access_required
    oauth.refresh_token_sliding_window_enabled
    oauth.refresh_token_absolute_expiry_enabled
    oauth.refresh_token_remaining_expiry_inherit
    oauth.state_required
    oauth.scope_required
    oauth.userinfo_require_openid
    oauth.sso_enabled
    oauth.error_description
    oauth.error_uri
    oauth.iss_response_param
    oauth.jarm_enabled
    oauth.https_request_uri_enabled
  `,
    ],
    [
      'oauth',
      'enum',
      'value',
      `
    oauth.id_token_aud_format
    oauth.prompt_none_behavior
    oauth.error_response_format
    oauth.error_id_mode
    oauth.default_response_mode
    oauth.backchannel_token_delivery_mode
  `,
    ],
    [
      'oauth',
      'string',
      'value',
      `
    oauth.id_token_signing_alg
    oauth.response_modes_supported
    oauth.backchannel_token_delivery_modes_supported
  `,
    ],
    [
      'oauth',
      'number',
      'value',
      `
    oauth.max_codes_per_user
    oauth.https_request_uri_max_size
  `,
    ],
    [
      'oauth',
      'string',
      'url_or_asset',
      `
    oauth.https_request_uri_allowed_domains
  `,
    ],
    [
      'session',
      'duration',
      'value',
      `
    session.default_ttl
    session.max_ttl
    session.min_ttl
    session.ttl.email_code
    session.ttl.directory_password
    session.ttl.direct_auth
    session.ttl.passkey
    session.ttl.passkey_registration
    session.ttl.admin_passkey
    session.ttl.guest
    session.ttl.did
    session.token_ttl
    session.tombstone_ttl
    session.backchannel_logout_token_exp
    session.backchannel_request_timeout_ms
    session.backchannel_retry_initial_delay_ms
    session.backchannel_retry_max_delay_ms
  `,
    ],
    [
      'session',
      'boolean',
      'value',
      `
    session.refresh_default
  `,
    ],
    [
      'session',
      'number',
      'value',
      `
    session.backchannel_retry_max_attempts
    session.backchannel_retry_backoff_multiplier
  `,
    ],
    [
      'session',
      'enum',
      'value',
      `
    session.backchannel_on_failure
  `,
    ],
    [
      'security',
      'boolean',
      'value',
      `
    security.fapi_enabled
    security.fapi_strict_dpop
    security.fapi_allow_public_clients
    security.dpop_bound_access_tokens
    security.dpop_nonce_enabled
    security.enable_abac
    security.enable_rebac
    security.enable_policy_logging
    security.enable_verified_attributes
    security.pkce_required
    security.pkce_s256_required
    security.par_required
    security.nonce_required
    security.https_redirect_only
    security.allow_http_redirect
    security.loopback_flexible_port
    security.https_request_uri
    security.token_binding_required
    security.mutual_tls_required
    security.sender_constrained_tokens
    security.require_signed_request_object
    security.require_encrypted_request_object
    security.ip_allowlist_enabled
    security.ip_blocklist_enabled
  `,
    ],
    [
      'security',
      'duration',
      'value',
      `
    security.dpop_nonce_ttl
    security.dpop_jti_ttl
    security.min_response_time
    security.jitter
  `,
    ],
    [
      'security',
      'number',
      'value',
      `
    security.jwt_clock_skew_seconds
    security.saml_clock_skew_seconds
  `,
    ],
    [
      'security',
      'string',
      'url_or_asset',
      `
    security.trusted_redirect_origins
  `,
    ],
    [
      'ciba',
      'duration',
      'value',
      `
    ciba.expires_in
    ciba.poll_interval
    ciba.slow_down_increment
    ciba.min_expires_in
    ciba.max_expires_in
    ciba.min_interval
    ciba.max_interval
    ciba.auth_request_ttl
    ciba.ping_notification_timeout_ms
    ciba.push_notification_timeout_ms
    ciba.notifier_default_timeout_ms
    ciba.notifier_max_timeout_ms
    ciba.notifier_retry_delay_base_ms
  `,
    ],
    [
      'ciba',
      'number',
      'value',
      `
    ciba.max_poll_count
    ciba.max_binding_message_length
  `,
    ],
    [
      'ciba',
      'boolean',
      'value',
      `
    ciba.binding_message_required
    ciba.user_code_enabled
  `,
    ],
    [
      'rate-limit',
      'number',
      'value',
      `
    rate_limit.strict
    rate_limit.moderate
    rate_limit.lenient
    rate_limit.email_max_requests
    rate_limit.auth_max_failed_attempts
  `,
    ],
    [
      'rate-limit',
      'duration',
      'value',
      `
    rate_limit.window_ms
    rate_limit.email_window
  `,
    ],
    [
      'device-flow',
      'duration',
      'value',
      `
    device_flow.expires_in
    device_flow.poll_interval
    device_flow.slow_down_increment
    device_flow.min_expires_in
    device_flow.max_expires_in
    device_flow.min_interval
    device_flow.max_interval
  `,
    ],
    [
      'device-flow',
      'number',
      'value',
      `
    device_flow.max_poll_count
    device_flow.user_code_length
  `,
    ],
    [
      'device-flow',
      'enum',
      'value',
      `
    device_flow.user_code_charset
  `,
    ],
    [
      'tokens',
      'boolean',
      'value',
      `
    tokens.exchange_enabled
    tokens.exchange_delegation_enabled
    tokens.exchange_impersonation_enabled
    tokens.introspection_require_client_auth
    tokens.introspection_strict_validation
    tokens.introspection_extended_claims
    tokens.access_token_singularization
  `,
    ],
    [
      'tokens',
      'duration',
      'value',
      `
    tokens.introspection_cache_ttl
    tokens.introspection_cache_inactive
  `,
    ],
    [
      'tokens',
      'number',
      'value',
      `
    tokens.introspection_cache_max_size
  `,
    ],
    [
      'tokens',
      'string',
      'key_reference',
      `
    tokens.access_token_signing_key_id
    tokens.id_token_signing_key_id
    tokens.userinfo_signing_key_id
  `,
    ],
    [
      'tokens',
      'string',
      'value',
      `
    tokens.rbac_id_token_claims
    tokens.rbac_access_token_claims
  `,
    ],
    [
      'external-idp',
      'boolean',
      'value',
      `
    external_idp.jit_provisioning_enabled
    external_idp.jit_update_on_login
    external_idp.token_encryption_enabled
  `,
    ],
    [
      'external-idp',
      'duration',
      'value',
      `
    external_idp.jwks_cache_ttl
    external_idp.jwks_fetch_timeout_ms
    external_idp.request_timeout_ms
  `,
    ],
    [
      'credentials',
      'duration',
      'value',
      `
    credentials.passkey_registration_ttl
    credentials.passkey_expiry
    credentials.email_code_ttl
    credentials.did_link_ttl
    credentials.did_auth_ttl
    credentials.did_session_ttl
  `,
    ],
    [
      'credentials',
      'number',
      'value',
      `
    credentials.email_code_length
  `,
    ],
    [
      'federation',
      'boolean',
      'value',
      `
    federation.saml_enabled
    federation.allow_unverified_email
    federation.auto_link_accounts
    federation.require_signed_requests
  `,
    ],
    [
      'federation',
      'duration',
      'value',
      `
    federation.saml_assertion_ttl
    federation.saml_request_ttl
    federation.saml_artifact_ttl
    federation.saml_artifact_resolution_timeout
    federation.scim_lockout_seconds
    federation.scim_failure_window_seconds
    federation.scim_token_min_expiry
    federation.scim_token_max_expiry
    federation.scim_token_default_expiry
    federation.metadata_cache_ttl
  `,
    ],
    [
      'federation',
      'enum',
      'value',
      `
    federation.saml_sso_binding
    federation.saml_slo_binding
    federation.saml_nameid_format
  `,
    ],
    [
      'federation',
      'number',
      'value',
      `
    federation.scim_default_page_size
    federation.scim_max_page_size
    federation.scim_max_filter_complexity
  `,
    ],
    [
      'client',
      'duration',
      'value',
      `
    client.access_token_ttl
    client.refresh_token_ttl
    client.id_token_ttl
  `,
    ],
    [
      'client',
      'boolean',
      'value',
      `
    client.pkce_required
    client.par_required
    client.dpop_required
    client.app_login_enabled
    client.sso_enabled
    client.refresh_token_rotation
    client.reuse_refresh_token
    client.allow_authorization_code
    client.allow_client_credentials
    client.allow_refresh_token
    client.allow_device_code
    client.allow_ciba
    client.allow_code_response
    client.allow_token_response
    client.allow_id_token_response
    client.strict_redirect_matching
    client.allow_localhost_redirect
    client.dpop_bound_access_tokens
    client.token_exchange_allowed
    client.frontchannel_logout_session_required
    client.backchannel_logout_session_required
    client.allowed_scopes_restriction_enabled
    client.client_credentials_allowed
    client.native_sso_enabled
    client.native_channel_allowed
    client.require_auth_time
  `,
    ],
    [
      'client',
      'enum',
      'value',
      `
    client.userinfo_signed_response_alg
    client.token_endpoint_auth_method
    client.subject_type
    client.dpop_mode
    client.delegation_mode
    client.application_type
    client.browser_public_client_mode
    client.browser_refresh_token_policy
    client.id_token_signing_alg
    client.id_token_encrypted_response_alg
    client.id_token_encrypted_response_enc
    client.userinfo_encrypted_response_alg
    client.userinfo_encrypted_response_enc
    client.request_object_signing_alg
    client.request_object_encryption_alg
    client.request_object_encryption_enc
    client.jwt_bearer_signing_alg
    client.token_endpoint_auth_signing_alg
  `,
    ],
    [
      'client',
      'string',
      'value',
      `
    client.grant_types
    client.response_types
    client.contacts
    client.allowed_channels
    client.default_acr_values
  `,
    ],
    [
      'client',
      'string',
      'url_or_asset',
      `
    client.frontchannel_logout_uri
    client.backchannel_logout_uri
    client.default_audience
    client.default_resource
    client.logo_uri
    client.tos_uri
    client.policy_uri
    client.client_uri
    client.initiate_login_uri
    client.login_ui_url
    client.sector_identifier_uri
    client.request_uris
  `,
    ],
    [
      'client',
      'string',
      'logical_reference',
      `
    client.allowed_scopes
    client.default_scope
    client.trust_group
  `,
    ],
    [
      'client',
      'number',
      'value',
      `
    client.default_max_age
  `,
    ],
    [
      'cache',
      'duration',
      'value',
      `
    cache.jwks
    cache.api_key
    cache.default
    cache.config
    cache.plugin_context
    cache.tenant_context
    cache.ec_key
    cache.introspection_key
    cache.challenge_shard
    cache.refresh_token_shard
    cache.region_shard
    cache.status_list
    cache.status_list_jwks
    cache.feature_flags
    cache.version_check
    cache.token_revocation
    cache.user
    cache.consent
    cache.partition_settings
    cache.rules
    cache.rbac
    cache.introspection
  `,
    ],
    [
      'feature-flags',
      'boolean',
      'value',
      `
    feature.enable_abac
    feature.enable_rebac
    feature.enable_policy_logging
    feature.enable_verified_attributes
    feature.enable_custom_rules
    feature.enable_policy_embedding
    feature.enable_id_level_permissions
    feature.enable_sd_jwt
    feature.enable_token_exchange
    feature.enable_client_credentials
    feature.enable_custom_claims
    feature.enable_test_endpoints
    feature.enable_check_api
    feature.enable_mock_auth
    feature.introspection_cache_enabled
    feature.conformance_enabled
    feature.conformance_use_builtin_forms
    feature.enable_flow_engine
  `,
    ],
    [
      'limits',
      'number',
      'value',
      `
    limits.max_query_limit
    limits.default_batch_size
    limits.max_embedded_permissions
    limits.max_resource_permissions
    limits.max_custom_claims
    limits.token_exchange_max_resource_params
    limits.token_exchange_max_audience_params
  `,
    ],
    [
      'tenant',
      'string',
      'url_or_asset',
      `
    tenant.base_domain
    tenant.allowed_origins
    tenant.allowed_domains
    tenant.allowed_identifiers
    tenant.logo_uri
    tenant.tos_uri
    tenant.policy_uri
    tenant.ui_base_url
  `,
    ],
    [
      'tenant',
      'string',
      'environment_mapping',
      `
    tenant.default_id
  `,
    ],
    [
      'tenant',
      'boolean',
      'value',
      `
    tenant.isolation_enabled
  `,
    ],
    [
      'tenant',
      'enum',
      'value',
      `
    tenant.user_id_format
    tenant.browser_public_client_mode
    tenant.saml_attribute_release_failure_message_mode
  `,
    ],
    [
      'tenant',
      'string',
      'logical_reference',
      `
    tenant.audit_profile_id
    tenant.residency_profile_id
  `,
    ],
    [
      'tenant',
      'string',
      'value',
      `
    tenant.name
    tenant.ui_login_path
    tenant.ui_consent_path
    tenant.ui_reauth_path
    tenant.ui_error_path
  `,
    ],
    [
      'vc',
      'duration',
      'value',
      `
    vc.vp_request_expiry
    vc.c_nonce_expiry
    vc.credential_offer_expiry
    vc.pop_validity
    vc.pop_clock_skew
    vc.did_cache_ttl
  `,
    ],
    [
      'discovery',
      'string',
      'value',
      `
    discovery.claims_supported
    discovery.claims_locales_supported
    discovery.acr_values_supported
  `,
    ],
    [
      'plugin',
      'boolean',
      'value',
      `
    plugin.enabled
    plugin.auto_update_check
    plugin.notifier_resend_enabled
    plugin.notifier_console_enabled
  `,
    ],
    [
      'plugin',
      'duration',
      'value',
      `
    plugin.execution_timeout_ms
  `,
    ],
    [
      'plugin',
      'number',
      'value',
      `
    plugin.memory_limit_mb
  `,
    ],
    [
      'infrastructure',
      'duration',
      'value',
      `
    infra.config_cache_ttl
    infra.tenant_context_cache_ttl
    infra.key_cache_ttl
    infra.jwks_cache_ttl
    infra.feature_flags_cache_ttl
    infra.retry_initial_delay
    infra.retry_max_delay
    infra.default_fetch_timeout_ms
    infra.do_cleanup_interval
    infra.do_audit_flush_delay
    infra.do_saml_request_expiry
    infra.do_saml_artifact_expiry
  `,
    ],
    [
      'infrastructure',
      'number',
      'value',
      `
    infra.retry_max
    infra.backoff_multiplier
  `,
    ],
    [
      'infrastructure',
      'string',
      'value',
      `
    infra.supported_signing_algs
    infra.dpop_signing_alg_values_supported
  `,
    ],
    [
      'infrastructure',
      'string',
      'logical_reference',
      `
    infra.default_audit_profile_id
    infra.default_residency_profile_id
  `,
    ],
    [
      'encryption',
      'boolean',
      'value',
      `
    encryption.key_rotation_enabled
    encryption.pii_encryption_enabled
    encryption.domain_hash_enabled
    encryption.rp_token_encryption_enabled
  `,
    ],
    [
      'encryption',
      'duration',
      'value',
      `
    encryption.key_rotation_interval
    encryption.key_overlap_period
    encryption.domain_hash_salt_rotation
  `,
    ],
    [
      'encryption',
      'string',
      'value',
      `
    encryption.default_signing_alg
    encryption.default_encryption_alg
    encryption.default_encryption_enc
    encryption.pii_key_derivation
    encryption.pii_fields
    encryption.password_version
  `,
    ],
    [
      'encryption',
      'enum',
      'value',
      `
    encryption.pii_algorithm
  `,
    ],
    [
      'encryption',
      'string',
      'key_reference',
      `
    encryption.pii_key_version
  `,
    ],
    [
      'encryption',
      'number',
      'value',
      `
    encryption.password_iterations
  `,
    ],
    [
      'assurance',
      'boolean',
      'value',
      `
    assurance.enabled
    assurance.include_in_id_token
    assurance.include_in_access_token
    assurance.fal2_requires_dpop
    assurance.fal3_requires_par
  `,
    ],
    [
      'assurance',
      'enum',
      'value',
      `
    assurance.default_aal
    assurance.default_fal
    assurance.default_ial
  `,
    ],
    [
      'assurance',
      'string',
      'structured',
      `
    assurance.scope_aal_requirements
  `,
    ],
    [
      'check-api-audit',
      'boolean',
      'value',
      `
    audit.check_api_enabled
  `,
    ],
    [
      'check-api-audit',
      'enum',
      'value',
      `
    audit.check_api_mode
    audit.check_api_log_allow
  `,
    ],
    [
      'check-api-audit',
      'number',
      'value',
      `
    audit.check_api_sample_rate
    audit.check_api_retention_days
  `,
    ],
    [
      'dcr',
      'boolean',
      'value',
      `
    dcr.enabled
    dcr.require_initial_access_token
    dcr.scope_restriction_enabled
    dcr.allow_duplicate_software_id
  `,
    ],
    [
      'login-ui',
      'enum',
      'value',
      `
    login-ui.theme
    login-ui.variant
    login-ui.theme_template
    login-ui.page_layout
    login-ui.font_family
    login-ui.font_scale
    login-ui.logo_display
    login-ui.default_locale
    login-ui.topbar_position
    login-ui.language_switcher_position
    login-ui.header_style
    login-ui.footer_style
    login-ui.logo_layout
    login-ui.split_frame
    login-ui.split_panel_side
    login-ui.split_panel_width
    login-ui.split_background_mode
    login-ui.brand_content_mode
    login-ui.brand_position
    login-ui.brand_align
  `,
    ],
    [
      'login-ui',
      'number',
      'value',
      `
    login-ui.published_version
    login-ui.login_panel_background_opacity
    login-ui.account_page_published_version
  `,
    ],
    [
      'login-ui',
      'string',
      'value',
      `
    login-ui.published_at
    login-ui.background_color
    login-ui.accent_color
    login-ui.title_color
    login-ui.text_color
    login-ui.copy_color
    login-ui.brand_name
    login-ui.brand_panel_title
    login-ui.brand_panel_text
    login-ui.supported_locales
    login-ui.login_panel_background_color
    login-ui.login_panel_background_gradient_color
    login-ui.header_text
    login-ui.account_page_published_at
  `,
    ],
    [
      'login-ui',
      'string',
      'structured',
      `
    login-ui.published_snapshot
    login-ui.rollback_snapshot
    login-ui.custom_css
    login-ui.text_localizations
    login-ui.footer_text
    login-ui.footer_links
    login-ui.custom_blocks
    login-ui.custom_themes
    login-ui.account_pages
    login-ui.account_page_draft
    login-ui.account_page_published
  `,
    ],
    [
      'login-ui',
      'string',
      'url_or_asset',
      `
    login-ui.logo_url
    login-ui.favicon_url
    login-ui.thumbnail_url
    login-ui.background_image_url
    login-ui.login_panel_background_image_url
  `,
    ],
    [
      'login-ui',
      'json',
      'structured',
      `
    login-ui.primary_locales
  `,
    ],
    [
      'login-ui',
      'boolean',
      'value',
      `
    login-ui.show_english_language_names
    login-ui.header_enabled
    login-ui.subtitle_enabled
    login-ui.footer_enabled
    login-ui.powered_by_enabled
    login-ui.auth_switch_link_enabled
    login-ui.theme_toggle_enabled
    login-ui.language_select_enabled
  `,
    ],
    [
      'authentication-methods',
      'boolean',
      'value',
      `
    authentication-methods.email_otp.guest_upgrade_enabled
    authentication-methods.passkey.guest_upgrade_enabled
    authentication-methods.guest.login_enabled
    authentication-methods.passkey.login_enabled
    authentication-methods.passkey.signup_enabled
    authentication-methods.passkey.reauth_enabled
    authentication-methods.passkey.account_link_enabled
    authentication-methods.email_otp.login_enabled
    authentication-methods.email_otp.signup_enabled
    authentication-methods.email_otp.reauth_enabled
    authentication-methods.email_otp.account_link_enabled
    authentication-methods.totp.login_enabled
    authentication-methods.totp.signup_enabled
    authentication-methods.totp.reauth_enabled
    authentication-methods.totp.account_link_enabled
    authentication-methods.human_verification.login_enabled
    authentication-methods.human_verification.signup_enabled
    authentication-methods.human_verification.reauth_enabled
    authentication-methods.directory_password.enabled
    authentication-methods.directory_password.auto_provision
  `,
    ],
    [
      'authentication-methods',
      'duration',
      'value',
      `
    authentication-methods.cache_ttl
  `,
    ],
    [
      'authentication-methods',
      'string',
      'structured',
      `
    authentication-methods.external_providers
  `,
    ],
    [
      'authentication-methods',
      'string',
      'value',
      `
    authentication-methods.totp.preset
    authentication-methods.totp.default_acr
    authentication-methods.directory_password.label
  `,
    ],
    [
      'authentication-methods',
      'json',
      'structured',
      `
    authentication-methods.totp.requirement_policy
    authentication-methods.external_provider_usage
  `,
    ],
    [
      'authentication-methods',
      'string',
      'logical_reference',
      `
    authentication-methods.human_verification.provider
    authentication-methods.directory_password.connector_id
  `,
    ],
    [
      'account-lifecycle',
      'boolean',
      'value',
      `
    account-lifecycle.guest.deletion_enabled
    account-lifecycle.guest.upgrade_enabled
  `,
    ],
    [
      'account-lifecycle',
      'number',
      'value',
      `
    account-lifecycle.guest.deletion_after_days
    account-lifecycle.guest.upgrade_hold_minutes
  `,
    ],
    [
      'diagnostic-logging',
      'boolean',
      'value',
      `
    diagnostic-logging.enabled
    diagnostic-logging.http_request_enabled
    diagnostic-logging.http_response_enabled
    diagnostic-logging.token_validation_enabled
    diagnostic-logging.auth_decision_enabled
    diagnostic-logging.r2_output_enabled
    diagnostic-logging.filter_pii
    diagnostic-logging.filter_tokens
    diagnostic-logging.http_body_schema_aware
    diagnostic-logging.sdk_ingest_enabled
    diagnostic-logging.merged_output_enabled
  `,
    ],
    [
      'diagnostic-logging',
      'enum',
      'value',
      `
    diagnostic-logging.log_level
    diagnostic-logging.output_format
    diagnostic-logging.buffer_strategy
    diagnostic-logging.storage_mode.default
  `,
    ],
    [
      'diagnostic-logging',
      'string',
      'environment_mapping',
      `
    diagnostic-logging.r2_bucket_binding
    diagnostic-logging.r2_path_prefix
  `,
    ],
    [
      'diagnostic-logging',
      'number',
      'value',
      `
    diagnostic-logging.batch_size
    diagnostic-logging.batch_interval_ms
    diagnostic-logging.token_hash_prefix_length
    diagnostic-logging.retention_days
  `,
    ],
    [
      'diagnostic-logging',
      'string',
      'value',
      `
    diagnostic-logging.http_safe_headers
  `,
    ],
    [
      'diagnostic-logging',
      'string',
      'structured',
      `
    diagnostic-logging.storage_mode.by_client
  `,
    ],
    [
      'dr-backup',
      'string',
      'environment_mapping',
      `
    dr-backup.storage_destination_id
  `,
    ],
    [
      'login-entry',
      'boolean',
      'value',
      `
    login-entry.override_enabled
    login-entry.allow_manual_tenant_entry
    login-entry.remember_last_tenant
    login-entry.redirect_default_login_to_discovery
    login-entry.require_common_discovery_before_login
    login-entry.skip_discovery_if_only_one_tenant
    login-entry.redirect_tenant_discover_to_common_entry
  `,
    ],
    [
      'login-entry',
      'enum',
      'value',
      `
    login-entry.mode
    login-entry.email_resolution_policy
    login-entry.selection_policy
    login-entry.post_login_behavior
  `,
    ],
    [
      'login-entry',
      'string',
      'structured',
      `
    login-entry.discovery_methods
  `,
    ],
    [
      'login-entry',
      'string',
      'url_or_asset',
      `
    login-entry.post_login_redirect_url
    login-entry.app_login_redirect_uri
    login-entry.app_login_final_return_to
  `,
    ],
    [
      'login-entry',
      'string',
      'logical_reference',
      `
    login-entry.app_login_client_id
    login-entry.app_login_scope
  `,
    ],
    [
      'tenant-discovery-ui',
      'boolean',
      'value',
      `
    tenant-discovery-ui.override_enabled
    tenant-discovery-ui.inherit_from_login_ui
  `,
    ],
    [
      'tenant-discovery-ui',
      'enum',
      'value',
      `
    tenant-discovery-ui.theme
    tenant-discovery-ui.variant
  `,
    ],
    [
      'tenant-discovery-ui',
      'string',
      'value',
      `
    tenant-discovery-ui.brand_name
    tenant-discovery-ui.page_title
    tenant-discovery-ui.kicker_text
    tenant-discovery-ui.title_text
    tenant-discovery-ui.subtitle_text
  `,
    ],
    [
      'tenant-discovery-ui',
      'string',
      'url_or_asset',
      `
    tenant-discovery-ui.logo_url
  `,
    ],
    [
      'support-ops',
      'boolean',
      'value',
      `
    support_ops.allow_self_approval
  `,
    ],
    [
      'support-ops',
      'enum',
      'value',
      `
    support_ops.duty_separation
  `,
    ],
    [
      'self-service',
      'boolean',
      'value',
      `
    self-service.account_page_enabled
  `,
    ],
    [
      'self-service',
      'string',
      'value',
      `
    self-service.account_page_path
  `,
    ],
    [
      'service-site',
      'boolean',
      'value',
      `
    service-site.fallback_enabled
  `,
    ],
  ];

export const TENANT_SETTING_FIELD_POLICIES: readonly TenantSettingFieldPolicy[] =
  REVIEWED_FIELDS.flatMap(([category, type, handling, keys]) =>
    keys
      .trim()
      .split(/\s+/)
      .map((key) => ({ category, type, handling, key }))
  );

export function checkTenantSettingFieldCoverage(
  actual: readonly { category: string; key: string; type: string }[],
  policies: readonly TenantSettingFieldPolicy[] = TENANT_SETTING_FIELD_POLICIES
): { unclassified: string[]; stale: string[]; duplicates: string[]; changedShape: string[] } {
  const declared = new Map<string, TenantSettingFieldPolicy>();
  const observed = new Set<string>();
  const duplicates = new Set<string>();
  const unclassified = new Set<string>();
  const changedShape = new Set<string>();
  for (const policy of policies) {
    if (declared.has(policy.key)) duplicates.add(policy.key);
    declared.set(policy.key, policy);
  }
  for (const field of actual) {
    if (observed.has(field.key)) duplicates.add(field.key);
    observed.add(field.key);
    const policy = declared.get(field.key);
    if (!policy) unclassified.add(field.key);
    else if (policy.category !== field.category || policy.type !== field.type) {
      changedShape.add(field.key);
    }
  }
  return {
    unclassified: [...unclassified].sort(),
    stale: [...declared.keys()].filter((key) => !observed.has(key)).sort(),
    duplicates: [...duplicates].sort(),
    changedShape: [...changedShape].sort(),
  };
}
