/**
 * UI Environment Variables Tests v2
 *
 * Tests generateUiEnvContent() serialization and integration with generateEnvVars().
 * No circular tests — inputs are independent of expected values.
 */

import { describe, it, expect } from 'vitest';
import { generateUiEnvContent } from '../core/ui-env.js';
import { resolveUiDeploymentSettings } from '../core/ui-deployment.js';
import type { AuthrimConfig } from '../core/config.js';
import {
  SCENARIOS,
  buildAuthrimConfig,
  scenarioLabel,
} from '../../../../test/fixtures/deployment-matrix.js';

// =============================================================================
// Serialization tests
// =============================================================================

describe('generateUiEnvContent - serialization', () => {
  it('includes all provided fields', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
      API_BACKEND_URL: 'https://api.example.com',
      PUBLIC_AUTHRIM_ISSUER: 'https://api.example.com',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).toContain('API_BACKEND_URL=https://api.example.com');
    expect(content).toContain('PUBLIC_AUTHRIM_ISSUER=https://api.example.com');
  });

  it('omits undefined fields', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).not.toContain('API_BACKEND_URL=');
    expect(content).not.toContain('PUBLIC_AUTHRIM_ISSUER=');
  });

  it('omits empty string fields', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
      API_BACKEND_URL: '',
      PUBLIC_AUTHRIM_ISSUER: 'https://api.example.com',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).not.toContain('API_BACKEND_URL=');
    expect(content).toContain('PUBLIC_AUTHRIM_ISSUER=https://api.example.com');
  });

  it('includes header comment', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
    });

    expect(content).toContain('# Auto-generated by @authrim/setup');
  });

  it('quotes values with special characters', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/path with spaces',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL="https://api.example.com/path with spaces"');
  });
});

// =============================================================================
// escapeEnvValue edge cases
// =============================================================================

describe('generateUiEnvContent - escapeEnvValue edge cases', () => {
  it('escapes double quotes in values', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/"test"',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL="https://api.example.com/\\"test\\""');
  });

  it('escapes backslashes in values', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/path\\with\\backslash',
    });

    expect(content).toContain(
      'PUBLIC_API_BASE_URL="https://api.example.com/path\\\\with\\\\backslash"'
    );
  });

  it('quotes values containing hash (#)', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/path#fragment',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL="https://api.example.com/path#fragment"');
  });

  it('does not quote simple URLs', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
    });

    // Should NOT have quotes around a simple URL
    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).not.toContain('PUBLIC_API_BASE_URL="https://api.example.com"');
  });
});

// =============================================================================
// Integration with deployment settings — verify UI env uses API/backend URLs, not UI_URL
// =============================================================================

describe('generateUiEnvContent - integration with deployment settings', () => {
  const scenariosWithLoginUi = SCENARIOS.filter((s) => s.config.hasLoginUi);

  it.each(scenariosWithLoginUi.map((s) => [scenarioLabel(s), s] as const))(
    '%s - UI env content uses correct API base URL from deployment settings',
    (_label, scenario) => {
      const config = buildAuthrimConfig(scenario) as AuthrimConfig;
      const settings = resolveUiDeploymentSettings({
        component: 'ar-login-ui',
        config,
        loginUiClientId: 'login-ui-client',
      });

      // Build UI env content from deployment-generated values (mimics real deployment flow)
      const content = generateUiEnvContent(settings.uiEnv);

      if (settings.uiEnv.PUBLIC_API_BASE_URL) {
        expect(content).toContain(`PUBLIC_API_BASE_URL=${settings.uiEnv.PUBLIC_API_BASE_URL}`);
      } else {
        expect(content).not.toContain('PUBLIC_API_BASE_URL=');
      }
      expect(content).toContain(`PUBLIC_AUTHRIM_ISSUER=${settings.apiBaseUrl}`);
      expect(content).toContain('PUBLIC_LOGIN_UI_CLIENT_ID=login-ui-client');
      if (settings.needsProxy) {
        expect(content).toContain(`API_BACKEND_URL=${settings.apiBaseUrl}`);
      }
    }
  );
});
