/**
 * UI Environment Variables Tests v2
 *
 * Tests generateUiEnvContent() serialization and integration with generateEnvVars().
 * No circular tests — inputs are independent of expected values.
 */

import { describe, it, expect } from 'vitest';
import { generateUiEnvContent } from '../core/ui-env.js';
import { generateEnvVars } from '../core/wrangler.js';
import type { AuthrimConfig } from '../core/config.js';
import {
  SCENARIOS,
  buildAuthrimConfig,
  scenarioLabel,
  WORKERS_SUBDOMAIN,
} from '../../../../test/fixtures/deployment-matrix.js';

function isMultiTenantConfigured(config: AuthrimConfig): boolean {
  return config.tenant?.multiTenant === true && !!config.tenant.baseDomain;
}

// =============================================================================
// Serialization tests
// =============================================================================

describe('generateUiEnvContent - serialization', () => {
  it('includes all provided fields', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
      API_BACKEND_URL: 'https://api.example.com',
      PUBLIC_AUTHRIM_ISSUER: 'https://api.example.com',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).toContain('API_BACKEND_URL=https://api.example.com');
    expect(content).toContain('PUBLIC_AUTHRIM_ISSUER=https://api.example.com');
  });

  it('omits undefined fields', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).not.toContain('API_BACKEND_URL=');
    expect(content).not.toContain('PUBLIC_AUTHRIM_ISSUER=');
  });

  it('omits empty string fields', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
      API_BACKEND_URL: '',
      PUBLIC_AUTHRIM_ISSUER: 'https://api.example.com',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).not.toContain('API_BACKEND_URL=');
    expect(content).toContain('PUBLIC_AUTHRIM_ISSUER=https://api.example.com');
  });

  it('includes header comment', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
    });

    expect(content).toContain('# Auto-generated by @authrim/setup');
  });

  it('quotes values with special characters', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/path with spaces',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL="https://api.example.com/path with spaces"');
  });
});

// =============================================================================
// escapeEnvValue edge cases
// =============================================================================

describe('generateUiEnvContent - escapeEnvValue edge cases', () => {
  it('escapes double quotes in values', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/"test"',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL="https://api.example.com/\\"test\\""');
  });

  it('escapes backslashes in values', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/path\\with\\backslash',
    });

    expect(content).toContain(
      'PUBLIC_API_BASE_URL="https://api.example.com/path\\\\with\\\\backslash"'
    );
  });

  it('quotes values containing hash (#)', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com/path#fragment',
    });

    expect(content).toContain('PUBLIC_API_BASE_URL="https://api.example.com/path#fragment"');
  });

  it('does not quote simple URLs', () => {
    const content = generateUiEnvContent({
      PUBLIC_API_BASE_URL: 'https://api.example.com',
    });

    // Should NOT have quotes around a simple URL
    expect(content).toContain('PUBLIC_API_BASE_URL=https://api.example.com');
    expect(content).not.toContain('PUBLIC_API_BASE_URL="https://api.example.com"');
  });
});

// =============================================================================
// Integration with generateEnvVars — verify UI env uses correct wrangler values
// =============================================================================

describe('generateUiEnvContent - integration with generateEnvVars', () => {
  const scenariosWithLoginUi = SCENARIOS.filter((s) => s.config.hasLoginUi);

  it.each(scenariosWithLoginUi.map((s) => [scenarioLabel(s), s] as const))(
    '%s - UI env content uses correct API base URL from wrangler',
    (_label, scenario) => {
      const config = buildAuthrimConfig(scenario) as AuthrimConfig;
      const vars = generateEnvVars('ar-auth', config, WORKERS_SUBDOMAIN);
      const effectiveApiUrl = config.urls?.api?.custom || config.urls?.api?.auto;
      const expectedUiUrl = isMultiTenantConfigured(config)
        ? effectiveApiUrl
        : scenario.expected.arAuthEnvVars.UI_URL;

      // Build UI env content from wrangler-generated values (mimics real deployment flow)
      const content = generateUiEnvContent({
        PUBLIC_API_BASE_URL: vars['UI_URL'],
        PUBLIC_AUTHRIM_ISSUER: vars['ISSUER_URL'],
      });

      // Verify UI_URL matches scenario expectation
      expect(vars['UI_URL']).toBe(expectedUiUrl);

      // Verify serialized content contains the expected values
      expect(content).toContain(`PUBLIC_API_BASE_URL=${expectedUiUrl}`);
      expect(content).toContain(
        `PUBLIC_AUTHRIM_ISSUER=${scenario.expected.arAuthEnvVars.ISSUER_URL}`
      );
    }
  );
});
