import { describe, expect, it } from 'vitest';
import { generateUiWorkersWranglerConfig } from '../core/wrangler.js';

describe('generateUiWorkersWranglerConfig', () => {
  describe('without Service Binding (needsProxy=false)', () => {
    it('generates correct toml for ar-login-ui', () => {
      const result = generateUiWorkersWranglerConfig({
        component: 'ar-login-ui',
        env: 'test',
        needsProxy: false,
      });

      expect(result).toContain('name = "test-ar-login-ui"');
      expect(result).toContain('workers_dev = true');
      expect(result).toContain('compatibility_date = "2024-01-01"');
      expect(result).toContain('nodejs_compat');
      expect(result).toContain('global_fetch_strictly_public');
      expect(result).toContain('main = ".svelte-kit/cloudflare/_worker.js"');
      expect(result).toContain('[assets]');
      expect(result).toContain('directory = ".svelte-kit/cloudflare"');
      expect(result).toContain('binding = "ASSETS"');
      expect(result).toContain('run_worker_first = ["/account", "/account/*"]');
      expect(result).not.toContain('[[services]]');
      expect(result).not.toContain('AR_ROUTER');
    });

    it('generates correct toml for ar-admin-ui', () => {
      const result = generateUiWorkersWranglerConfig({
        component: 'ar-admin-ui',
        env: 'prod',
        needsProxy: false,
      });

      expect(result).toContain('name = "prod-ar-admin-ui"');
      expect(result).toContain('workers_dev = true');
      expect(result).toContain('main = ".svelte-kit/cloudflare/_worker.js"');
      expect(result).not.toContain('run_worker_first');
      expect(result).not.toContain('[[services]]');
    });
  });

  describe('with Service Binding (needsProxy=true)', () => {
    it('generates [[services]] section for ar-login-ui', () => {
      const result = generateUiWorkersWranglerConfig({
        component: 'ar-login-ui',
        env: 'test',
        needsProxy: true,
      });

      expect(result).toContain('name = "test-ar-login-ui"');
      expect(result).toContain('[[services]]');
      expect(result).toContain('binding = "AR_ROUTER"');
      expect(result).toContain('service = "test-ar-router"');
    });

    it('generates [[services]] section for ar-admin-ui', () => {
      const result = generateUiWorkersWranglerConfig({
        component: 'ar-admin-ui',
        env: 'test',
        needsProxy: true,
      });

      expect(result).toContain('name = "test-ar-admin-ui"');
      expect(result).toContain('[[services]]');
      expect(result).toContain('binding = "AR_ROUTER"');
      expect(result).toContain('service = "test-ar-router"');
    });

    it('uses env-prefixed worker name in service binding', () => {
      const result = generateUiWorkersWranglerConfig({
        component: 'ar-login-ui',
        env: 'prod',
        needsProxy: true,
      });

      expect(result).toContain('service = "prod-ar-router"');
      expect(result).not.toContain('service = "test-ar-router"');
    });
  });

  it('ends with a newline', () => {
    const result = generateUiWorkersWranglerConfig({
      component: 'ar-login-ui',
      env: 'test',
      needsProxy: false,
    });

    expect(result.endsWith('\n')).toBe(true);
  });

  it('includes auto-generated comment', () => {
    const result = generateUiWorkersWranglerConfig({
      component: 'ar-login-ui',
      env: 'test',
      needsProxy: false,
    });

    expect(result).toContain('Auto-generated by @authrim/setup');
  });

  it('includes runtime vars when provided', () => {
    const result = generateUiWorkersWranglerConfig({
      component: 'ar-login-ui',
      env: 'test',
      needsProxy: false,
      vars: {
        API_BACKEND_URL: '__DISABLED__',
        PUBLIC_AUTHRIM_ISSUER: 'https://issuer.example.com',
      },
    });

    expect(result).toContain('[vars]');
    expect(result).toContain('API_BACKEND_URL = "__DISABLED__"');
    expect(result).toContain('PUBLIC_AUTHRIM_ISSUER = "https://issuer.example.com"');
  });

  it('quotes the Email Verification Origin Trial token map as one Worker var', () => {
    const tokenMap = JSON.stringify({
      'https://login.example.com': 'A'.repeat(64),
    });
    const result = generateUiWorkersWranglerConfig({
      component: 'ar-login-ui',
      env: 'test',
      needsProxy: false,
      vars: {
        EMAIL_VERIFICATION_ORIGIN_TRIAL_TOKENS: tokenMap,
      },
    });

    expect(result).toContain(
      `EMAIL_VERIFICATION_ORIGIN_TRIAL_TOKENS = ${JSON.stringify(tokenMap)}`
    );
  });

  it('disables workers.dev and binds a custom domain when UI custom domain routes are provided', () => {
    const result = generateUiWorkersWranglerConfig({
      component: 'ar-admin-ui',
      env: 'phase9',
      needsProxy: true,
      workersDev: false,
      routes: [{ pattern: 'admin.multi-tenant.authrim.com', custom_domain: true }],
    });

    expect(result).toContain('workers_dev = false');
    expect(result).toContain('[[routes]]');
    expect(result).toContain('pattern = "admin.multi-tenant.authrim.com"');
    expect(result).toContain('custom_domain = true');
    expect(result).toContain('binding = "AR_ROUTER"');
  });
});
