import { describe, expect, it } from 'vitest';
import { generatePagesWranglerConfig } from '../core/wrangler.js';

describe('generatePagesWranglerConfig', () => {
  describe('without Service Binding (needsProxy=false)', () => {
    it('generates correct toml for ar-login-ui', () => {
      const result = generatePagesWranglerConfig({
        component: 'ar-login-ui',
        env: 'test',
        needsProxy: false,
      });

      expect(result).toContain('name = "test-ar-login-ui"');
      expect(result).toContain('compatibility_date = "2024-01-01"');
      expect(result).toContain('nodejs_compat');
      expect(result).toContain('global_fetch_strictly_public');
      expect(result).toContain('pages_build_output_dir = ".svelte-kit/cloudflare"');
      expect(result).not.toContain('[[services]]');
      expect(result).not.toContain('AR_ROUTER');
    });

    it('generates correct toml for ar-admin-ui', () => {
      const result = generatePagesWranglerConfig({
        component: 'ar-admin-ui',
        env: 'prod',
        needsProxy: false,
      });

      expect(result).toContain('name = "prod-ar-admin-ui"');
      expect(result).toContain('pages_build_output_dir = ".svelte-kit/cloudflare"');
      expect(result).not.toContain('[[services]]');
    });
  });

  describe('with Service Binding (needsProxy=true)', () => {
    it('generates [[services]] section for ar-login-ui', () => {
      const result = generatePagesWranglerConfig({
        component: 'ar-login-ui',
        env: 'test',
        needsProxy: true,
      });

      expect(result).toContain('name = "test-ar-login-ui"');
      expect(result).toContain('[[services]]');
      expect(result).toContain('binding = "AR_ROUTER"');
      expect(result).toContain('service = "test-ar-router"');
    });

    it('generates [[services]] section for ar-admin-ui', () => {
      const result = generatePagesWranglerConfig({
        component: 'ar-admin-ui',
        env: 'test',
        needsProxy: true,
      });

      expect(result).toContain('name = "test-ar-admin-ui"');
      expect(result).toContain('[[services]]');
      expect(result).toContain('binding = "AR_ROUTER"');
      expect(result).toContain('service = "test-ar-router"');
    });

    it('uses env-prefixed worker name in service binding', () => {
      const result = generatePagesWranglerConfig({
        component: 'ar-login-ui',
        env: 'prod',
        needsProxy: true,
      });

      expect(result).toContain('service = "prod-ar-router"');
      expect(result).not.toContain('service = "test-ar-router"');
    });
  });

  it('ends with a newline', () => {
    const result = generatePagesWranglerConfig({
      component: 'ar-login-ui',
      env: 'test',
      needsProxy: false,
    });

    expect(result.endsWith('\n')).toBe(true);
  });

  it('includes auto-generated comment', () => {
    const result = generatePagesWranglerConfig({
      component: 'ar-login-ui',
      env: 'test',
      needsProxy: false,
    });

    expect(result).toContain('Auto-generated by @authrim/setup');
  });
});
