import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

function readRoute(relativePath: string): string {
	const path = fileURLToPath(new URL(`../../../routes/${relativePath}`, import.meta.url));
	return readFileSync(path, 'utf8');
}

function readApi(relativePath: string): string {
	const path = fileURLToPath(new URL(`../../api/${relativePath}`, import.meta.url));
	return readFileSync(path, 'utf8');
}

function readComponent(relativePath: string): string {
	const path = fileURLToPath(new URL(`../../components/${relativePath}`, import.meta.url));
	return readFileSync(path, 'utf8');
}

describe('field mapping Admin UI smoke checks', () => {
	it('keeps the field mapping routes in the left navigation instead of bottom cards', () => {
		const layout = readRoute('admin/+layout.svelte');
		const page = readRoute('admin/field-mapping/+page.svelte');

		expect(layout).toContain('/admin/field-mapping');
		expect(layout).toContain('admin_nav_source_destination');
		expect(layout).toContain('admin_nav_mapping_policies');
		expect(layout).toContain('admin_nav_resolution_center');
		expect(layout).toContain('/admin/field-mapping/profiles');
		expect(layout).toContain('/admin/field-mapping/field-mapping-sets');
		expect(layout).toContain('/admin/field-mapping/resolution-center');
		expect(layout).toContain('/admin/field-mapping/edit');
		expect(layout).toContain("activePaths: ['/admin/field-mapping/edit']");
		expect(layout).not.toContain('Mapping Rules');
		expect(layout).not.toContain('/admin/field-mapping/operations');
		expect(layout).not.toContain('/admin/field-mapping/overview');
		expect(layout).not.toContain('/admin/field-mapping/federation-trust');
		expect(layout).not.toContain('/admin/field-mapping/schema-readiness');
		expect(layout).not.toContain('/admin/field-mapping/profiles#destination-consent');
		expect(page).toContain("editorAllowedViewModes={['overview']}");
		expect(page).toContain('editorEditable={false}');
		expect(page).toContain('showEditorInspector={false}');
		expect(page).toContain('showControlPlaneStatus={false}');
		expect(page).not.toContain('operations-grid');
		expect(page).not.toContain('operation-card');
	});

	it('keeps the flow editor graph interaction affordances present', () => {
		const flowEditor = readComponent('identity-mapping/IdentityMappingFlowEditor.svelte');
		const flowData = readComponent('identity-mapping/flow-data.ts');
		const pageShell = readComponent('identity-mapping/IdentityMappingPageShell.svelte');
		const page = readRoute('admin/field-mapping/+page.svelte');
		const editPage = readRoute('admin/field-mapping/edit/+page.svelte');
		const overviewPage = readRoute('admin/field-mapping/overview/+page.svelte');

		expect(flowEditor).toContain('startConnectionDrag');
		expect(flowEditor).toContain('startEasyConnectionDrag');
		expect(flowEditor).toContain('pendingConnectionStart');
		expect(flowEditor).toContain('handleEasyConnectionPointerMove');
		expect(flowEditor).toContain('drag-edge');
		expect(flowEditor).toContain('edge-hit');
		expect(flowEditor).toContain('.edge-hit:focus-visible');
		expect(flowEditor).toContain('edge-delete-control');
		expect(flowEditor).toContain('edge-reconnect-control');
		expect(flowEditor).toContain('edge-insert-control');
		expect(flowEditor).toContain('addTransformNode');
		expect(flowEditor).toContain('startReconnectDrag');
		expect(flowEditor).toContain('reconnectEdge');
		expect(flowEditor).toContain('canInsertTransformNode');
		expect(flowEditor).toContain('edgeDeletePoint');
		expect(flowEditor).toContain('edgeInsertPoint');
		expect(flowEditor).toContain('deleteTransformNode');
		expect(flowEditor).toContain('transform-delete-control');
		expect(flowEditor).toContain('transformOperationSchemas');
		expect(flowEditor).toContain('updateTransformOperation');
		expect(flowEditor).toContain('updateTransformParameter');
		expect(flowEditor).toContain('buildDraftPayload');
		expect(flowEditor).toContain('buildPolicyGraph');
		expect(flowEditor).toContain('selectedPolicyRules');
		expect(flowEditor).toContain('shouldGroupPolicyTransformInputs');
		expect(flowEditor).toContain('policyTransformNode');
		expect(flowEditor).toContain('policy-transform');
		expect(flowEditor).toContain('transformSide');
		expect(flowEditor).toContain('submitDraftForCompile');
		expect(flowEditor).toContain('onCompileDraft');
		expect(flowEditor).toContain('transform_input');
		expect(flowEditor).toContain('admin_identity_mapping_flow_transform_step');
		expect(flowEditor).toContain('admin_identity_mapping_flow_operation');
		expect(flowEditor).toContain('copy');
		expect(flowEditor).toContain('concat');
		expect(flowEditor).toContain('fallback');
		expect(flowEditor).toContain('normalize');
		expect(flowEditor).toContain('case');
		expect(flowEditor).toContain('trim');
		expect(flowEditor).toContain('text_to_boolean');
		expect(flowEditor).toContain('json_build');
		expect(flowEditor).toContain('json_extract_text');
		expect(flowEditor).toContain('json_extract_boolean');
		expect(flowEditor).toContain('json_extract_integer');
		expect(flowEditor).toContain("toType === 'boolean'");
		expect(flowEditor).toContain("toType === 'json'");
		expect(flowEditor).toContain('isValidConnectionForReconnect');
		expect(flowEditor).toContain('isTypeCompatible');
		expect(flowEditor).toContain('isConnectionTypeMismatch');
		expect(flowEditor).toContain('isConnectionCardinalityMismatch');
		expect(flowEditor).toContain('isTypeCompatibleWithTransformInput');
		expect(flowEditor).toContain('isTransformOutputCompatible');
		expect(flowEditor).toContain('transformOutputType');
		expect(flowEditor).toContain('edge-invalid');
		expect(flowEditor).toContain('isTargetInputFull');
		expect(flowEditor).toContain("fromNode.role !== 'source' && fromNode.role !== 'transform'");
		expect(flowEditor).toContain("edgeFromRole === 'source' || edgeFromRole === 'transform'");
		expect(flowEditor).toContain(
			'!isTargetInputFull(fromNode, toNode, ignoredEdgeIds, extraEdges)'
		);
		expect(flowEditor).toContain('targetInputCardinality');
		expect(flowEditor).toContain('locked-node');
		expect(flowEditor).toContain('node-lock-icon');
		expect(flowEditor).toContain('fromNode.locked || toNode.locked');
		expect(flowEditor).toContain('normalizeNodeType');
		expect(flowEditor).toContain('drag-reject-marker');
		expect(flowEditor).toContain('drag-edge-invalid');
		expect(flowEditor).toContain('function nodeFieldRef(');
		expect(flowEditor).toContain("side: 'source' | 'destination'");
		expect(flowEditor).toContain('namespace: fieldRef.namespace');
		expect(flowEditor).toContain('path: fieldRef.path');
		expect(flowEditor).toContain('catalogEntryId: fieldRef.catalogEntryId');
		expect(flowEditor).toContain("sourceRef: nodeFieldRef(fromNode, 'source')");
		expect(flowEditor).toContain("targetRef: nodeFieldRef(toNode, 'destination')");
		expect(flowData).toContain("namespace: 'authrim.profile'");
		expect(flowData).toContain('namespaceForProfile(profile.adapter)');
		expect(flowData).toContain("return 'oidc.claim'");
		expect(flowData).toContain("return 'saml.attribute'");
		expect(flowEditor).toContain('connection-rejected');
		expect(flowEditor).toContain('selectEdge');
		expect(flowEditor).toContain('clearSelection');
		expect(flowEditor).toContain('edge-blank-hit');
		expect(flowEditor).toContain('handleClearSelectionKeyDown');
		expect(flowEditor).toContain('deleteSelectedEdge');
		expect(flowEditor).toContain('handleGlobalKeyDown');
		expect(flowEditor).toContain('beforeNavigate');
		expect(flowEditor).toContain('beforeunload');
		expect(flowEditor).toContain('hasUnsavedDraftChanges');
		expect(flowEditor).toContain('--map-edge-flow-speed');
		expect(flowEditor).toContain('--map-drag-edge-flow-speed');
		expect(flowEditor).toContain('edge-selected');
		expect(flowEditor).toContain('adapter-hidden');
		expect(flowEditor).toContain('nodeVisualOffset');
		expect(flowEditor).toContain('animateNextSampleSourceNodes = true');
		expect(flowEditor).toContain('animateVisibleNodeSwap');
		expect(flowEditor).toContain('if (option.id === selectedSourcePolicyId) continue');
		expect(flowEditor).toContain('swappingNodeIds');
		expect(flowEditor).toContain('node-swap-enter');
		expect(flowEditor).toContain('node-handle output');
		expect(flowEditor).toContain('node-handle input');
		expect(flowEditor).toContain('--node-glow');
		expect(flowEditor).toContain('cardinality-one');
		expect(flowEditor).toContain('cardinality-many');
		expect(flowEditor).toContain('target-group-header');
		expect(flowEditor).toContain('toggleTargetGroup');
		expect(flowEditor).toContain('targetGroupPosition');
		expect(flowEditor).toContain('transform-node');
		expect(flowEditor).toContain('admin_identity_mapping_flow_consent_status');
		expect(flowEditor).toContain('admin_identity_mapping_flow_challenge_mode');
		expect(flowEditor).toContain('admin_identity_mapping_flow_release_policy');
		expect(flowEditor).toContain('admin_identity_mapping_flow_privacy_policy');
		expect(flowEditor).toContain('admin_identity_mapping_flow_identity_schema');
		expect(flowEditor).toContain('admin_identity_mapping_flow_schema_field');
		expect(flowEditor).toContain('admin_identity_mapping_flow_overview');
		expect(flowEditor).toContain('admin_identity_mapping_flow_source_mapping');
		expect(flowEditor).toContain('admin_identity_mapping_flow_destination_release');
		expect(flowEditor).toContain('allowedViewModes');
		expect(flowEditor).toContain('initialViewMode');
		expect(flowEditor).toContain('editable');
		expect(flowEditor).toContain('showMetrics');
		expect(flowEditor).toContain('showInspector');
		expect(flowEditor).toContain("showInspector ? '' : 'no-inspector'");
		expect(flowEditor).toContain('showToolbarSourceProfile');
		expect(flowEditor).toContain('selectedProfileId');
		expect(flowEditor).toContain('admin_identity_mapping_source_profile');
		expect(flowEditor).toContain('admin_identity_mapping_destination_profile');
		expect(flowEditor).toContain('view-source');
		expect(flowEditor).toContain('view-destination');
		expect(flowEditor).toContain("role === 'source' && toNode.role === 'target'");
		expect(flowEditor).toContain("role === 'target' && toNode.role === 'destination'");
		expect(flowEditor).toContain('$props');
		expect(flowEditor).not.toContain('mappingSamples');
		expect(flowEditor).not.toContain('SAML Salesforce columns');
		expect(flowEditor).not.toContain('Field Mapping Control Plane');
		expect(flowEditor).not.toContain('Authrim Admin');
		expect(flowEditor).not.toContain('Theme');
		expect(page).toContain('IdentityMappingPageShell');
		expect(pageShell).toContain('buildIdentityMappingFlowSamples');
		expect(pageShell).toContain('compileEditorDraft');
		expect(pageShell).toContain('createFieldMappingVersion');
		expect(pageShell).toContain('compileFieldMappingVersion');
		expect(pageShell).toContain('policyOptionAdapter');
		expect(pageShell).toContain('`[${adapter}] ${policy.displayName || policy.fieldMappingKey}`');
		expect(pageShell).toContain('getSchemaReadiness');
		expect(pageShell).toContain('showControlPlaneStatus && !showProfileModeControl');
		expect(pageShell).toContain('showInspector={showEditorInspector}');
		expect(pageShell).toContain('editorSamples');
		expect(pageShell).toContain('samples={editorSamples}');
		expect(pageShell).toContain('profile-mode-control');
		expect(pageShell).toContain('selectedEditorProfileId');
		expect(pageShell).toContain('routePolicyOptionId');
		expect(pageShell).toContain('initialPolicyOptionId={selectedFieldMappingOptionId}');
		expect(pageShell).toContain('admin_identity_mapping_editor_policy_version');
		expect(pageShell).toContain('toggleSelectedPolicyActivation');
		expect(pageShell).toContain('publishSelectedFieldMappingVersion');
		expect(pageShell).toContain('rollbackSelectedPolicy');
		expect(pageShell).toContain('deactivateFieldMappingVersion');
		expect(flowEditor).toContain('initialPolicyOptionId');
		expect(flowEditor).toContain('applySourcePolicySelection');
		expect(flowEditor).toContain('applyDestinationPolicySelection');
		expect(editPage).toContain('pageTitle={$LL.admin_identity_mapping_editor_title()}');
		expect(editPage).toContain('backHref="/admin/field-mapping/field-mapping-sets"');
		expect(editPage).toContain('backLabel={$LL.admin_identity_mapping_back_to_policies()}');
		expect(editPage).toContain("editorAllowedViewModes={['source', 'destination']}");
		expect(editPage).toContain('editorInitialViewMode="source"');
		expect(editPage).toContain('showProfileModeControl');
		expect(editPage).toContain('showEditorMetrics={false}');
		expect(overviewPage).toContain('pageTitle={$LL.admin_identity_mapping_overview_title()}');
		expect(overviewPage).toContain("editorAllowedViewModes={['overview']}");
		expect(overviewPage).toContain('editorEditable={false}');
		expect(overviewPage).toContain('showEditorMetrics={false}');
		expect(page).not.toContain('Tier 2 Operations');
	});

	it('wires operation, profile, resolution, and federation pages to their APIs', () => {
		const api = readApi('admin-identity-mapping.ts');
		const operations = readRoute('admin/field-mapping/field-mapping-sets/+page.svelte');
		const profiles = readRoute('admin/field-mapping/profiles/+page.svelte');
		const profileEditor = readRoute('admin/field-mapping/profiles/edit/+page.svelte');
		const resolution = readRoute('admin/field-mapping/resolution-center/+page.svelte');
		const federation = readRoute('admin/field-mapping/federation-trust/+page.svelte');

		expect(api).toContain('/api/admin/field-mapping/review-tasks');
		expect(api).toContain('/api/admin/field-mapping/federation-trust-sources');
		expect(api).toContain('/metadata-documents');
		expect(api).toContain('/api/admin/field-mapping/protocol-schemas');
		expect(api).toContain('/api/admin/field-mapping/external-schemas');
		expect(api).toContain('/api/admin/field-mapping/source-profiles');
		expect(api).toContain('/api/admin/field-mapping/source-profiles/csv/parse');
		expect(api).toContain('/api/admin/field-mapping/destination-profiles');
		expect(api).toContain('deleteSourceProfile');
		expect(api).toContain('deleteDestinationProfile');
		expect(api).toContain('/api/admin/field-mapping/attribute-groups');
		expect(api).toContain('/api/admin/field-mapping/attribute-fields');
		expect(api).toContain('/api/admin/field-mapping/templates');
		expect(api).toContain('/api/admin/field-mapping/schema-readiness');
		expect(api).toContain('/rollback');
		expect(api).toContain('/publish');
		expect(api).toContain('/compile');
		expect(api).toContain('/activate');
		expect(api).toContain('/deactivate');
		expect(api).toContain('/transition');
		expect(operations).toContain('admin_identity_mapping_policies_title');
		expect(operations).toContain('admin_identity_mapping_policies_source_title');
		expect(operations).toContain('admin_identity_mapping_policies_destination_title');
		expect(operations).toContain('editPolicyHref');
		expect(operations).toContain('newPolicyHref');
		expect(operations).toContain('admin_identity_mapping_policies_create_source');
		expect(operations).toContain('admin_identity_mapping_policies_create_destination');
		expect(operations).toContain('direction');
		expect(operations).not.toContain('Confirm rollback');
		expect(operations).not.toContain('rollbackPolicy');
		expect(operations).not.toContain('runPolicyOperation');
		expect(operations).not.toContain('Publish and activate a policy version');
		expect(operations).not.toContain('Action Panel');
		expect(operations).not.toContain('activePolicyCount');
		expect(operations).not.toContain('draftPolicyCount');
		expect(operations).not.toContain('item.policy.fieldMappingKey');
		expect(profiles).toContain('listSourceProfiles');
		expect(profiles).toContain('listDestinationProfiles');
		expect(profiles).toContain('admin_identity_mapping_profiles_lists_title');
		expect(profiles).toContain('sourceProfileListItems');
		expect(profiles).toContain('destinationProfileListItems');
		expect(profiles).toContain('admin_identity_mapping_profiles_create_source');
		expect(profiles).toContain('admin_identity_mapping_profiles_create_destination');
		expect(profiles).toContain('/admin/field-mapping/profiles/edit?kind=source');
		expect(profiles).toContain('/admin/field-mapping/profiles/edit?kind=destination');
		expect(profiles).toContain('onclick={() => editSourceProfile(profile)}');
		expect(profiles).toContain('onclick={() => editDestinationProfile(profile)}');
		expect(profiles).not.toContain('listProtocolSchemas');
		expect(profiles).not.toContain('listExternalSchemas');
		expect(profiles).not.toContain('listAttributeGroups');
		expect(profiles).not.toContain('listAttributeFields');
		expect(profiles).not.toContain('listTemplates');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_create_source');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_create_destination');
		expect(profileEditor).toContain('listAttributeGroups');
		expect(profileEditor).toContain('listAttributeFields');
		expect(profileEditor).toContain('destinationTemplates');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_create_from_existing');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_create_from_template');
		expect(profileEditor).toContain(
			'admin_identity_mapping_profile_edit_destination_consent_settings'
		);
		expect(profileEditor).toContain(
			'admin_identity_mapping_profile_edit_configure_release_consent'
		);
		expect(profileEditor).toContain('deleteCurrentProfile');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_delete');
		expect(profileEditor).toContain('parseCsvSourceProfile');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_save_draft_profile');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_save_destination_draft');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_manual');
		expect(profileEditor).toContain('Shift_JIS');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_add_saml_attribute');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_save_attribute_group');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_save_attribute_field');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_tenant_default');
		expect(profileEditor).toContain('admin_identity_mapping_profile_edit_destination_override');
		expect(profiles).not.toContain('admin_identity_mapping_profile_edit_save_draft_profile');
		expect(profiles).not.toContain('admin_identity_mapping_profile_edit_save_destination_draft');
		expect(profiles).not.toContain(
			'admin_identity_mapping_profile_edit_destination_consent_settings'
		);
		expect(resolution).toContain('listReviewTasks');
		expect(resolution).toContain("status: 'in_review'");
		expect(resolution).toContain('transitionResolutionItem');
		expect(federation).toContain('listFederationTrustSources');
		expect(federation).toContain('listFederationMetadataDocuments');
		expect(federation).toContain('listAggregatePreviewEntities');
	});

	it('loads schema readiness from the control-plane API instead of hardcoded rows', () => {
		const readiness = readRoute('admin/field-mapping/schema-readiness/+page.svelte');

		expect(readiness).toContain('getSchemaReadiness');
		expect(readiness).toContain('schemaPresent');
		expect(readiness).toContain('gateState');
		expect(readiness).not.toContain('const rows: ReadinessRow[]');
	});

	it('keeps operator naming separate from internal review task storage names', () => {
		const resolution = readRoute('admin/field-mapping/resolution-center/+page.svelte');

		expect(resolution).toContain('admin_identity_mapping_resolution_title');
		expect(resolution).not.toContain('review_tasks');
		expect(resolution).not.toContain('Review Queue');
	});
});
