/**
 * UI Environment Variables Management Module
 *
 * Manages UI-specific environment variables (.authrim/{env}/ui.env)
 * and copies them to package directories during build.
 *
 * Flow:
 * 1. init command generates ui.env with PUBLIC_API_BASE_URL
 * 2. deploy command copies ui.env to package's .env before build
 * 3. Vite reads .env during build
 * 4. deploy command cleans up .env after build
 */

import { writeFile, copyFile, unlink, access, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { constants } from 'node:fs';
import type { AuthrimConfig } from './config.js';
import { ensureHttps } from './url-config.js';

// =============================================================================
// Types
// =============================================================================

export interface UiEnvConfig {
  /** API base URL for UI to connect to (e.g., https://prod-ar-router.workers.dev) */
  PUBLIC_API_BASE_URL: string;
  /**
   * Public fallback backend URL for the Pages proxy.
   * Used when the runtime API_BACKEND_URL secret is missing or stale.
   */
  PUBLIC_API_PROXY_BACKEND_URL?: string;
  /**
   * Backend API URL for server-side proxy (Safari ITP compatibility)
   * Used by SvelteKit hooks.server.ts to proxy /api/* requests
   * If not set, defaults to PUBLIC_API_BASE_URL
   */
  API_BACKEND_URL?: string;
  /**
   * Authrim issuer URL for SDK initialization
   * Used by Login UI to configure the SDK client
   * Typically the same as the API base URL
   */
  PUBLIC_AUTHRIM_ISSUER?: string;
  /**
   * Login UI OAuth client ID
   * Auto-created during deployment via ensureLoginUiClient()
   */
  PUBLIC_LOGIN_UI_CLIENT_ID?: string;
}

// =============================================================================
// Content Generation
// =============================================================================

/**
 * Escape and quote a value for .env file if needed
 * Values containing spaces, #, quotes, or newlines need to be quoted
 */
function escapeEnvValue(value: string): string {
  // Check if quoting is needed
  const needsQuote = /[\s#"'\\]/.test(value) || value.includes('\n');
  if (!needsQuote) {
    return value;
  }
  // Escape backslashes and double quotes, then wrap in double quotes
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

/**
 * Generate ui.env file content from configuration
 */
export function generateUiEnvContent(config: UiEnvConfig): string {
  const lines: string[] = [
    '# Auto-generated by @authrim/setup',
    '# Do not edit manually - regenerate with setup tool',
    '',
  ];

  for (const [key, value] of Object.entries(config)) {
    if (value !== undefined && value !== '') {
      lines.push(`${key}=${escapeEnvValue(value)}`);
    }
  }

  return lines.join('\n') + '\n';
}

/**
 * Build the minimal UI env used before component-specific deploy-time env exists.
 * This keeps CLI init and Web setup bootstrap behavior identical.
 */
export function buildInitialUiEnvConfig(config: AuthrimConfig): UiEnvConfig | null {
  const apiUrl = ensureHttps(config.urls?.api?.custom || config.urls?.api?.auto);
  if (!apiUrl) {
    return null;
  }

  return {
    PUBLIC_API_BASE_URL: apiUrl,
  };
}

// =============================================================================
// File Operations
// =============================================================================

/**
 * Save ui.env to .authrim/{env}/ directory
 *
 * @param envPath - Full path to the ui.env file (e.g., .authrim/prod/ui.env)
 * @param config - UI environment configuration
 */
export async function saveUiEnv(envPath: string, config: UiEnvConfig): Promise<void> {
  // Ensure directory exists
  const dir = dirname(envPath);
  await mkdir(dir, { recursive: true });

  const content = generateUiEnvContent(config);
  await writeFile(envPath, content, 'utf-8');
}

/**
 * Copy ui.env to a package's .env file for Vite build
 *
 * @param uiEnvPath - Source path (.authrim/{env}/ui.env)
 * @param packageDir - Target package directory (e.g., packages/ar-admin-ui)
 */
export async function copyUiEnvToPackage(uiEnvPath: string, packageDir: string): Promise<void> {
  const targetPath = join(packageDir, '.env');
  await copyFile(uiEnvPath, targetPath);
}

/**
 * Remove .env from a package directory (cleanup after build)
 *
 * @param packageDir - Package directory containing .env to remove
 */
export async function cleanupPackageEnv(packageDir: string): Promise<void> {
  const envPath = join(packageDir, '.env');
  try {
    await unlink(envPath);
  } catch (error) {
    // ENOENT (file doesn't exist) is expected and safe to ignore
    // Other errors should be propagated
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

/**
 * Check if ui.env exists for an environment
 *
 * @param uiEnvPath - Path to ui.env file
 * @returns true if file exists
 */
export async function uiEnvExists(uiEnvPath: string): Promise<boolean> {
  try {
    await access(uiEnvPath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
