export interface CustomClaimPresetField {
  field_key: string;
  display_label: string;
  field_type: string;
  is_pii: number;
  is_searchable: number;
  is_exportable: number;
  display_order: number;
  ui_group_key: string;
  ui_group_label: string;
  ui_group_order: number;
  ui_field_order: number;
  examples_json: string;
  scope: 'profile' | 'email' | 'phone' | 'address';
  description: string;
}

export interface CustomClaimPreset {
  id: string;
  label: string;
  description: string;
  fields: CustomClaimPresetField[];
}

const PROFILE_GROUP = {
  ui_group_key: 'profile',
  ui_group_label: 'Profile',
  ui_group_order: 10,
};

const CONTACT_GROUP = {
  ui_group_key: 'contact',
  ui_group_label: 'Contact',
  ui_group_order: 20,
};

const ADDRESS_GROUP = {
  ui_group_key: 'address',
  ui_group_label: 'Address',
  ui_group_order: 30,
};

export const OIDC_STANDARD_CLAIM_FIELDS: CustomClaimPresetField[] = [
  {
    field_key: 'name',
    display_label: 'Full Name',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 1,
    is_exportable: 1,
    display_order: 1,
    ui_field_order: 1,
    examples_json: JSON.stringify({ values: ['John Doe', '山田 太郎'] }),
    scope: 'profile',
    description: 'OIDC profile claim: full display name.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'given_name',
    display_label: 'First Name',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 1,
    is_exportable: 1,
    display_order: 2,
    ui_field_order: 2,
    examples_json: JSON.stringify({ values: ['John', '太郎'] }),
    scope: 'profile',
    description: 'OIDC profile claim: given name.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'family_name',
    display_label: 'Last Name',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 1,
    is_exportable: 1,
    display_order: 3,
    ui_field_order: 3,
    examples_json: JSON.stringify({ values: ['Doe', '山田'] }),
    scope: 'profile',
    description: 'OIDC profile claim: family name.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'middle_name',
    display_label: 'Middle Name',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 4,
    ui_field_order: 4,
    examples_json: JSON.stringify({ values: ['Quincy'] }),
    scope: 'profile',
    description: 'OIDC profile claim: middle name.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'nickname',
    display_label: 'Nickname',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 5,
    ui_field_order: 5,
    examples_json: JSON.stringify({ values: ['jd'] }),
    scope: 'profile',
    description: 'OIDC profile claim: casual display name.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'preferred_username',
    display_label: 'Preferred Username',
    field_type: 'string',
    is_pii: 0,
    is_searchable: 1,
    is_exportable: 1,
    display_order: 6,
    ui_field_order: 6,
    examples_json: JSON.stringify({ values: ['jdoe'] }),
    scope: 'profile',
    description: 'OIDC profile claim: preferred username.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'profile',
    display_label: 'Profile URL',
    field_type: 'string',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 7,
    ui_field_order: 7,
    examples_json: JSON.stringify({ values: ['https://example.com/users/jdoe'] }),
    scope: 'profile',
    description: 'OIDC profile claim: profile page URL.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'picture',
    display_label: 'Picture URL',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 8,
    ui_field_order: 8,
    examples_json: JSON.stringify({ values: ['https://example.com/users/jdoe/photo.jpg'] }),
    scope: 'profile',
    description: 'OIDC profile claim: profile image URL.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'website',
    display_label: 'Website',
    field_type: 'string',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 9,
    ui_field_order: 9,
    examples_json: JSON.stringify({ values: ['https://example.com'] }),
    scope: 'profile',
    description: 'OIDC profile claim: website URL.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'birthdate',
    display_label: 'Birthdate',
    field_type: 'date',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 10,
    ui_field_order: 10,
    examples_json: JSON.stringify({ values: ['1970-01-01'] }),
    scope: 'profile',
    description: 'OIDC profile claim: birthdate.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'zoneinfo',
    display_label: 'Time Zone',
    field_type: 'string',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 11,
    ui_field_order: 11,
    examples_json: JSON.stringify({ values: ['Asia/Tokyo'] }),
    scope: 'profile',
    description: 'OIDC profile claim: time zone.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'locale',
    display_label: 'Locale',
    field_type: 'string',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 12,
    ui_field_order: 12,
    examples_json: JSON.stringify({ values: ['ja-JP', 'en-US'] }),
    scope: 'profile',
    description: 'OIDC profile claim: locale.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'updated_at',
    display_label: 'Last Updated',
    field_type: 'number',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 0,
    display_order: 13,
    ui_field_order: 13,
    examples_json: JSON.stringify({ values: [1772323200] }),
    scope: 'profile',
    description: 'OIDC profile claim: last update epoch seconds.',
    ...PROFILE_GROUP,
  },
  {
    field_key: 'email',
    display_label: 'Email',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 1,
    is_exportable: 1,
    display_order: 20,
    ui_field_order: 1,
    examples_json: JSON.stringify({ values: ['john@example.com'] }),
    scope: 'email',
    description: 'OIDC email claim.',
    ...CONTACT_GROUP,
  },
  {
    field_key: 'email_verified',
    display_label: 'Email Verified',
    field_type: 'boolean',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 0,
    display_order: 21,
    ui_field_order: 2,
    examples_json: JSON.stringify({ values: [true] }),
    scope: 'email',
    description: 'OIDC email verification claim.',
    ...CONTACT_GROUP,
  },
  {
    field_key: 'phone_number',
    display_label: 'Phone Number',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 1,
    is_exportable: 1,
    display_order: 30,
    ui_field_order: 3,
    examples_json: JSON.stringify({ values: ['+1-555-0100', '+81-3-1234-5678'] }),
    scope: 'phone',
    description: 'OIDC phone claim.',
    ...CONTACT_GROUP,
  },
  {
    field_key: 'phone_number_verified',
    display_label: 'Phone Number Verified',
    field_type: 'boolean',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 0,
    display_order: 31,
    ui_field_order: 4,
    examples_json: JSON.stringify({ values: [false] }),
    scope: 'phone',
    description: 'OIDC phone verification claim.',
    ...CONTACT_GROUP,
  },
  {
    field_key: 'address_formatted',
    display_label: 'Address (Formatted)',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 40,
    ui_field_order: 1,
    examples_json: JSON.stringify({ values: ['1-1 Chiyoda, Tokyo, Japan'] }),
    scope: 'address',
    description: 'OIDC address claim: formatted address.',
    ...ADDRESS_GROUP,
  },
  {
    field_key: 'address_street_address',
    display_label: 'Street Address',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 41,
    ui_field_order: 2,
    examples_json: JSON.stringify({ values: ['1-1 Chiyoda'] }),
    scope: 'address',
    description: 'OIDC address claim: street address.',
    ...ADDRESS_GROUP,
  },
  {
    field_key: 'address_locality',
    display_label: 'City / Locality',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 42,
    ui_field_order: 3,
    examples_json: JSON.stringify({ values: ['Tokyo'] }),
    scope: 'address',
    description: 'OIDC address claim: locality.',
    ...ADDRESS_GROUP,
  },
  {
    field_key: 'address_region',
    display_label: 'State / Region',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 43,
    ui_field_order: 4,
    examples_json: JSON.stringify({ values: ['Tokyo'] }),
    scope: 'address',
    description: 'OIDC address claim: region.',
    ...ADDRESS_GROUP,
  },
  {
    field_key: 'address_postal_code',
    display_label: 'Postal Code',
    field_type: 'string',
    is_pii: 1,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 44,
    ui_field_order: 5,
    examples_json: JSON.stringify({ values: ['100-0001'] }),
    scope: 'address',
    description: 'OIDC address claim: postal code.',
    ...ADDRESS_GROUP,
  },
  {
    field_key: 'address_country',
    display_label: 'Country',
    field_type: 'string',
    is_pii: 0,
    is_searchable: 0,
    is_exportable: 1,
    display_order: 45,
    ui_field_order: 6,
    examples_json: JSON.stringify({ values: ['JP', 'US'] }),
    scope: 'address',
    description: 'OIDC address claim: country.',
    ...ADDRESS_GROUP,
  },
];

export const BUILTIN_CANONICAL_SCHEMA_FIELDS: CustomClaimPresetField[] =
  OIDC_STANDARD_CLAIM_FIELDS.filter((field) =>
    ['email', 'email_verified', 'name', 'locale'].includes(field.field_key)
  );

export const CUSTOM_CLAIM_PRESETS: CustomClaimPreset[] = [
  {
    id: 'oidc_standard',
    label: 'OIDC Standard Claims',
    description: 'Standard OIDC profile, email, phone, and address claim fields.',
    fields: OIDC_STANDARD_CLAIM_FIELDS,
  },
];
