-- Migration: 008_add_tenant_id_to_all_tables.sql
-- Description: Add tenant_id column to all tables for future multi-tenant support
-- Author: @authrim
-- Date: 2025-11-28
-- Issue: Multi-tenant readiness

-- =============================================================================
-- Auto-generated by: npx tsx scripts/generate-tenant-migration.ts
-- Generated at: 2025-11-28T04:17:12.834Z
-- Tables detected: 16
-- =============================================================================

-- This migration adds tenant_id to all tables with DEFAULT 'default'.
-- In single-tenant mode, all data uses the 'default' tenant.
-- For future multi-tenant mode, the tenant resolver will set appropriate values.

-- =============================================================================
-- Up Migration (Forward)
-- =============================================================================

-- Add tenant_id column to all tables
ALTER TABLE audit_log ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE branding_settings ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE ciba_requests ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE device_codes ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE identity_providers ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE migration_metadata ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE oauth_client_consents ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE oauth_clients ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE passkeys ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE password_reset_tokens ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE roles ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE scope_mappings ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE sessions ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE user_custom_fields ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE user_roles ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';
ALTER TABLE users ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';

-- Create indexes for frequently queried tables
CREATE INDEX IF NOT EXISTS idx_audit_log_tenant_id ON audit_log(tenant_id);
CREATE INDEX IF NOT EXISTS idx_oauth_clients_tenant_id ON oauth_clients(tenant_id);
CREATE INDEX IF NOT EXISTS idx_passkeys_tenant_id ON passkeys(tenant_id);
CREATE INDEX IF NOT EXISTS idx_roles_tenant_id ON roles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sessions_tenant_id ON sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_tenant_id ON users(tenant_id);

-- Update unique constraints to be tenant-scoped
-- users: Make email unique per tenant
DROP INDEX IF EXISTS idx_users_email;
CREATE UNIQUE INDEX idx_users_tenant_email ON users(tenant_id, email);

-- =============================================================================
-- Down Migration (Rollback) - COMMENTED OUT
-- =============================================================================
-- This section documents how to rollback this migration if needed.
-- WARNING: This will fail if any tenant_id values other than 'default' exist.
--
-- -- Restore original unique constraints
-- DROP INDEX IF EXISTS idx_users_tenant_email;
-- CREATE UNIQUE INDEX idx_users_email ON users(email);
--
-- -- Drop tenant_id indexes
-- DROP INDEX IF EXISTS idx_audit_log_tenant_id;
-- DROP INDEX IF EXISTS idx_oauth_clients_tenant_id;
-- DROP INDEX IF EXISTS idx_passkeys_tenant_id;
-- DROP INDEX IF EXISTS idx_roles_tenant_id;
-- DROP INDEX IF EXISTS idx_sessions_tenant_id;
-- DROP INDEX IF EXISTS idx_users_tenant_id;
--
-- -- Drop tenant_id columns
-- ALTER TABLE audit_log DROP COLUMN tenant_id;
-- ALTER TABLE branding_settings DROP COLUMN tenant_id;
-- ALTER TABLE ciba_requests DROP COLUMN tenant_id;
-- ALTER TABLE device_codes DROP COLUMN tenant_id;
-- ALTER TABLE identity_providers DROP COLUMN tenant_id;
-- ALTER TABLE migration_metadata DROP COLUMN tenant_id;
-- ALTER TABLE oauth_client_consents DROP COLUMN tenant_id;
-- ALTER TABLE oauth_clients DROP COLUMN tenant_id;
-- ALTER TABLE passkeys DROP COLUMN tenant_id;
-- ALTER TABLE password_reset_tokens DROP COLUMN tenant_id;
-- ALTER TABLE roles DROP COLUMN tenant_id;
-- ALTER TABLE scope_mappings DROP COLUMN tenant_id;
-- ALTER TABLE sessions DROP COLUMN tenant_id;
-- ALTER TABLE user_custom_fields DROP COLUMN tenant_id;
-- ALTER TABLE user_roles DROP COLUMN tenant_id;
-- ALTER TABLE users DROP COLUMN tenant_id;
--
-- -- Remove migration record
-- DELETE FROM schema_migrations WHERE version = 8;

-- =============================================================================
-- Migration Complete
-- =============================================================================
-- Version: 008
-- =============================================================================
