-- Tenant database size/account statistics for tenant-d1 capacity warnings.
-- Stats are generated by scheduled/operator jobs and are not on the auth hot path.

CREATE TABLE IF NOT EXISTS tenant_database_stats (
  tenant_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (
    role IN ('tenant_core', 'tenant_pii', 'tenant_audit', 'tenant_custom')
  ),
  generation INTEGER NOT NULL,
  shard_group TEXT NOT NULL DEFAULT 'default',
  shard_index INTEGER NOT NULL DEFAULT 0,
  account_count INTEGER,
  active_user_count INTEGER,
  active_pending_user_count INTEGER,
  d1_file_size_bytes INTEGER,
  d1_file_size_checked_at TEXT,
  d1_file_size_status TEXT NOT NULL DEFAULT 'unknown' CHECK (
    d1_file_size_status IN ('fresh', 'stale', 'unknown', 'unavailable')
  ),
  table_size_estimate_json TEXT,
  row_count_estimate_json TEXT,
  warning_state TEXT NOT NULL DEFAULT 'ok' CHECK (
    warning_state IN ('ok', 'warning', 'strong_warning')
  ),
  warning_reasons_json TEXT,
  stats_checked_at TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, role, generation, shard_group, shard_index)
);

CREATE INDEX IF NOT EXISTS idx_tenant_database_stats_warning
  ON tenant_database_stats(warning_state, role);

CREATE INDEX IF NOT EXISTS idx_tenant_database_stats_checked_at
  ON tenant_database_stats(stats_checked_at);
