-- Phase 2D: distinguish operator-managed Agent Access objects from the immutable
-- snapshots generated by interactive self-service authorization.

ALTER TABLE admin_agent_grants
  ADD COLUMN management_mode TEXT NOT NULL DEFAULT 'managed'
  CHECK (management_mode IN ('managed', 'system_managed'));

ALTER TABLE agent_task_sets
  ADD COLUMN management_mode TEXT NOT NULL DEFAULT 'managed'
  CHECK (management_mode IN ('managed', 'system_managed'));

ALTER TABLE agent_scope_policies
  ADD COLUMN management_mode TEXT NOT NULL DEFAULT 'managed'
  CHECK (management_mode IN ('managed', 'system_managed'));

CREATE INDEX IF NOT EXISTS idx_admin_agent_grants_management_mode
  ON admin_agent_grants(tenant_id, management_mode, status);

CREATE INDEX IF NOT EXISTS idx_agent_task_sets_management_mode
  ON agent_task_sets(tenant_id, management_mode, status);

CREATE INDEX IF NOT EXISTS idx_agent_scope_policies_management_mode
  ON agent_scope_policies(tenant_id, management_mode, status);
