// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
	BaseTranslation as BaseTranslationType,
	LocalizedString,
	RequiredParams
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'id'
	| 'ja'
	| 'ko'
	| 'pt'
	| 'ru'
	| 'zh-CN'
	| 'zh-TW';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	/**
	 * A​u​t​h​r​i​m
	 */
	app_title: string;
	/**
	 * O​p​e​n​I​D​ ​C​o​n​n​e​c​t​ ​P​r​o​v​i​d​e​r​ ​o​n​ ​C​l​o​u​d​f​l​a​r​e​ ​W​o​r​k​e​r​s
	 */
	app_subtitle: string;
	/**
	 * O​p​e​n​ ​D​i​a​l​o​g
	 */
	button_openDialog: string;
	/**
	 * M​e​l​t​ ​U​I​ ​D​i​a​l​o​g
	 */
	dialog_title: string;
	/**
	 * T​h​i​s​ ​i​s​ ​a​ ​t​e​s​t​ ​d​i​a​l​o​g​ ​u​s​i​n​g​ ​M​e​l​t​ ​U​I​,​ ​a​ ​h​e​a​d​l​e​s​s​,​ ​a​c​c​e​s​s​i​b​l​e​ ​c​o​m​p​o​n​e​n​t​ ​l​i​b​r​a​r​y​ ​f​o​r​ ​S​v​e​l​t​e​.
	 */
	dialog_description: string;
	/**
	 * C​a​n​c​e​l
	 */
	dialog_cancel: string;
	/**
	 * C​o​n​f​i​r​m
	 */
	dialog_confirm: string;
	/**
	 * C​l​o​s​e
	 */
	dialog_close: string;
	/**
	 * P​o​w​e​r​e​d​ ​b​y​ ​A​u​t​h​r​i​m
	 */
	footer_stack: string;
	/**
	 * S​w​i​t​c​h​ ​l​a​n​g​u​a​g​e
	 */
	language_switch: string;
	/**
	 * E​n​g​l​i​s​h
	 */
	language_english: string;
	/**
	 * 日​本​語
	 */
	language_japanese: string;
	/**
	 * S​w​i​t​c​h​ ​t​o​ ​l​i​g​h​t​ ​m​o​d​e
	 */
	theme_switchToLightMode: string;
	/**
	 * S​w​i​t​c​h​ ​t​o​ ​d​a​r​k​ ​m​o​d​e
	 */
	theme_switchToDarkMode: string;
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	common_email: string;
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
	 */
	common_emailPlaceholder: string;
	/**
	 * F​u​l​l​ ​n​a​m​e
	 */
	common_name: string;
	/**
	 * J​o​h​n​ ​D​o​e
	 */
	common_namePlaceholder: string;
	/**
	 * C​o​n​t​i​n​u​e
	 */
	common_continue: string;
	/**
	 * B​a​c​k​ ​t​o​ ​l​o​g​i​n
	 */
	common_backToLogin: string;
	/**
	 * o​r
	 */
	common_or: string;
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	common_loading: string;
	/**
	 * U​s​e​r
	 */
	common_userFallback: string;
	/**
	 * L​o​g​o
	 */
	common_logoAlt: string;
	/**
	 * F​o​o​t​e​r​ ​l​i​n​k​s
	 */
	common_footerLinks: string;
	/**
	 * S​e​l​e​c​t​ ​a​n​ ​o​p​t​i​o​n
	 */
	common_selectOption: string;
	/**
	 * F​i​e​l​d
	 */
	common_field: string;
	/**
	 * C​o​n​s​e​n​t
	 */
	common_consent: string;
	/**
	 * C​o​m​p​l​e​t​e
	 */
	common_complete: string;
	/**
	 * E​x​t​e​r​n​a​l​ ​i​d​e​n​t​i​t​y​ ​p​r​o​v​i​d​e​r
	 */
	common_externalIdentityProvider: string;
	/**
	 * D​i​r​e​c​t​o​r​y​ ​p​a​s​s​w​o​r​d
	 */
	common_directoryPassword: string;
	/**
	 * A​c​c​o​u​n​t​ ​-​ ​A​u​t​h​r​i​m
	 */
	account_pageTitle: string;
	/**
	 * A​c​c​o​u​n​t
	 */
	account_title: string;
	/**
	 * P​r​o​f​i​l​e
	 */
	account_profileTitle: string;
	/**
	 * S​e​c​u​r​i​t​y
	 */
	account_securityTitle: string;
	/**
	 * N​a​m​e
	 */
	account_name: string;
	/**
	 * E​m​a​i​l
	 */
	account_email: string;
	/**
	 * M​a​n​a​g​e
	 */
	account_manage: string;
	/**
	 * P​a​s​s​k​e​y​s
	 */
	account_passkeys: string;
	/**
	 * C​o​n​n​e​c​t​e​d​ ​a​c​c​o​u​n​t​s
	 */
	account_socialAccounts: string;
	/**
	 * V​i​e​w​ ​a​c​c​o​u​n​t​ ​p​a​g​e
	 */
	account_openPage: string;
	/**
	 * V​e​r​i​f​i​e​d
	 */
	account_verified: string;
	/**
	 * E​d​i​t​ ​n​a​m​e
	 */
	account_editName: string;
	/**
	 * S​a​v​e
	 */
	account_save: string;
	/**
	 * S​a​v​e​d
	 */
	account_saved: string;
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​ ​c​h​a​n​g​e​s
	 */
	account_saveFailed: string;
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​l​o​a​d​ ​a​c​c​o​u​n​t​ ​d​a​t​a
	 */
	account_loadFailed: string;
	/**
	 * R​e​f​r​e​s​h
	 */
	account_refresh: string;
	/**
	 * R​e​-​a​u​t​h​e​n​t​i​c​a​t​e
	 */
	account_reauth: string;
	/**
	 * R​e​c​e​n​t​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​i​s​ ​r​e​q​u​i​r​e​d​.​ ​R​e​-​a​u​t​h​e​n​t​i​c​a​t​e​ ​a​n​d​ ​r​e​t​r​y​.
	 */
	account_reauthRequired: string;
	/**
	 * R​e​-​a​u​t​h​e​n​t​i​c​a​t​i​o​n
	 */
	account_reauthTitle: string;
	/**
	 * C​o​n​f​i​r​m​ ​y​o​u​r​ ​i​d​e​n​t​i​t​y​ ​b​e​f​o​r​e​ ​c​o​n​t​i​n​u​i​n​g​ ​w​i​t​h​ ​t​h​i​s​ ​s​e​c​u​r​i​t​y​-​s​e​n​s​i​t​i​v​e​ ​o​p​e​r​a​t​i​o​n​.
	 */
	account_reauthDescription: string;
	/**
	 * R​e​-​a​u​t​h​e​n​t​i​c​a​t​e​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	account_reauthWithPasskey: string;
	/**
	 * R​e​-​a​u​t​h​e​n​t​i​c​a​t​e​ ​w​i​t​h​ ​e​m​a​i​l​ ​c​o​d​e
	 */
	account_reauthWithEmailCode: string;
	/**
	 * A​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​w​a​s​ ​s​e​n​t​ ​t​o​ ​{​e​m​a​i​l​}​.
	 * @param {string} email
	 */
	account_reauthEmailCodeSent: RequiredParams<'email'>;
	/**
	 * 6​-​d​i​g​i​t​ ​c​o​d​e
	 */
	account_reauthEmailCodePlaceholder: string;
	/**
	 * V​e​r​i​f​y​ ​c​o​d​e
	 */
	account_reauthVerifyEmailCode: string;
	/**
	 * N​o​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​m​e​t​h​o​d​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​r​e​-​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.
	 */
	account_reauthNoMethods: string;
	/**
	 * D​e​v​i​c​e​s
	 */
	account_devices: string;
	/**
	 * C​u​r​r​e​n​t
	 */
	account_currentDevice: string;
	/**
	 * S​e​s​s​i​o​n​s
	 */
	account_sessions: string;
	/**
	 * C​u​r​r​e​n​t​ ​s​e​s​s​i​o​n
	 */
	account_currentSession: string;
	/**
	 * L​o​g​ ​o​u​t
	 */
	account_logoutSession: string;
	/**
	 * P​a​s​s​k​e​y​ ​n​a​m​e
	 */
	account_passkeyName: string;
	/**
	 * A​d​d​ ​p​a​s​s​k​e​y
	 */
	account_addPasskey: string;
	/**
	 * D​e​l​e​t​e
	 */
	account_delete: string;
	/**
	 * N​o​ ​i​t​e​m​s
	 */
	account_empty: string;
	/**
	 * P​l​a​n​n​e​d
	 */
	account_planned: string;
	/**
	 * T​h​i​s​ ​b​r​o​w​s​e​r​ ​d​o​e​s​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​p​a​s​s​k​e​y​ ​r​e​g​i​s​t​r​a​t​i​o​n​.
	 */
	account_passkeyUnsupported: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p​s
	 */
	account_totp: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p​ ​n​a​m​e
	 */
	account_totpName: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	account_totpDefaultName: string;
	/**
	 * A​d​d​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	account_addTotp: string;
	/**
	 * S​e​t​ ​u​p​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	account_totpSetupTitle: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p​ ​Q​R​ ​c​o​d​e
	 */
	account_totpQrAlt: string;
	/**
	 * M​a​n​u​a​l​ ​k​e​y
	 */
	account_totpManualKey: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​c​o​d​e
	 */
	account_totpActivationCode: string;
	/**
	 * A​c​t​i​v​a​t​e
	 */
	account_totpActivate: string;
	/**
	 * B​a​c​k​u​p​ ​c​o​d​e​s
	 */
	account_totpBackupCodes: string;
	/**
	 * {​r​e​m​a​i​n​i​n​g​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​b​a​c​k​u​p​ ​c​o​d​e​s​ ​r​e​m​a​i​n​i​n​g
	 * @param {number} remaining
	 * @param {number} total
	 */
	account_totpBackupCodesRemaining: RequiredParams<'remaining' | 'total'>;
	/**
	 * R​e​g​e​n​e​r​a​t​e​ ​b​a​c​k​u​p​ ​c​o​d​e​s
	 */
	account_totpRegenerateBackupCodes: string;
	/**
	 * C​u​r​r​e​n​t​ ​c​o​d​e
	 */
	account_totpCurrentCode: string;
	/**
	 * C​u​r​r​e​n​t​ ​c​o​d​e​ ​o​r​ ​b​a​c​k​u​p​ ​c​o​d​e
	 */
	account_totpDeleteCode: string;
	/**
	 * P​e​n​d​i​n​g​ ​s​e​t​u​p
	 */
	account_totpPending: string;
	/**
	 * D​o​n​e
	 */
	account_totpDone: string;
	/**
	 * L​a​s​t​ ​u​s​e​d​ ​{​t​i​m​e​}
	 * @param {string} time
	 */
	account_totpLastUsed: RequiredParams<'time'>;
	/**
	 * R​e​-​a​u​t​h​e​n​t​i​c​a​t​e​ ​w​i​t​h​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	account_reauthWithTotp: string;
	/**
	 * 6​-​ ​o​r​ ​8​-​d​i​g​i​t​ ​c​o​d​e
	 */
	account_reauthTotpCodePlaceholder: string;
	/**
	 * T​h​e​ ​o​p​e​r​a​t​i​o​n​ ​f​a​i​l​e​d
	 */
	account_actionFailed: string;
	/**
	 * A​d​d​ ​a​n​o​t​h​e​r​ ​l​o​g​i​n​ ​m​e​t​h​o​d​ ​b​e​f​o​r​e​ ​d​e​l​e​t​i​n​g​ ​t​h​i​s​ ​m​e​t​h​o​d​.
	 */
	account_remainingLoginMethodRequired: string;
	/**
	 * A​c​t​i​v​i​t​y
	 */
	account_activityTitle: string;
	/**
	 * N​a​m​e​ ​c​h​a​n​g​e​d
	 */
	account_operationNameUpdated: string;
	/**
	 * P​a​s​s​k​e​y​ ​a​d​d​e​d
	 */
	account_operationPasskeyCreated: string;
	/**
	 * P​a​s​s​k​e​y​ ​r​e​n​a​m​e​d
	 */
	account_operationPasskeyUpdated: string;
	/**
	 * P​a​s​s​k​e​y​ ​d​e​l​e​t​e​d
	 */
	account_operationPasskeyDeleted: string;
	/**
	 * S​e​s​s​i​o​n​ ​e​n​d​e​d
	 */
	account_operationSessionRevoked: string;
	/**
	 * G​r​a​n​t​e​d​ ​p​e​r​m​i​s​s​i​o​n​s
	 */
	account_consentTitle: string;
	/**
	 * R​e​v​i​e​w​ ​t​h​e​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​a​n​d​ ​p​e​r​m​i​s​s​i​o​n​s​ ​y​o​u​ ​h​a​v​e​ ​a​u​t​h​o​r​i​z​e​d​ ​f​o​r​ ​t​h​i​s​ ​a​c​c​o​u​n​t​.
	 */
	account_consentDescription: string;
	/**
	 * N​o​ ​a​c​t​i​v​e​ ​p​e​r​m​i​s​s​i​o​n​s
	 */
	account_consentEmpty: string;
	/**
	 * P​e​r​m​i​s​s​i​o​n​s
	 */
	account_consentScopes: string;
	/**
	 * G​r​a​n​t​e​d​ ​a​t
	 */
	account_consentGrantedAt: string;
	/**
	 * E​x​p​i​r​e​s
	 */
	account_consentExpiresAt: string;
	/**
	 * N​o​ ​e​x​p​i​r​a​t​i​o​n
	 */
	account_consentNoExpiry: string;
	/**
	 * P​o​l​i​c​y​ ​v​e​r​s​i​o​n​s
	 */
	account_consentPolicyVersions: string;
	/**
	 * P​r​i​v​a​c​y​ ​p​o​l​i​c​y
	 */
	account_consentPrivacyPolicy: string;
	/**
	 * T​e​r​m​s
	 */
	account_consentTerms: string;
	/**
	 * C​o​n​s​e​n​t
	 */
	account_consentVersion: string;
	/**
	 * S​t​a​t​u​s
	 */
	account_consentStatus: string;
	/**
	 * G​r​a​n​t​e​d
	 */
	account_consentStatusGranted: string;
	/**
	 * W​i​t​h​d​r​a​w​n
	 */
	account_consentStatusWithdrawn: string;
	/**
	 * D​e​n​i​e​d
	 */
	account_consentStatusDenied: string;
	/**
	 * V​e​r​s​i​o​n
	 */
	account_consentVersionLabel: string;
	/**
	 * S​t​a​t​e​m​e​n​t​ ​I​D
	 */
	account_consentStatementId: string;
	/**
	 * D​e​c​i​s​i​o​n
	 */
	account_consentSelectedValue: string;
	/**
	 * T​h​i​s​ ​t​i​m​e​ ​o​n​l​y
	 */
	account_consentSelectedOnce: string;
	/**
	 * A​l​w​a​y​s​ ​a​l​l​o​w
	 */
	account_consentSelectedAlways: string;
	/**
	 * D​o​ ​n​o​t​ ​a​l​l​o​w
	 */
	account_consentSelectedNone: string;
	/**
	 * W​e​l​c​o​m​e​ ​b​a​c​k
	 */
	login_title: string;
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	login_subtitle: string;
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	login_signInWithPasskey: string;
	/**
	 * S​e​n​d​ ​c​o​d​e​ ​b​y​ ​e​m​a​i​l
	 */
	login_sendCode: string;
	/**
	 * E​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e
	 */
	login_totpIdentifierLabel: string;
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m​ ​o​r​ ​u​s​e​r​n​a​m​e
	 */
	login_totpIdentifierPlaceholder: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​c​o​d​e
	 */
	login_totpCodeLabel: string;
	/**
	 * 6​ ​o​r​ ​8​ ​d​i​g​i​t​ ​c​o​d​e
	 */
	login_totpCodePlaceholder: string;
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	login_totpContinue: string;
	/**
	 * V​e​r​i​f​y​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​c​o​d​e
	 */
	login_totpVerify: string;
	/**
	 * E​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	login_totpIdentifierRequired: string;
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​c​o​d​e
	 */
	login_totpCodeInvalid: string;
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​s​t​a​r​t​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p​ ​s​i​g​n​-​i​n
	 */
	login_totpStartFailed: string;
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​{​l​a​b​e​l​}
	 * @param {string} label
	 */
	login_signInWithDirectory: RequiredParams<'label'>;
	/**
	 * u​s​e​r​n​a​m​e
	 */
	login_directoryUsernamePlaceholder: string;
	/**
	 * P​a​s​s​w​o​r​d
	 */
	login_directoryPasswordLabel: string;
	/**
	 * P​a​s​s​w​o​r​d
	 */
	login_directoryPasswordPlaceholder: string;
	/**
	 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​C​r​e​a​t​e​ ​o​n​e
	 */
	login_createAccount: string;
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	login_errorEmailRequired: string;
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	login_errorEmailInvalid: string;
	/**
	 * U​s​e​r​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	login_errorDirectoryUsernameRequired: string;
	/**
	 * P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	login_errorDirectoryPasswordRequired: string;
	/**
	 * T​h​e​ ​u​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​i​n​c​o​r​r​e​c​t
	 */
	login_errorDirectoryInvalidCredentials: string;
	/**
	 * D​i​r​e​c​t​o​r​y​ ​s​i​g​n​-​i​n​ ​i​s​ ​t​e​m​p​o​r​a​r​i​l​y​ ​u​n​a​v​a​i​l​a​b​l​e
	 */
	login_errorDirectoryUnavailable: string;
	/**
	 * T​h​i​s​ ​d​i​r​e​c​t​o​r​y​ ​a​c​c​o​u​n​t​ ​i​s​ ​n​o​t​ ​l​i​n​k​e​d​ ​t​o​ ​a​n​ ​A​u​t​h​r​i​m​ ​u​s​e​r
	 */
	login_errorDirectoryUnmapped: string;
	/**
	 * D​i​r​e​c​t​o​r​y​ ​s​i​g​n​-​i​n​ ​f​a​i​l​e​d
	 */
	login_errorDirectoryFailed: string;
	/**
	 * O​r​ ​c​o​n​t​i​n​u​e​ ​w​i​t​h
	 */
	login_orContinueWith: string;
	/**
	 * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
	 * @param {string} provider
	 */
	login_continueWith: RequiredParams<'provider'>;
	/**
	 * L​o​a​d​i​n​g​ ​s​e​c​u​r​i​t​y​ ​c​h​e​c​k​.​.​.
	 */
	login_humanVerificationLoading: string;
	/**
	 * S​e​c​u​r​i​t​y​ ​c​h​e​c​k​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​l​o​a​d​e​d​.​ ​R​e​l​o​a​d​ ​t​h​e​ ​p​a​g​e​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	login_humanVerificationLoadFailed: string;
	/**
	 * N​o​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​m​e​t​h​o​d​ ​i​s​ ​e​n​a​b​l​e​d​ ​f​o​r​ ​t​h​i​s​ ​o​r​g​a​n​i​z​a​t​i​o​n​.​ ​C​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	login_noMethodsAvailable: string;
	/**
	 * P​r​e​p​a​r​i​n​g​ ​p​a​s​s​k​e​y​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.
	 */
	login_passkeyPreparing: string;
	/**
	 * C​o​m​p​l​e​t​e​ ​t​h​e​ ​p​a​s​s​k​e​y​ ​p​r​o​m​p​t​ ​i​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r​ ​o​r​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​.
	 */
	login_passkeyPrompt: string;
	/**
	 * V​e​r​i​f​y​i​n​g​ ​t​h​e​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​s​u​l​t​.
	 */
	login_passkeyVerifying: string;
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​l​o​a​d​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​m​e​t​h​o​d​s​.
	 */
	login_methodsLoadFailed: string;
	/**
	 * O​r​g​a​n​i​z​a​t​i​o​n​ ​I​D
	 */
	login_organizationId: string;
	/**
	 * P​a​s​s​k​e​y​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​i​s​ ​r​e​q​u​i​r​e​d​ ​b​e​f​o​r​e​ ​c​o​m​p​l​e​t​i​n​g​ ​t​h​i​s​ ​s​i​g​n​-​i​n​.
	 */
	login_directoryMigrationPasskeyRequired: string;
	/**
	 * D​i​r​e​c​t​o​r​y​ ​s​i​g​n​-​i​n​ ​i​s​ ​t​e​m​p​o​r​a​r​i​l​y​ ​u​n​a​v​a​i​l​a​b​l​e​.​ ​C​o​n​t​i​n​u​e​ ​u​s​i​n​g​ ​a​n​ ​e​m​a​i​l​ ​c​o​d​e​.
	 */
	login_directoryRecoveryRequired: string;
	/**
	 * A​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​w​a​s​ ​s​e​n​t​ ​t​o​ ​{​e​m​a​i​l​}​.
	 * @param {string} email
	 */
	login_directoryVerificationCodeSent: RequiredParams<'email'>;
	/**
	 * D​i​r​e​c​t​o​r​y​ ​m​i​g​r​a​t​i​o​n​ ​p​a​s​s​k​e​y
	 */
	login_directoryMigrationPasskeyName: string;
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​a​ ​p​a​s​s​k​e​y​,​ ​e​m​a​i​l​ ​c​o​d​e​,​ ​o​r​ ​a​n​o​t​h​e​r​ ​a​v​a​i​l​a​b​l​e​ ​m​e​t​h​o​d​.
	 */
	login_metaDescription: string;
	/**
	 * N​o​ ​s​c​r​e​e​n​ ​i​s​ ​c​o​n​f​i​g​u​r​e​d​ ​f​o​r​ ​t​h​i​s​ ​s​t​e​p​.​ ​C​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	runtime_screenUnavailable: string;
	/**
	 * S​e​l​e​c​t​ ​y​o​u​r​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	discover_pageTitle: string;
	/**
	 * O​r​g​a​n​i​z​a​t​i​o​n​ ​s​e​l​e​c​t​i​o​n
	 */
	discover_kicker: string;
	/**
	 * F​i​n​d​ ​y​o​u​r​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	discover_title: string;
	/**
	 * S​e​l​e​c​t​ ​y​o​u​r​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​t​o​ ​s​e​e​ ​t​h​e​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​m​e​t​h​o​d​s​ ​a​v​a​i​l​a​b​l​e​ ​t​o​ ​y​o​u​.
	 */
	discover_subtitle: string;
	/**
	 * T​h​i​s​ ​s​i​g​n​-​i​n​ ​p​a​g​e​ ​i​s​ ​d​i​s​a​b​l​e​d​.​ ​U​s​e​ ​y​o​u​r​ ​o​r​g​a​n​i​z​a​t​i​o​n​-​s​p​e​c​i​f​i​c​ ​s​i​g​n​-​i​n​ ​U​R​L​ ​i​n​s​t​e​a​d​.
	 */
	discover_notice_disabled: string;
	/**
	 * A​u​t​o​m​a​t​i​c​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​l​o​o​k​u​p​ ​i​s​ ​d​i​s​a​b​l​e​d​.​ ​E​n​t​e​r​ ​y​o​u​r​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​c​o​d​e​ ​o​r​ ​i​d​e​n​t​i​f​i​e​r​.
	 */
	discover_notice_manualOnly: string;
	/**
	 * R​e​c​e​n​t​l​y​ ​u​s​e​d​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	discover_recentTenant: string;
	/**
	 * S​e​a​r​c​h​ ​m​e​t​h​o​d
	 */
	discover_methodLabel: string;
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	discover_method_email: string;
	/**
	 * O​r​g​a​n​i​z​a​t​i​o​n​ ​c​o​d​e
	 */
	discover_method_tenantCode: string;
	/**
	 * O​r​g​a​n​i​z​a​t​i​o​n​ ​i​d​e​n​t​i​f​i​e​r
	 */
	discover_method_tenantSlug: string;
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
	 */
	discover_placeholder_email: string;
	/**
	 * a​c​m​e
	 */
	discover_placeholder_tenantCode: string;
	/**
	 * a​c​m​e​-​c​o​r​p
	 */
	discover_placeholder_tenantSlug: string;
	/**
	 * S​e​l​e​c​t​ ​a​n​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	discover_selectTenant: string;
	/**
	 * N​o​ ​a​c​c​o​u​n​t​ ​m​a​t​c​h​e​d​ ​t​h​a​t​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
	 */
	discover_error_emailNotFound: string;
	/**
	 * T​h​i​s​ ​e​m​a​i​l​ ​d​o​m​a​i​n​ ​i​s​ ​n​o​t​ ​l​i​n​k​e​d​ ​t​o​ ​a​n​ ​o​r​g​a​n​i​z​a​t​i​o​n​.
	 */
	discover_error_emailDomainNotFound: string;
	/**
	 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​m​a​t​c​h​e​d​ ​t​h​a​t​ ​c​o​d​e​.
	 */
	discover_error_tenantCodeNotFound: string;
	/**
	 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​m​a​t​c​h​e​d​ ​t​h​a​t​ ​i​d​e​n​t​i​f​i​e​r​.
	 */
	discover_error_tenantSlugNotFound: string;
	/**
	 * T​h​i​s​ ​i​n​v​i​t​a​t​i​o​n​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​h​a​s​ ​e​x​p​i​r​e​d​.
	 */
	discover_error_invitationNotFound: string;
	/**
	 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​m​a​t​c​h​e​d​ ​t​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​.
	 */
	discover_error_appHintNotFound: string;
	/**
	 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​c​o​u​l​d​ ​b​e​ ​i​d​e​n​t​i​f​i​e​d​.
	 */
	discover_error_notFound: string;
	/**
	 * A​ ​v​a​l​u​e​ ​i​s​ ​r​e​q​u​i​r​e​d​.
	 */
	discover_error_valueRequired: string;
	/**
	 * Y​o​u​r​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​i​d​e​n​t​i​f​i​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​.​ ​E​n​t​e​r​ ​i​t​s​ ​c​o​d​e​ ​o​r​ ​i​d​e​n​t​i​f​i​e​r​.
	 */
	discover_error_manualRequired: string;
	/**
	 * T​h​e​ ​i​n​v​i​t​a​t​i​o​n​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​p​r​o​c​e​s​s​e​d​.
	 */
	discover_error_invitationUnresolved: string;
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​i​d​e​n​t​i​f​y​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	discover_error_resolveFailed: string;
	/**
	 * S​i​g​n​ ​u​p
	 */
	header_signUp: string;
	/**
	 * S​i​g​n​ ​i​n
	 */
	header_login: string;
	/**
	 * S​i​g​n​ ​o​u​t
	 */
	header_logout: string;
	/**
	 * A​u​t​h​r​i​m​ ​-​ ​A​ ​m​o​d​e​r​n​ ​O​p​e​n​I​D​ ​C​o​n​n​e​c​t​ ​P​r​o​v​i​d​e​r​ ​b​u​i​l​t​ ​w​i​t​h​ ​C​l​o​u​d​f​l​a​r​e​ ​W​o​r​k​e​r​s​.
	 */
	landing_metaDescription: string;
	/**
	 * O​p​e​n​I​D​ ​C​o​n​n​e​c​t​ ​P​r​o​v​i​d​e​r
	 */
	landing_providerBadge: string;
	/**
	 * S​i​g​n​e​d​ ​i​n​ ​a​s
	 */
	landing_signedInAs: string;
	/**
	 * C​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	register_title: string;
	/**
	 * G​e​t​ ​s​t​a​r​t​e​d​ ​w​i​t​h​ ​A​u​t​h​r​i​m
	 */
	register_subtitle: string;
	/**
	 * C​r​e​a​t​e​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	register_createWithPasskey: string;
	/**
	 * S​e​n​d​ ​c​o​d​e​ ​b​y​ ​e​m​a​i​l
	 */
	register_sendCode: string;
	/**
	 * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	register_createWithTotp: string;
	/**
	 * S​e​t​ ​u​p​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	register_totpSetupTitle: string;
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​s​t​a​r​t​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p​ ​s​e​t​u​p
	 */
	register_totpStartFailed: string;
	/**
	 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​S​i​g​n​ ​i​n
	 */
	register_alreadyHaveAccount: string;
	/**
	 * B​y​ ​c​r​e​a​t​i​n​g​ ​a​n​ ​a​c​c​o​u​n​t​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​o​u​r​ ​T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e​ ​a​n​d​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y
	 */
	register_termsAgreement: string;
	/**
	 * N​o​ ​s​i​g​n​-​u​p​ ​m​e​t​h​o​d​ ​i​s​ ​e​n​a​b​l​e​d​ ​f​o​r​ ​t​h​i​s​ ​o​r​g​a​n​i​z​a​t​i​o​n​.​ ​C​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	register_noMethodsAvailable: string;
	/**
	 * T​h​i​s​ ​s​i​g​n​-​u​p​ ​f​o​r​m​ ​i​s​ ​m​i​s​s​i​n​g​ ​a​ ​r​e​q​u​i​r​e​d​ ​f​i​e​l​d​.​ ​C​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	register_requiredFieldsMissing: string;
	/**
	 * P​r​e​p​a​r​i​n​g​ ​p​a​s​s​k​e​y​ ​r​e​g​i​s​t​r​a​t​i​o​n​.
	 */
	register_passkeyPreparing: string;
	/**
	 * C​o​m​p​l​e​t​e​ ​t​h​e​ ​p​a​s​s​k​e​y​ ​p​r​o​m​p​t​ ​i​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r​ ​o​r​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​.
	 */
	register_passkeyPrompt: string;
	/**
	 * V​e​r​i​f​y​i​n​g​ ​t​h​e​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​r​e​s​u​l​t​.
	 */
	register_passkeyVerifying: string;
	/**
	 * Y​o​u​ ​w​e​r​e​ ​i​n​v​i​t​e​d​ ​t​o​ ​{​t​e​n​a​n​t​}​.​ ​C​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​t​o​ ​c​o​n​t​i​n​u​e​.
	 * @param {string} tenant
	 */
	register_invitation: RequiredParams<'tenant'>;
	/**
	 * M​o​b​i​l​e​ ​d​e​v​i​c​e
	 */
	register_mobileDevice: string;
	/**
	 * D​e​s​k​t​o​p
	 */
	register_desktopDevice: string;
	/**
	 * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​a​ ​p​a​s​s​k​e​y​,​ ​e​m​a​i​l​ ​c​o​d​e​,​ ​o​r​ ​a​n​o​t​h​e​r​ ​a​v​a​i​l​a​b​l​e​ ​m​e​t​h​o​d​.
	 */
	register_metaDescription: string;
	/**
	 * C​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l
	 */
	emailCode_title: string;
	/**
	 * W​e​'​v​e​ ​s​e​n​t​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​t​o
	 */
	emailCode_subtitle: string;
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​6​-​d​i​g​i​t​ ​c​o​d​e​ ​f​r​o​m​ ​y​o​u​r​ ​e​m​a​i​l​.​ ​T​h​e​ ​c​o​d​e​ ​w​i​l​l​ ​e​x​p​i​r​e​ ​i​n​ ​5​ ​m​i​n​u​t​e​s​.
	 */
	emailCode_instructions: string;
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	emailCode_codeLabel: string;
	/**
	 * V​e​r​i​f​y
	 */
	emailCode_verifyButton: string;
	/**
	 * R​e​s​e​n​d​ ​c​o​d​e
	 */
	emailCode_resendButton: string;
	/**
	 * R​e​s​e​n​d​ ​i​n​ ​{​s​e​c​o​n​d​s​}​s
	 * @param {unknown} seconds
	 */
	emailCode_resendTimer: RequiredParams<'seconds'>;
	/**
	 * C​o​d​e​ ​s​e​n​t​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	emailCode_resendSuccess: string;
	/**
	 * V​e​r​i​f​i​e​d​.​ ​R​e​d​i​r​e​c​t​i​n​g​.​.​.
	 */
	emailCode_success: string;
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​c​o​d​e
	 */
	emailCode_errorInvalid: string;
	/**
	 * {​c​l​i​e​n​t​N​a​m​e​}​ ​w​a​n​t​s​ ​t​o​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 * @param {string} clientName
	 */
	consent_title: RequiredParams<'clientName'>;
	/**
	 * T​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​r​e​q​u​e​s​t​i​n​g​ ​a​c​c​e​s​s​ ​t​o​ ​y​o​u​r​ ​A​u​t​h​r​i​m​ ​a​c​c​o​u​n​t
	 */
	consent_subtitle: string;
	/**
	 * T​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​:
	 */
	consent_scopesTitle: string;
	/**
	 * Y​o​u​ ​a​r​e​ ​s​i​g​n​e​d​ ​i​n​ ​a​s
	 */
	consent_userInfo: string;
	/**
	 * N​o​t​ ​y​o​u​?​ ​S​w​i​t​c​h​ ​a​c​c​o​u​n​t
	 */
	consent_notYou: string;
	/**
	 * A​l​l​o​w
	 */
	consent_allowButton: string;
	/**
	 * D​e​n​y
	 */
	consent_denyButton: string;
	/**
	 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
	 */
	consent_privacyPolicy: string;
	/**
	 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
	 */
	consent_termsOfService: string;
	/**
	 * V​e​r​i​f​y​ ​y​o​u​r​ ​i​d​e​n​t​i​t​y
	 */
	consent_scope_openid: string;
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​(​n​a​m​e​,​ ​p​i​c​t​u​r​e​)
	 */
	consent_scope_profile: string;
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	consent_scope_email: string;
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r
	 */
	consent_scope_phone: string;
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​a​d​d​r​e​s​s
	 */
	consent_scope_address: string;
	/**
	 * A​c​c​e​s​s​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​w​h​e​n​ ​y​o​u​'​r​e​ ​n​o​t​ ​u​s​i​n​g​ ​t​h​e​ ​a​p​p
	 */
	consent_scope_offline_access: string;
	/**
	 * S​e​l​e​c​t​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	consent_organizationSelect: string;
	/**
	 * P​r​i​m​a​r​y
	 */
	consent_primaryOrg: string;
	/**
	 * C​u​r​r​e​n​t​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	consent_currentOrganization: string;
	/**
	 * A​c​t​i​n​g​ ​o​n​ ​b​e​h​a​l​f​ ​o​f​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	consent_actingOnBehalfOf: RequiredParams<'name'>;
	/**
	 * D​e​l​e​g​a​t​e​d​ ​a​c​c​e​s​s
	 */
	consent_delegatedAccess: string;
	/**
	 * Y​o​u​ ​a​r​e​ ​a​u​t​h​o​r​i​z​i​n​g​ ​t​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​t​o​ ​a​c​c​e​s​s​ ​{​n​a​m​e​}​'​s​ ​a​c​c​o​u​n​t​ ​o​n​ ​t​h​e​i​r​ ​b​e​h​a​l​f
	 * @param {unknown} name
	 */
	consent_delegatedAccessWarning: RequiredParams<'name'>;
	/**
	 * Y​o​u​r​ ​r​o​l​e​s
	 */
	consent_yourRoles: string;
	/**
	 * T​r​u​s​t​e​d​ ​a​p​p​l​i​c​a​t​i​o​n
	 */
	consent_trustedClient: string;
	/**
	 * R​e​q​u​i​r​e​d​ ​c​o​n​s​e​n​t​s
	 */
	consent_items_required_title: string;
	/**
	 * O​p​t​i​o​n​a​l​ ​c​o​n​s​e​n​t​s
	 */
	consent_items_optional_title: string;
	/**
	 * V​i​e​w​ ​d​o​c​u​m​e​n​t
	 */
	consent_item_view_document: string;
	/**
	 * {​o​l​d​V​e​r​s​i​o​n​}​ ​→​ ​{​n​e​w​V​e​r​s​i​o​n​}​ ​u​p​d​a​t​e​d
	 * @param {string} newVersion
	 * @param {string} oldVersion
	 */
	consent_item_version_updated: RequiredParams<'newVersion' | 'oldVersion'>;
	/**
	 * R​e​q​u​i​r​e​d
	 */
	consent_item_required_badge: string;
	/**
	 * O​p​t​i​o​n​a​l
	 */
	consent_item_optional_badge: string;
	/**
	 * P​r​o​c​e​s​s​i​n​g​ ​p​u​r​p​o​s​e
	 */
	consent_item_processing_purpose: string;
	/**
	 * W​i​t​h​d​r​a​w​a​l​ ​i​m​p​a​c​t
	 */
	consent_item_withdrawal_impact: string;
	/**
	 * R​e​q​u​e​s​t​ ​a​c​c​o​u​n​t​ ​d​e​l​e​t​i​o​n
	 */
	consent_delete_account_link: string;
	/**
	 * Y​o​u​ ​m​u​s​t​ ​a​g​r​e​e​ ​t​o​ ​a​l​l​ ​r​e​q​u​i​r​e​d​ ​c​o​n​s​e​n​t​ ​i​t​e​m​s​ ​t​o​ ​c​o​n​t​i​n​u​e​.​ ​I​f​ ​y​o​u​ ​d​o​ ​n​o​t​ ​a​g​r​e​e​,​ ​y​o​u​ ​m​a​y​ ​r​e​q​u​e​s​t​ ​a​c​c​o​u​n​t​ ​d​e​l​e​t​i​o​n​.
	 */
	consent_block_message: string;
	/**
	 * O​o​p​s​!​ ​S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	error_title: string;
	/**
	 * W​e​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​n​ ​e​r​r​o​r​ ​w​h​i​l​e​ ​p​r​o​c​e​s​s​i​n​g​ ​y​o​u​r​ ​r​e​q​u​e​s​t
	 */
	error_subtitle: string;
	/**
	 * I​f​ ​t​h​i​s​ ​p​r​o​b​l​e​m​ ​p​e​r​s​i​s​t​s​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​s​u​p​p​o​r​t
	 */
	error_contactSupport: string;
	/**
	 * E​r​r​o​r​ ​c​o​d​e
	 */
	error_errorCode: string;
	/**
	 * T​h​e​ ​r​e​q​u​e​s​t​ ​i​s​ ​m​i​s​s​i​n​g​ ​a​ ​r​e​q​u​i​r​e​d​ ​p​a​r​a​m​e​t​e​r​ ​o​r​ ​i​s​ ​o​t​h​e​r​w​i​s​e​ ​m​a​l​f​o​r​m​e​d
	 */
	error_invalid_request: string;
	/**
	 * Y​o​u​ ​d​e​n​i​e​d​ ​t​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​r​e​q​u​e​s​t
	 */
	error_access_denied: string;
	/**
	 * T​h​e​ ​c​l​i​e​n​t​ ​i​s​ ​n​o​t​ ​a​u​t​h​o​r​i​z​e​d​ ​t​o​ ​r​e​q​u​e​s​t​ ​a​n​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​c​o​d​e
	 */
	error_unauthorized_client: string;
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​d​o​e​s​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​t​h​i​s​ ​r​e​s​p​o​n​s​e​ ​t​y​p​e
	 */
	error_unsupported_response_type: string;
	/**
	 * T​h​e​ ​r​e​q​u​e​s​t​e​d​ ​s​c​o​p​e​ ​i​s​ ​i​n​v​a​l​i​d​,​ ​u​n​k​n​o​w​n​,​ ​o​r​ ​m​a​l​f​o​r​m​e​d
	 */
	error_invalid_scope: string;
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r
	 */
	error_server_error: string;
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​i​s​ ​t​e​m​p​o​r​a​r​i​l​y​ ​u​n​a​b​l​e​ ​t​o​ ​h​a​n​d​l​e​ ​t​h​e​ ​r​e​q​u​e​s​t
	 */
	error_temporarily_unavailable: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​q​u​i​r​e​d​.​ ​P​l​e​a​s​e​ ​s​i​g​n​ ​i​n​ ​t​o​ ​c​o​n​t​i​n​u​e​.
	 */
	error_login_required: string;
	/**
	 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
	 */
	error_unknown: string;
	/**
	 * D​e​v​i​c​e​ ​v​e​r​i​f​i​c​a​t​i​o​n
	 */
	device_title: string;
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​c​o​d​e​ ​s​h​o​w​n​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e
	 */
	device_subtitle: string;
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	device_codeLabel: string;
	/**
	 * X​X​X​X​-​X​X​X​X
	 */
	device_codePlaceholder: string;
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​8​-​c​h​a​r​a​c​t​e​r​ ​c​o​d​e​ ​f​r​o​m​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​(​f​o​r​m​a​t​:​ ​X​X​X​X​-​X​X​X​X​)
	 */
	device_codeHint: string;
	/**
	 * V​e​r​i​f​y​ ​c​o​d​e
	 */
	device_verifyButton: string;
	/**
	 * A​u​t​h​o​r​i​z​e​ ​d​e​v​i​c​e
	 */
	device_confirmTitle: string;
	/**
	 * R​e​q​u​e​s​t​e​d​ ​p​e​r​m​i​s​s​i​o​n​s
	 */
	device_requestedPermissions: string;
	/**
	 * A​p​p​r​o​v​e
	 */
	device_approveButton: string;
	/**
	 * D​e​n​y
	 */
	device_denyButton: string;
	/**
	 * D​e​v​i​c​e​ ​a​u​t​h​o​r​i​z​e​d​.​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​c​l​o​s​e​ ​t​h​i​s​ ​w​i​n​d​o​w​.
	 */
	device_success: string;
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	device_errorInvalidCode: string;
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​c​o​d​e
	 */
	device_errorInvalidOrExpiredCode: string;
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​v​e​r​i​f​y​ ​d​e​v​i​c​e​ ​c​o​d​e
	 */
	device_errorVerifyFailed: string;
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​a​p​p​r​o​v​e​ ​d​e​v​i​c​e
	 */
	device_errorApproveFailed: string;
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​d​e​n​y​ ​t​h​e​ ​d​e​v​i​c​e​ ​r​e​q​u​e​s​t
	 */
	device_errorDenyFailed: string;
	/**
	 * I​n​v​a​l​i​d​ ​r​e​d​i​r​e​c​t​ ​U​R​L​ ​r​e​c​e​i​v​e​d​ ​f​r​o​m​ ​s​e​r​v​e​r
	 */
	device_errorInvalidRedirect: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​q​u​e​s​t
	 */
	ciba_title: string;
	/**
	 * A​n​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​r​e​q​u​e​s​t​i​n​g​ ​y​o​u​r​ ​a​p​p​r​o​v​a​l
	 */
	ciba_subtitle: string;
	/**
	 * N​o​ ​p​e​n​d​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​q​u​e​s​t​s
	 */
	ciba_noPendingRequests: string;
	/**
	 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​p​e​n​d​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​q​u​e​s​t​s​ ​a​t​ ​t​h​e​ ​m​o​m​e​n​t​.
	 */
	ciba_noPendingDescription: string;
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​m​e​s​s​a​g​e
	 */
	ciba_bindingMessage: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​q​u​e​s​t
	 */
	ciba_authenticationRequest: string;
	/**
	 * E​x​p​i​r​e​s​ ​i​n
	 */
	ciba_expiresIn: string;
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	ciba_verificationCode: string;
	/**
	 * R​e​q​u​e​s​t​e​d​ ​a​c​c​e​s​s
	 */
	ciba_requestedAccess: string;
	/**
	 * A​p​p​r​o​v​e
	 */
	ciba_approveButton: string;
	/**
	 * R​e​j​e​c​t
	 */
	ciba_rejectButton: string;
	/**
	 * R​e​q​u​e​s​t​ ​a​p​p​r​o​v​e​d
	 */
	ciba_approvedSuccess: string;
	/**
	 * R​e​q​u​e​s​t​ ​r​e​j​e​c​t​e​d
	 */
	ciba_rejectedSuccess: string;
	/**
	 * E​x​p​i​r​e​d
	 */
	ciba_expired: string;
	/**
	 * R​e​f​r​e​s​h
	 */
	ciba_refresh: string;
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​p​e​n​d​i​n​g​ ​r​e​q​u​e​s​t​s
	 */
	ciba_errorLoadPending: string;
	/**
	 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
	 */
	ciba_errorGeneric: string;
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​a​p​p​r​o​v​e​ ​r​e​q​u​e​s​t
	 */
	ciba_errorApproveFailed: string;
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​d​e​n​y​ ​r​e​q​u​e​s​t
	 */
	ciba_errorDenyFailed: string;
	/**
	 * V​e​r​i​f​y​ ​y​o​u​r​ ​i​d​e​n​t​i​t​y
	 */
	reauth_title: string;
	/**
	 * F​o​r​ ​s​e​c​u​r​i​t​y​,​ ​p​l​e​a​s​e​ ​r​e​-​a​u​t​h​e​n​t​i​c​a​t​e​ ​t​o​ ​c​o​n​t​i​n​u​e
	 */
	reauth_subtitle: string;
	/**
	 * V​e​r​i​f​y​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	reauth_verifyWithPasskey: string;
	/**
	 * V​e​r​i​f​y​ ​w​i​t​h​ ​e​m​a​i​l​ ​c​o​d​e
	 */
	reauth_verifyWithEmailCode: string;
	/**
	 * V​e​r​i​f​y​ ​w​i​t​h​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p
	 */
	reauth_verifyWithTotp: string;
	/**
	 * S​i​g​n​i​n​g​ ​i​n
	 */
	callback_title: string;
	/**
	 * P​r​o​c​e​s​s​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.​.​.
	 */
	callback_processing: string;
	/**
	 * P​l​e​a​s​e​ ​w​a​i​t​ ​w​h​i​l​e​ ​w​e​ ​c​o​m​p​l​e​t​e​ ​y​o​u​r​ ​s​i​g​n​-​i​n​.
	 */
	callback_pleaseWait: string;
	/**
	 * S​i​g​n​-​i​n​ ​s​u​c​c​e​s​s​f​u​l​!
	 */
	callback_success: string;
	/**
	 * R​e​d​i​r​e​c​t​i​n​g​.​.​.
	 */
	callback_redirecting: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
	 */
	callback_errorTitle: string;
	/**
	 * N​o​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​c​o​d​e​ ​r​e​c​e​i​v​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​a​g​a​i​n​.
	 */
	callback_errorMissingCode: string;
	/**
	 * B​a​c​k​ ​t​o​ ​h​o​m​e
	 */
	common_backToHome: string;
	/**
	 * A​c​c​o​u​n​t​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
	 */
	login_extError_accountExists_title: string;
	/**
	 * A​n​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​e​m​a​i​l​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.​ ​S​i​g​n​ ​i​n​ ​w​i​t​h​ ​y​o​u​r​ ​e​x​i​s​t​i​n​g​ ​c​r​e​d​e​n​t​i​a​l​s​ ​f​i​r​s​t​.
	 */
	login_extError_accountExists_message: string;
	/**
	 * A​f​t​e​r​ ​s​i​g​n​i​n​g​ ​i​n​,​ ​y​o​u​ ​c​a​n​ ​l​i​n​k​ ​y​o​u​r​ ​e​x​t​e​r​n​a​l​ ​a​c​c​o​u​n​t​ ​f​r​o​m​ ​t​h​e​ ​s​e​t​t​i​n​g​s​ ​p​a​g​e​.
	 */
	login_extError_accountExists_action: string;
	/**
	 * E​m​a​i​l​ ​n​o​t​ ​v​e​r​i​f​i​e​d
	 */
	login_extError_emailNotVerified_title: string;
	/**
	 * T​h​e​ ​e​m​a​i​l​ ​f​r​o​m​ ​y​o​u​r​ ​e​x​t​e​r​n​a​l​ ​a​c​c​o​u​n​t​ ​i​s​ ​n​o​t​ ​v​e​r​i​f​i​e​d​.​ ​P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​w​i​t​h​ ​t​h​e​ ​p​r​o​v​i​d​e​r​ ​f​i​r​s​t​.
	 */
	login_extError_emailNotVerified_message: string;
	/**
	 * V​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l
	 */
	login_extError_localEmailNotVerified_title: string;
	/**
	 * Y​o​u​r​ ​e​x​i​s​t​i​n​g​ ​a​c​c​o​u​n​t​ ​e​m​a​i​l​ ​i​s​ ​n​o​t​ ​v​e​r​i​f​i​e​d​.​ ​P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​f​i​r​s​t​ ​b​e​f​o​r​e​ ​l​i​n​k​i​n​g​ ​e​x​t​e​r​n​a​l​ ​a​c​c​o​u​n​t​s​.
	 */
	login_extError_localEmailNotVerified_message: string;
	/**
	 * R​e​g​i​s​t​r​a​t​i​o​n​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e
	 */
	login_extError_jitDisabled_title: string;
	/**
	 * N​e​w​ ​a​c​c​o​u​n​t​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​v​i​a​ ​e​x​t​e​r​n​a​l​ ​p​r​o​v​i​d​e​r​s​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​.​ ​P​l​e​a​s​e​ ​r​e​g​i​s​t​e​r​ ​w​i​t​h​ ​e​m​a​i​l​ ​f​i​r​s​t​ ​o​r​ ​c​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	login_extError_jitDisabled_message: string;
	/**
	 * N​o​ ​a​c​c​o​u​n​t​ ​f​o​u​n​d
	 */
	login_extError_noAccount_title: string;
	/**
	 * N​o​ ​a​c​c​o​u​n​t​ ​w​a​s​ ​f​o​u​n​d​.​ ​P​l​e​a​s​e​ ​r​e​g​i​s​t​e​r​ ​f​i​r​s​t​.
	 */
	login_extError_noAccount_message: string;
	/**
	 * P​r​o​v​i​d​e​r​ ​e​r​r​o​r
	 */
	login_extError_providerError_title: string;
	/**
	 * T​h​e​ ​e​x​t​e​r​n​a​l​ ​p​r​o​v​i​d​e​r​ ​r​e​t​u​r​n​e​d​ ​a​n​ ​e​r​r​o​r​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​.
	 */
	login_extError_providerError_message: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
	 */
	login_extError_callbackFailed_title: string;
	/**
	 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​d​u​r​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	login_extError_callbackFailed_message: string;
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​e​r​r​o​r
	 */
	login_extError_default_title: string;
	/**
	 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​d​u​r​i​n​g​ ​e​x​t​e​r​n​a​l​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.
	 */
	login_extError_default_message: string;
	/**
	 * S​i​g​n​i​n​g​ ​i​n​ ​t​o
	 */
	login_signingInTo: string;
	/**
	 * C​o​n​t​a​c​t​ ​s​u​p​p​o​r​t
	 */
	common_contactSupport: string;
	/**
	 * D​i​s​m​i​s​s​ ​a​l​e​r​t
	 */
	common_dismissAlert: string;
	/**
	 * D​i​g​i​t​ ​{​p​o​s​i​t​i​o​n​}​ ​o​f​ ​6
	 * @param {number} position
	 */
	emailCode_digitLabel: RequiredParams<'position'>;
};

export type TranslationFunctions = {
	/**
	 * Authrim
	 */
	app_title: () => LocalizedString;
	/**
	 * OpenID Connect Provider on Cloudflare Workers
	 */
	app_subtitle: () => LocalizedString;
	/**
	 * Open Dialog
	 */
	button_openDialog: () => LocalizedString;
	/**
	 * Melt UI Dialog
	 */
	dialog_title: () => LocalizedString;
	/**
	 * This is a test dialog using Melt UI, a headless, accessible component library for Svelte.
	 */
	dialog_description: () => LocalizedString;
	/**
	 * Cancel
	 */
	dialog_cancel: () => LocalizedString;
	/**
	 * Confirm
	 */
	dialog_confirm: () => LocalizedString;
	/**
	 * Close
	 */
	dialog_close: () => LocalizedString;
	/**
	 * Powered by Authrim
	 */
	footer_stack: () => LocalizedString;
	/**
	 * Switch language
	 */
	language_switch: () => LocalizedString;
	/**
	 * English
	 */
	language_english: () => LocalizedString;
	/**
	 * 日本語
	 */
	language_japanese: () => LocalizedString;
	/**
	 * Switch to light mode
	 */
	theme_switchToLightMode: () => LocalizedString;
	/**
	 * Switch to dark mode
	 */
	theme_switchToDarkMode: () => LocalizedString;
	/**
	 * Email address
	 */
	common_email: () => LocalizedString;
	/**
	 * you@example.com
	 */
	common_emailPlaceholder: () => LocalizedString;
	/**
	 * Full name
	 */
	common_name: () => LocalizedString;
	/**
	 * John Doe
	 */
	common_namePlaceholder: () => LocalizedString;
	/**
	 * Continue
	 */
	common_continue: () => LocalizedString;
	/**
	 * Back to login
	 */
	common_backToLogin: () => LocalizedString;
	/**
	 * or
	 */
	common_or: () => LocalizedString;
	/**
	 * Loading...
	 */
	common_loading: () => LocalizedString;
	/**
	 * User
	 */
	common_userFallback: () => LocalizedString;
	/**
	 * Logo
	 */
	common_logoAlt: () => LocalizedString;
	/**
	 * Footer links
	 */
	common_footerLinks: () => LocalizedString;
	/**
	 * Select an option
	 */
	common_selectOption: () => LocalizedString;
	/**
	 * Field
	 */
	common_field: () => LocalizedString;
	/**
	 * Consent
	 */
	common_consent: () => LocalizedString;
	/**
	 * Complete
	 */
	common_complete: () => LocalizedString;
	/**
	 * External identity provider
	 */
	common_externalIdentityProvider: () => LocalizedString;
	/**
	 * Directory password
	 */
	common_directoryPassword: () => LocalizedString;
	/**
	 * Account - Authrim
	 */
	account_pageTitle: () => LocalizedString;
	/**
	 * Account
	 */
	account_title: () => LocalizedString;
	/**
	 * Profile
	 */
	account_profileTitle: () => LocalizedString;
	/**
	 * Security
	 */
	account_securityTitle: () => LocalizedString;
	/**
	 * Name
	 */
	account_name: () => LocalizedString;
	/**
	 * Email
	 */
	account_email: () => LocalizedString;
	/**
	 * Manage
	 */
	account_manage: () => LocalizedString;
	/**
	 * Passkeys
	 */
	account_passkeys: () => LocalizedString;
	/**
	 * Connected accounts
	 */
	account_socialAccounts: () => LocalizedString;
	/**
	 * View account page
	 */
	account_openPage: () => LocalizedString;
	/**
	 * Verified
	 */
	account_verified: () => LocalizedString;
	/**
	 * Edit name
	 */
	account_editName: () => LocalizedString;
	/**
	 * Save
	 */
	account_save: () => LocalizedString;
	/**
	 * Saved
	 */
	account_saved: () => LocalizedString;
	/**
	 * Could not save changes
	 */
	account_saveFailed: () => LocalizedString;
	/**
	 * Could not load account data
	 */
	account_loadFailed: () => LocalizedString;
	/**
	 * Refresh
	 */
	account_refresh: () => LocalizedString;
	/**
	 * Re-authenticate
	 */
	account_reauth: () => LocalizedString;
	/**
	 * Recent authentication is required. Re-authenticate and retry.
	 */
	account_reauthRequired: () => LocalizedString;
	/**
	 * Re-authentication
	 */
	account_reauthTitle: () => LocalizedString;
	/**
	 * Confirm your identity before continuing with this security-sensitive operation.
	 */
	account_reauthDescription: () => LocalizedString;
	/**
	 * Re-authenticate with Passkey
	 */
	account_reauthWithPasskey: () => LocalizedString;
	/**
	 * Re-authenticate with email code
	 */
	account_reauthWithEmailCode: () => LocalizedString;
	/**
	 * A verification code was sent to {email}.
	 */
	account_reauthEmailCodeSent: (arg: { email: string }) => LocalizedString;
	/**
	 * 6-digit code
	 */
	account_reauthEmailCodePlaceholder: () => LocalizedString;
	/**
	 * Verify code
	 */
	account_reauthVerifyEmailCode: () => LocalizedString;
	/**
	 * No authentication method is available for re-authentication.
	 */
	account_reauthNoMethods: () => LocalizedString;
	/**
	 * Devices
	 */
	account_devices: () => LocalizedString;
	/**
	 * Current
	 */
	account_currentDevice: () => LocalizedString;
	/**
	 * Sessions
	 */
	account_sessions: () => LocalizedString;
	/**
	 * Current session
	 */
	account_currentSession: () => LocalizedString;
	/**
	 * Log out
	 */
	account_logoutSession: () => LocalizedString;
	/**
	 * Passkey name
	 */
	account_passkeyName: () => LocalizedString;
	/**
	 * Add passkey
	 */
	account_addPasskey: () => LocalizedString;
	/**
	 * Delete
	 */
	account_delete: () => LocalizedString;
	/**
	 * No items
	 */
	account_empty: () => LocalizedString;
	/**
	 * Planned
	 */
	account_planned: () => LocalizedString;
	/**
	 * This browser does not support passkey registration.
	 */
	account_passkeyUnsupported: () => LocalizedString;
	/**
	 * Authenticator apps
	 */
	account_totp: () => LocalizedString;
	/**
	 * Authenticator app name
	 */
	account_totpName: () => LocalizedString;
	/**
	 * Authenticator app
	 */
	account_totpDefaultName: () => LocalizedString;
	/**
	 * Add authenticator app
	 */
	account_addTotp: () => LocalizedString;
	/**
	 * Set up authenticator app
	 */
	account_totpSetupTitle: () => LocalizedString;
	/**
	 * Authenticator app QR code
	 */
	account_totpQrAlt: () => LocalizedString;
	/**
	 * Manual key
	 */
	account_totpManualKey: () => LocalizedString;
	/**
	 * Authenticator code
	 */
	account_totpActivationCode: () => LocalizedString;
	/**
	 * Activate
	 */
	account_totpActivate: () => LocalizedString;
	/**
	 * Backup codes
	 */
	account_totpBackupCodes: () => LocalizedString;
	/**
	 * {remaining} of {total} backup codes remaining
	 */
	account_totpBackupCodesRemaining: (arg: { remaining: number; total: number }) => LocalizedString;
	/**
	 * Regenerate backup codes
	 */
	account_totpRegenerateBackupCodes: () => LocalizedString;
	/**
	 * Current code
	 */
	account_totpCurrentCode: () => LocalizedString;
	/**
	 * Current code or backup code
	 */
	account_totpDeleteCode: () => LocalizedString;
	/**
	 * Pending setup
	 */
	account_totpPending: () => LocalizedString;
	/**
	 * Done
	 */
	account_totpDone: () => LocalizedString;
	/**
	 * Last used {time}
	 */
	account_totpLastUsed: (arg: { time: string }) => LocalizedString;
	/**
	 * Re-authenticate with authenticator app
	 */
	account_reauthWithTotp: () => LocalizedString;
	/**
	 * 6- or 8-digit code
	 */
	account_reauthTotpCodePlaceholder: () => LocalizedString;
	/**
	 * The operation failed
	 */
	account_actionFailed: () => LocalizedString;
	/**
	 * Add another login method before deleting this method.
	 */
	account_remainingLoginMethodRequired: () => LocalizedString;
	/**
	 * Activity
	 */
	account_activityTitle: () => LocalizedString;
	/**
	 * Name changed
	 */
	account_operationNameUpdated: () => LocalizedString;
	/**
	 * Passkey added
	 */
	account_operationPasskeyCreated: () => LocalizedString;
	/**
	 * Passkey renamed
	 */
	account_operationPasskeyUpdated: () => LocalizedString;
	/**
	 * Passkey deleted
	 */
	account_operationPasskeyDeleted: () => LocalizedString;
	/**
	 * Session ended
	 */
	account_operationSessionRevoked: () => LocalizedString;
	/**
	 * Granted permissions
	 */
	account_consentTitle: () => LocalizedString;
	/**
	 * Review the applications and permissions you have authorized for this account.
	 */
	account_consentDescription: () => LocalizedString;
	/**
	 * No active permissions
	 */
	account_consentEmpty: () => LocalizedString;
	/**
	 * Permissions
	 */
	account_consentScopes: () => LocalizedString;
	/**
	 * Granted at
	 */
	account_consentGrantedAt: () => LocalizedString;
	/**
	 * Expires
	 */
	account_consentExpiresAt: () => LocalizedString;
	/**
	 * No expiration
	 */
	account_consentNoExpiry: () => LocalizedString;
	/**
	 * Policy versions
	 */
	account_consentPolicyVersions: () => LocalizedString;
	/**
	 * Privacy policy
	 */
	account_consentPrivacyPolicy: () => LocalizedString;
	/**
	 * Terms
	 */
	account_consentTerms: () => LocalizedString;
	/**
	 * Consent
	 */
	account_consentVersion: () => LocalizedString;
	/**
	 * Status
	 */
	account_consentStatus: () => LocalizedString;
	/**
	 * Granted
	 */
	account_consentStatusGranted: () => LocalizedString;
	/**
	 * Withdrawn
	 */
	account_consentStatusWithdrawn: () => LocalizedString;
	/**
	 * Denied
	 */
	account_consentStatusDenied: () => LocalizedString;
	/**
	 * Version
	 */
	account_consentVersionLabel: () => LocalizedString;
	/**
	 * Statement ID
	 */
	account_consentStatementId: () => LocalizedString;
	/**
	 * Decision
	 */
	account_consentSelectedValue: () => LocalizedString;
	/**
	 * This time only
	 */
	account_consentSelectedOnce: () => LocalizedString;
	/**
	 * Always allow
	 */
	account_consentSelectedAlways: () => LocalizedString;
	/**
	 * Do not allow
	 */
	account_consentSelectedNone: () => LocalizedString;
	/**
	 * Welcome back
	 */
	login_title: () => LocalizedString;
	/**
	 * Sign in to your account
	 */
	login_subtitle: () => LocalizedString;
	/**
	 * Sign in with Passkey
	 */
	login_signInWithPasskey: () => LocalizedString;
	/**
	 * Send code by email
	 */
	login_sendCode: () => LocalizedString;
	/**
	 * Email or username
	 */
	login_totpIdentifierLabel: () => LocalizedString;
	/**
	 * you@example.com or username
	 */
	login_totpIdentifierPlaceholder: () => LocalizedString;
	/**
	 * Authenticator code
	 */
	login_totpCodeLabel: () => LocalizedString;
	/**
	 * 6 or 8 digit code
	 */
	login_totpCodePlaceholder: () => LocalizedString;
	/**
	 * Sign in with authenticator app
	 */
	login_totpContinue: () => LocalizedString;
	/**
	 * Verify authenticator code
	 */
	login_totpVerify: () => LocalizedString;
	/**
	 * Email or username is required
	 */
	login_totpIdentifierRequired: () => LocalizedString;
	/**
	 * Invalid or expired authenticator code
	 */
	login_totpCodeInvalid: () => LocalizedString;
	/**
	 * Could not start authenticator app sign-in
	 */
	login_totpStartFailed: () => LocalizedString;
	/**
	 * Sign in with {label}
	 */
	login_signInWithDirectory: (arg: { label: string }) => LocalizedString;
	/**
	 * username
	 */
	login_directoryUsernamePlaceholder: () => LocalizedString;
	/**
	 * Password
	 */
	login_directoryPasswordLabel: () => LocalizedString;
	/**
	 * Password
	 */
	login_directoryPasswordPlaceholder: () => LocalizedString;
	/**
	 * Don't have an account? Create one
	 */
	login_createAccount: () => LocalizedString;
	/**
	 * Email address is required
	 */
	login_errorEmailRequired: () => LocalizedString;
	/**
	 * Please enter a valid email address
	 */
	login_errorEmailInvalid: () => LocalizedString;
	/**
	 * Username is required
	 */
	login_errorDirectoryUsernameRequired: () => LocalizedString;
	/**
	 * Password is required
	 */
	login_errorDirectoryPasswordRequired: () => LocalizedString;
	/**
	 * The username or password is incorrect
	 */
	login_errorDirectoryInvalidCredentials: () => LocalizedString;
	/**
	 * Directory sign-in is temporarily unavailable
	 */
	login_errorDirectoryUnavailable: () => LocalizedString;
	/**
	 * This directory account is not linked to an Authrim user
	 */
	login_errorDirectoryUnmapped: () => LocalizedString;
	/**
	 * Directory sign-in failed
	 */
	login_errorDirectoryFailed: () => LocalizedString;
	/**
	 * Or continue with
	 */
	login_orContinueWith: () => LocalizedString;
	/**
	 * Continue with {provider}
	 */
	login_continueWith: (arg: { provider: string }) => LocalizedString;
	/**
	 * Loading security check...
	 */
	login_humanVerificationLoading: () => LocalizedString;
	/**
	 * Security check could not be loaded. Reload the page and try again.
	 */
	login_humanVerificationLoadFailed: () => LocalizedString;
	/**
	 * No authentication method is enabled for this organization. Contact your administrator.
	 */
	login_noMethodsAvailable: () => LocalizedString;
	/**
	 * Preparing passkey authentication.
	 */
	login_passkeyPreparing: () => LocalizedString;
	/**
	 * Complete the passkey prompt in your browser or on your device.
	 */
	login_passkeyPrompt: () => LocalizedString;
	/**
	 * Verifying the authentication result.
	 */
	login_passkeyVerifying: () => LocalizedString;
	/**
	 * Could not load authentication methods.
	 */
	login_methodsLoadFailed: () => LocalizedString;
	/**
	 * Organization ID
	 */
	login_organizationId: () => LocalizedString;
	/**
	 * Passkey registration is required before completing this sign-in.
	 */
	login_directoryMigrationPasskeyRequired: () => LocalizedString;
	/**
	 * Directory sign-in is temporarily unavailable. Continue using an email code.
	 */
	login_directoryRecoveryRequired: () => LocalizedString;
	/**
	 * A verification code was sent to {email}.
	 */
	login_directoryVerificationCodeSent: (arg: { email: string }) => LocalizedString;
	/**
	 * Directory migration passkey
	 */
	login_directoryMigrationPasskeyName: () => LocalizedString;
	/**
	 * Sign in with a passkey, email code, or another available method.
	 */
	login_metaDescription: () => LocalizedString;
	/**
	 * No screen is configured for this step. Contact your administrator.
	 */
	runtime_screenUnavailable: () => LocalizedString;
	/**
	 * Select your organization
	 */
	discover_pageTitle: () => LocalizedString;
	/**
	 * Organization selection
	 */
	discover_kicker: () => LocalizedString;
	/**
	 * Find your organization
	 */
	discover_title: () => LocalizedString;
	/**
	 * Select your organization to see the authentication methods available to you.
	 */
	discover_subtitle: () => LocalizedString;
	/**
	 * This sign-in page is disabled. Use your organization-specific sign-in URL instead.
	 */
	discover_notice_disabled: () => LocalizedString;
	/**
	 * Automatic organization lookup is disabled. Enter your organization code or identifier.
	 */
	discover_notice_manualOnly: () => LocalizedString;
	/**
	 * Recently used organization
	 */
	discover_recentTenant: () => LocalizedString;
	/**
	 * Search method
	 */
	discover_methodLabel: () => LocalizedString;
	/**
	 * Email address
	 */
	discover_method_email: () => LocalizedString;
	/**
	 * Organization code
	 */
	discover_method_tenantCode: () => LocalizedString;
	/**
	 * Organization identifier
	 */
	discover_method_tenantSlug: () => LocalizedString;
	/**
	 * you@example.com
	 */
	discover_placeholder_email: () => LocalizedString;
	/**
	 * acme
	 */
	discover_placeholder_tenantCode: () => LocalizedString;
	/**
	 * acme-corp
	 */
	discover_placeholder_tenantSlug: () => LocalizedString;
	/**
	 * Select an organization
	 */
	discover_selectTenant: () => LocalizedString;
	/**
	 * No account matched that email address.
	 */
	discover_error_emailNotFound: () => LocalizedString;
	/**
	 * This email domain is not linked to an organization.
	 */
	discover_error_emailDomainNotFound: () => LocalizedString;
	/**
	 * No organization matched that code.
	 */
	discover_error_tenantCodeNotFound: () => LocalizedString;
	/**
	 * No organization matched that identifier.
	 */
	discover_error_tenantSlugNotFound: () => LocalizedString;
	/**
	 * This invitation is invalid or has expired.
	 */
	discover_error_invitationNotFound: () => LocalizedString;
	/**
	 * No organization matched this application.
	 */
	discover_error_appHintNotFound: () => LocalizedString;
	/**
	 * No organization could be identified.
	 */
	discover_error_notFound: () => LocalizedString;
	/**
	 * A value is required.
	 */
	discover_error_valueRequired: () => LocalizedString;
	/**
	 * Your organization could not be identified automatically. Enter its code or identifier.
	 */
	discover_error_manualRequired: () => LocalizedString;
	/**
	 * The invitation could not be processed.
	 */
	discover_error_invitationUnresolved: () => LocalizedString;
	/**
	 * Could not identify the organization
	 */
	discover_error_resolveFailed: () => LocalizedString;
	/**
	 * Sign up
	 */
	header_signUp: () => LocalizedString;
	/**
	 * Sign in
	 */
	header_login: () => LocalizedString;
	/**
	 * Sign out
	 */
	header_logout: () => LocalizedString;
	/**
	 * Authrim - A modern OpenID Connect Provider built with Cloudflare Workers.
	 */
	landing_metaDescription: () => LocalizedString;
	/**
	 * OpenID Connect Provider
	 */
	landing_providerBadge: () => LocalizedString;
	/**
	 * Signed in as
	 */
	landing_signedInAs: () => LocalizedString;
	/**
	 * Create your account
	 */
	register_title: () => LocalizedString;
	/**
	 * Get started with Authrim
	 */
	register_subtitle: () => LocalizedString;
	/**
	 * Create account with Passkey
	 */
	register_createWithPasskey: () => LocalizedString;
	/**
	 * Send code by email
	 */
	register_sendCode: () => LocalizedString;
	/**
	 * Sign up with authenticator app
	 */
	register_createWithTotp: () => LocalizedString;
	/**
	 * Set up authenticator app
	 */
	register_totpSetupTitle: () => LocalizedString;
	/**
	 * Could not start authenticator app setup
	 */
	register_totpStartFailed: () => LocalizedString;
	/**
	 * Already have an account? Sign in
	 */
	register_alreadyHaveAccount: () => LocalizedString;
	/**
	 * By creating an account, you agree to our Terms of Service and Privacy Policy
	 */
	register_termsAgreement: () => LocalizedString;
	/**
	 * No sign-up method is enabled for this organization. Contact your administrator.
	 */
	register_noMethodsAvailable: () => LocalizedString;
	/**
	 * This sign-up form is missing a required field. Contact your administrator.
	 */
	register_requiredFieldsMissing: () => LocalizedString;
	/**
	 * Preparing passkey registration.
	 */
	register_passkeyPreparing: () => LocalizedString;
	/**
	 * Complete the passkey prompt in your browser or on your device.
	 */
	register_passkeyPrompt: () => LocalizedString;
	/**
	 * Verifying the registration result.
	 */
	register_passkeyVerifying: () => LocalizedString;
	/**
	 * You were invited to {tenant}. Create your account to continue.
	 */
	register_invitation: (arg: { tenant: string }) => LocalizedString;
	/**
	 * Mobile device
	 */
	register_mobileDevice: () => LocalizedString;
	/**
	 * Desktop
	 */
	register_desktopDevice: () => LocalizedString;
	/**
	 * Create an account with a passkey, email code, or another available method.
	 */
	register_metaDescription: () => LocalizedString;
	/**
	 * Check your email
	 */
	emailCode_title: () => LocalizedString;
	/**
	 * We've sent a verification code to
	 */
	emailCode_subtitle: () => LocalizedString;
	/**
	 * Enter the 6-digit code from your email. The code will expire in 5 minutes.
	 */
	emailCode_instructions: () => LocalizedString;
	/**
	 * Verification code
	 */
	emailCode_codeLabel: () => LocalizedString;
	/**
	 * Verify
	 */
	emailCode_verifyButton: () => LocalizedString;
	/**
	 * Resend code
	 */
	emailCode_resendButton: () => LocalizedString;
	/**
	 * Resend in {seconds}s
	 */
	emailCode_resendTimer: (arg: { seconds: unknown }) => LocalizedString;
	/**
	 * Code sent successfully
	 */
	emailCode_resendSuccess: () => LocalizedString;
	/**
	 * Verified. Redirecting...
	 */
	emailCode_success: () => LocalizedString;
	/**
	 * Invalid or expired code
	 */
	emailCode_errorInvalid: () => LocalizedString;
	/**
	 * {clientName} wants to access your account
	 */
	consent_title: (arg: { clientName: string }) => LocalizedString;
	/**
	 * This application is requesting access to your Authrim account
	 */
	consent_subtitle: () => LocalizedString;
	/**
	 * This application will be able to:
	 */
	consent_scopesTitle: () => LocalizedString;
	/**
	 * You are signed in as
	 */
	consent_userInfo: () => LocalizedString;
	/**
	 * Not you? Switch account
	 */
	consent_notYou: () => LocalizedString;
	/**
	 * Allow
	 */
	consent_allowButton: () => LocalizedString;
	/**
	 * Deny
	 */
	consent_denyButton: () => LocalizedString;
	/**
	 * Privacy Policy
	 */
	consent_privacyPolicy: () => LocalizedString;
	/**
	 * Terms of Service
	 */
	consent_termsOfService: () => LocalizedString;
	/**
	 * Verify your identity
	 */
	consent_scope_openid: () => LocalizedString;
	/**
	 * View your profile information (name, picture)
	 */
	consent_scope_profile: () => LocalizedString;
	/**
	 * View your email address
	 */
	consent_scope_email: () => LocalizedString;
	/**
	 * View your phone number
	 */
	consent_scope_phone: () => LocalizedString;
	/**
	 * View your address
	 */
	consent_scope_address: () => LocalizedString;
	/**
	 * Access your account when you're not using the app
	 */
	consent_scope_offline_access: () => LocalizedString;
	/**
	 * Select organization
	 */
	consent_organizationSelect: () => LocalizedString;
	/**
	 * Primary
	 */
	consent_primaryOrg: () => LocalizedString;
	/**
	 * Current organization
	 */
	consent_currentOrganization: () => LocalizedString;
	/**
	 * Acting on behalf of {name}
	 */
	consent_actingOnBehalfOf: (arg: { name: string }) => LocalizedString;
	/**
	 * Delegated access
	 */
	consent_delegatedAccess: () => LocalizedString;
	/**
	 * You are authorizing this application to access {name}'s account on their behalf
	 */
	consent_delegatedAccessWarning: (arg: { name: unknown }) => LocalizedString;
	/**
	 * Your roles
	 */
	consent_yourRoles: () => LocalizedString;
	/**
	 * Trusted application
	 */
	consent_trustedClient: () => LocalizedString;
	/**
	 * Required consents
	 */
	consent_items_required_title: () => LocalizedString;
	/**
	 * Optional consents
	 */
	consent_items_optional_title: () => LocalizedString;
	/**
	 * View document
	 */
	consent_item_view_document: () => LocalizedString;
	/**
	 * {oldVersion} → {newVersion} updated
	 */
	consent_item_version_updated: (arg: {
		newVersion: string;
		oldVersion: string;
	}) => LocalizedString;
	/**
	 * Required
	 */
	consent_item_required_badge: () => LocalizedString;
	/**
	 * Optional
	 */
	consent_item_optional_badge: () => LocalizedString;
	/**
	 * Processing purpose
	 */
	consent_item_processing_purpose: () => LocalizedString;
	/**
	 * Withdrawal impact
	 */
	consent_item_withdrawal_impact: () => LocalizedString;
	/**
	 * Request account deletion
	 */
	consent_delete_account_link: () => LocalizedString;
	/**
	 * You must agree to all required consent items to continue. If you do not agree, you may request account deletion.
	 */
	consent_block_message: () => LocalizedString;
	/**
	 * Oops! Something went wrong
	 */
	error_title: () => LocalizedString;
	/**
	 * We encountered an error while processing your request
	 */
	error_subtitle: () => LocalizedString;
	/**
	 * If this problem persists, please contact support
	 */
	error_contactSupport: () => LocalizedString;
	/**
	 * Error code
	 */
	error_errorCode: () => LocalizedString;
	/**
	 * The request is missing a required parameter or is otherwise malformed
	 */
	error_invalid_request: () => LocalizedString;
	/**
	 * You denied the authorization request
	 */
	error_access_denied: () => LocalizedString;
	/**
	 * The client is not authorized to request an authorization code
	 */
	error_unauthorized_client: () => LocalizedString;
	/**
	 * The authorization server does not support this response type
	 */
	error_unsupported_response_type: () => LocalizedString;
	/**
	 * The requested scope is invalid, unknown, or malformed
	 */
	error_invalid_scope: () => LocalizedString;
	/**
	 * The authorization server encountered an unexpected error
	 */
	error_server_error: () => LocalizedString;
	/**
	 * The authorization server is temporarily unable to handle the request
	 */
	error_temporarily_unavailable: () => LocalizedString;
	/**
	 * Authentication required. Please sign in to continue.
	 */
	error_login_required: () => LocalizedString;
	/**
	 * An unknown error occurred
	 */
	error_unknown: () => LocalizedString;
	/**
	 * Device verification
	 */
	device_title: () => LocalizedString;
	/**
	 * Enter the code shown on your device
	 */
	device_subtitle: () => LocalizedString;
	/**
	 * Verification code
	 */
	device_codeLabel: () => LocalizedString;
	/**
	 * XXXX-XXXX
	 */
	device_codePlaceholder: () => LocalizedString;
	/**
	 * Enter the 8-character code from your device (format: XXXX-XXXX)
	 */
	device_codeHint: () => LocalizedString;
	/**
	 * Verify code
	 */
	device_verifyButton: () => LocalizedString;
	/**
	 * Authorize device
	 */
	device_confirmTitle: () => LocalizedString;
	/**
	 * Requested permissions
	 */
	device_requestedPermissions: () => LocalizedString;
	/**
	 * Approve
	 */
	device_approveButton: () => LocalizedString;
	/**
	 * Deny
	 */
	device_denyButton: () => LocalizedString;
	/**
	 * Device authorized. You can now close this window.
	 */
	device_success: () => LocalizedString;
	/**
	 * Invalid or expired verification code
	 */
	device_errorInvalidCode: () => LocalizedString;
	/**
	 * Invalid or expired code
	 */
	device_errorInvalidOrExpiredCode: () => LocalizedString;
	/**
	 * Failed to verify device code
	 */
	device_errorVerifyFailed: () => LocalizedString;
	/**
	 * Failed to approve device
	 */
	device_errorApproveFailed: () => LocalizedString;
	/**
	 * Could not deny the device request
	 */
	device_errorDenyFailed: () => LocalizedString;
	/**
	 * Invalid redirect URL received from server
	 */
	device_errorInvalidRedirect: () => LocalizedString;
	/**
	 * Authentication request
	 */
	ciba_title: () => LocalizedString;
	/**
	 * An application is requesting your approval
	 */
	ciba_subtitle: () => LocalizedString;
	/**
	 * No pending authentication requests
	 */
	ciba_noPendingRequests: () => LocalizedString;
	/**
	 * You don't have any pending authentication requests at the moment.
	 */
	ciba_noPendingDescription: () => LocalizedString;
	/**
	 * Verification message
	 */
	ciba_bindingMessage: () => LocalizedString;
	/**
	 * Authentication request
	 */
	ciba_authenticationRequest: () => LocalizedString;
	/**
	 * Expires in
	 */
	ciba_expiresIn: () => LocalizedString;
	/**
	 * Verification code
	 */
	ciba_verificationCode: () => LocalizedString;
	/**
	 * Requested access
	 */
	ciba_requestedAccess: () => LocalizedString;
	/**
	 * Approve
	 */
	ciba_approveButton: () => LocalizedString;
	/**
	 * Reject
	 */
	ciba_rejectButton: () => LocalizedString;
	/**
	 * Request approved
	 */
	ciba_approvedSuccess: () => LocalizedString;
	/**
	 * Request rejected
	 */
	ciba_rejectedSuccess: () => LocalizedString;
	/**
	 * Expired
	 */
	ciba_expired: () => LocalizedString;
	/**
	 * Refresh
	 */
	ciba_refresh: () => LocalizedString;
	/**
	 * Failed to load pending requests
	 */
	ciba_errorLoadPending: () => LocalizedString;
	/**
	 * An error occurred
	 */
	ciba_errorGeneric: () => LocalizedString;
	/**
	 * Failed to approve request
	 */
	ciba_errorApproveFailed: () => LocalizedString;
	/**
	 * Failed to deny request
	 */
	ciba_errorDenyFailed: () => LocalizedString;
	/**
	 * Verify your identity
	 */
	reauth_title: () => LocalizedString;
	/**
	 * For security, please re-authenticate to continue
	 */
	reauth_subtitle: () => LocalizedString;
	/**
	 * Verify with Passkey
	 */
	reauth_verifyWithPasskey: () => LocalizedString;
	/**
	 * Verify with email code
	 */
	reauth_verifyWithEmailCode: () => LocalizedString;
	/**
	 * Verify with authenticator app
	 */
	reauth_verifyWithTotp: () => LocalizedString;
	/**
	 * Signing in
	 */
	callback_title: () => LocalizedString;
	/**
	 * Processing authentication...
	 */
	callback_processing: () => LocalizedString;
	/**
	 * Please wait while we complete your sign-in.
	 */
	callback_pleaseWait: () => LocalizedString;
	/**
	 * Sign-in successful!
	 */
	callback_success: () => LocalizedString;
	/**
	 * Redirecting...
	 */
	callback_redirecting: () => LocalizedString;
	/**
	 * Authentication failed
	 */
	callback_errorTitle: () => LocalizedString;
	/**
	 * No authorization code received. Please try signing in again.
	 */
	callback_errorMissingCode: () => LocalizedString;
	/**
	 * Back to home
	 */
	common_backToHome: () => LocalizedString;
	/**
	 * Account already exists
	 */
	login_extError_accountExists_title: () => LocalizedString;
	/**
	 * An account with this email already exists. Sign in with your existing credentials first.
	 */
	login_extError_accountExists_message: () => LocalizedString;
	/**
	 * After signing in, you can link your external account from the settings page.
	 */
	login_extError_accountExists_action: () => LocalizedString;
	/**
	 * Email not verified
	 */
	login_extError_emailNotVerified_title: () => LocalizedString;
	/**
	 * The email from your external account is not verified. Please verify your email with the provider first.
	 */
	login_extError_emailNotVerified_message: () => LocalizedString;
	/**
	 * Verify your email
	 */
	login_extError_localEmailNotVerified_title: () => LocalizedString;
	/**
	 * Your existing account email is not verified. Please verify your email first before linking external accounts.
	 */
	login_extError_localEmailNotVerified_message: () => LocalizedString;
	/**
	 * Registration not available
	 */
	login_extError_jitDisabled_title: () => LocalizedString;
	/**
	 * New account registration via external providers is not available. Please register with email first or contact your administrator.
	 */
	login_extError_jitDisabled_message: () => LocalizedString;
	/**
	 * No account found
	 */
	login_extError_noAccount_title: () => LocalizedString;
	/**
	 * No account was found. Please register first.
	 */
	login_extError_noAccount_message: () => LocalizedString;
	/**
	 * Provider error
	 */
	login_extError_providerError_title: () => LocalizedString;
	/**
	 * The external provider returned an error. Please try again later.
	 */
	login_extError_providerError_message: () => LocalizedString;
	/**
	 * Authentication failed
	 */
	login_extError_callbackFailed_title: () => LocalizedString;
	/**
	 * An error occurred during authentication. Please try again.
	 */
	login_extError_callbackFailed_message: () => LocalizedString;
	/**
	 * Authentication error
	 */
	login_extError_default_title: () => LocalizedString;
	/**
	 * An error occurred during external authentication.
	 */
	login_extError_default_message: () => LocalizedString;
	/**
	 * Signing in to
	 */
	login_signingInTo: () => LocalizedString;
	/**
	 * Contact support
	 */
	common_contactSupport: () => LocalizedString;
	/**
	 * Dismiss alert
	 */
	common_dismissAlert: () => LocalizedString;
	/**
	 * Digit {position} of 6
	 */
	emailCode_digitLabel: (arg: { position: number }) => LocalizedString;
};

export type Formatters = {};
