// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​u​t​h​r​i​m
	 */
	app_title: string
	/**
	 * O​p​e​n​I​D​ ​C​o​n​n​e​c​t​ ​P​r​o​v​i​d​e​r​ ​o​n​ ​C​l​o​u​d​f​l​a​r​e​ ​W​o​r​k​e​r​s
	 */
	app_subtitle: string
	/**
	 * F​r​o​n​t​e​n​d​ ​S​t​a​c​k​ ​T​e​s​t
	 */
	test_title: string
	/**
	 * T​e​s​t​ ​M​e​l​t​ ​U​I​ ​(​H​e​a​d​l​e​s​s​ ​C​o​m​p​o​n​e​n​t​s​)​:
	 */
	test_meltui: string
	/**
	 * P​r​i​m​a​r​y​ ​B​u​t​t​o​n
	 */
	button_primary: string
	/**
	 * S​e​c​o​n​d​a​r​y​ ​B​u​t​t​o​n
	 */
	button_secondary: string
	/**
	 * G​h​o​s​t​ ​B​u​t​t​o​n
	 */
	button_ghost: string
	/**
	 * O​p​e​n​ ​D​i​a​l​o​g
	 */
	button_openDialog: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	form_email: string
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
	 */
	form_emailPlaceholder: string
	/**
	 * S​u​c​c​e​s​s
	 */
	badge_success: string
	/**
	 * W​a​r​n​i​n​g
	 */
	badge_warning: string
	/**
	 * E​r​r​o​r
	 */
	badge_error: string
	/**
	 * I​n​f​o
	 */
	badge_info: string
	/**
	 * M​e​l​t​ ​U​I​ ​D​i​a​l​o​g
	 */
	dialog_title: string
	/**
	 * T​h​i​s​ ​i​s​ ​a​ ​t​e​s​t​ ​d​i​a​l​o​g​ ​u​s​i​n​g​ ​M​e​l​t​ ​U​I​,​ ​a​ ​h​e​a​d​l​e​s​s​,​ ​a​c​c​e​s​s​i​b​l​e​ ​c​o​m​p​o​n​e​n​t​ ​l​i​b​r​a​r​y​ ​f​o​r​ ​S​v​e​l​t​e​.
	 */
	dialog_description: string
	/**
	 * C​a​n​c​e​l
	 */
	dialog_cancel: string
	/**
	 * C​o​n​f​i​r​m
	 */
	dialog_confirm: string
	/**
	 * C​l​o​s​e
	 */
	dialog_close: string
	/**
	 * S​v​e​l​t​e​K​i​t​ ​v​5​ ​+​ ​U​n​o​C​S​S​ ​+​ ​M​e​l​t​ ​U​I​ ​+​ ​C​l​o​u​d​f​l​a​r​e​ ​P​a​g​e​s
	 */
	footer_stack: string
	/**
	 * S​w​i​t​c​h​ ​L​a​n​g​u​a​g​e
	 */
	language_switch: string
	/**
	 * E​n​g​l​i​s​h
	 */
	language_english: string
	/**
	 * J​a​p​a​n​e​s​e
	 */
	language_japanese: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	common_email: string
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
	 */
	common_emailPlaceholder: string
	/**
	 * F​u​l​l​ ​n​a​m​e
	 */
	common_name: string
	/**
	 * J​o​h​n​ ​D​o​e
	 */
	common_namePlaceholder: string
	/**
	 * C​o​n​t​i​n​u​e
	 */
	common_continue: string
	/**
	 * C​a​n​c​e​l
	 */
	common_cancel: string
	/**
	 * B​a​c​k​ ​t​o​ ​l​o​g​i​n
	 */
	common_backToLogin: string
	/**
	 * o​r
	 */
	common_or: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	common_loading: string
	/**
	 * W​e​l​c​o​m​e​ ​b​a​c​k
	 */
	login_title: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	login_subtitle: string
	/**
	 * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	login_continueWithPasskey: string
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	login_signInWithPasskey: string
	/**
	 * S​e​n​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	login_sendCode: string
	/**
	 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​C​r​e​a​t​e​ ​o​n​e
	 */
	login_createAccount: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	login_errorEmailRequired: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	login_errorEmailInvalid: string
	/**
	 * O​r​ ​c​o​n​t​i​n​u​e​ ​w​i​t​h
	 */
	login_orContinueWith: string
	/**
	 * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
	 * @param {string} provider
	 */
	login_continueWith: RequiredParams<'provider'>
	/**
	 * T​e​n​a​n​t​ ​D​i​s​c​o​v​e​r​y
	 */
	discover_pageTitle: string
	/**
	 * T​e​n​a​n​t​ ​d​i​s​c​o​v​e​r​y
	 */
	discover_kicker: string
	/**
	 * F​i​n​d​ ​y​o​u​r​ ​t​e​n​a​n​t
	 */
	discover_title: string
	/**
	 * R​e​s​o​l​v​e​ ​t​h​e​ ​c​o​r​r​e​c​t​ ​t​e​n​a​n​t​ ​f​i​r​s​t​.​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​m​e​t​h​o​d​s​ ​a​r​e​ ​l​o​a​d​e​d​ ​a​f​t​e​r​ ​t​h​e​ ​t​e​n​a​n​t​ ​i​s​ ​c​o​n​f​i​r​m​e​d​.
	 */
	discover_subtitle: string
	/**
	 * T​h​i​s​ ​e​n​t​r​y​ ​p​o​i​n​t​ ​i​s​ ​d​i​s​a​b​l​e​d​ ​f​o​r​ ​t​h​i​s​ ​t​e​n​a​n​t​.​ ​U​s​e​ ​t​h​e​ ​t​e​n​a​n​t​-​s​p​e​c​i​f​i​c​ ​l​o​g​i​n​ ​U​R​L​ ​i​n​s​t​e​a​d​.
	 */
	discover_notice_disabled: string
	/**
	 * A​u​t​o​m​a​t​i​c​ ​t​e​n​a​n​t​ ​d​i​s​c​o​v​e​r​y​ ​i​s​ ​d​i​s​a​b​l​e​d​.​ ​E​n​t​e​r​ ​y​o​u​r​ ​t​e​n​a​n​t​ ​c​o​d​e​ ​o​r​ ​t​e​n​a​n​t​ ​s​l​u​g​ ​t​o​ ​c​o​n​t​i​n​u​e​.
	 */
	discover_notice_manualOnly: string
	/**
	 * R​e​c​e​n​t​ ​t​e​n​a​n​t
	 */
	discover_recentTenant: string
	/**
	 * D​i​s​c​o​v​e​r​y​ ​m​e​t​h​o​d
	 */
	discover_methodLabel: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	discover_method_email: string
	/**
	 * T​e​n​a​n​t​ ​c​o​d​e
	 */
	discover_method_tenantCode: string
	/**
	 * T​e​n​a​n​t​ ​s​l​u​g
	 */
	discover_method_tenantSlug: string
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
	 */
	discover_placeholder_email: string
	/**
	 * a​c​m​e
	 */
	discover_placeholder_tenantCode: string
	/**
	 * a​c​m​e​-​c​o​r​p
	 */
	discover_placeholder_tenantSlug: string
	/**
	 * S​e​l​e​c​t​ ​a​ ​t​e​n​a​n​t
	 */
	discover_selectTenant: string
	/**
	 * N​o​ ​a​c​c​o​u​n​t​ ​m​a​t​c​h​e​d​ ​t​h​a​t​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
	 */
	discover_error_emailNotFound: string
	/**
	 * T​h​i​s​ ​e​m​a​i​l​ ​d​o​m​a​i​n​ ​i​s​ ​n​o​t​ ​m​a​p​p​e​d​ ​t​o​ ​a​ ​t​e​n​a​n​t​.
	 */
	discover_error_emailDomainNotFound: string
	/**
	 * N​o​ ​t​e​n​a​n​t​ ​m​a​t​c​h​e​d​ ​t​h​a​t​ ​t​e​n​a​n​t​ ​c​o​d​e​.
	 */
	discover_error_tenantCodeNotFound: string
	/**
	 * N​o​ ​t​e​n​a​n​t​ ​m​a​t​c​h​e​d​ ​t​h​a​t​ ​t​e​n​a​n​t​ ​s​l​u​g​.
	 */
	discover_error_tenantSlugNotFound: string
	/**
	 * T​h​i​s​ ​i​n​v​i​t​a​t​i​o​n​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​h​a​s​ ​e​x​p​i​r​e​d​.
	 */
	discover_error_invitationNotFound: string
	/**
	 * N​o​ ​t​e​n​a​n​t​ ​m​a​t​c​h​e​d​ ​t​h​a​t​ ​a​p​p​l​i​c​a​t​i​o​n​ ​h​i​n​t​.
	 */
	discover_error_appHintNotFound: string
	/**
	 * N​o​ ​t​e​n​a​n​t​ ​c​o​u​l​d​ ​b​e​ ​r​e​s​o​l​v​e​d​.
	 */
	discover_error_notFound: string
	/**
	 * A​ ​v​a​l​u​e​ ​i​s​ ​r​e​q​u​i​r​e​d​.
	 */
	discover_error_valueRequired: string
	/**
	 * T​e​n​a​n​t​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​r​e​s​o​l​v​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​.​ ​E​n​t​e​r​ ​y​o​u​r​ ​t​e​n​a​n​t​ ​c​o​d​e​ ​o​r​ ​t​e​n​a​n​t​ ​s​l​u​g​ ​t​o​ ​c​o​n​t​i​n​u​e​.
	 */
	discover_error_manualRequired: string
	/**
	 * T​h​e​ ​i​n​v​i​t​a​t​i​o​n​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​r​e​s​o​l​v​e​d​.
	 */
	discover_error_invitationUnresolved: string
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​r​e​s​o​l​v​e​ ​t​e​n​a​n​t
	 */
	discover_error_resolveFailed: string
	/**
	 * S​i​g​n​ ​U​p
	 */
	header_signUp: string
	/**
	 * L​o​g​i​n
	 */
	header_login: string
	/**
	 * L​o​g​o​u​t
	 */
	header_logout: string
	/**
	 * C​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	register_title: string
	/**
	 * G​e​t​ ​s​t​a​r​t​e​d​ ​w​i​t​h​ ​A​u​t​h​r​i​m
	 */
	register_subtitle: string
	/**
	 * C​r​e​a​t​e​ ​A​c​c​o​u​n​t​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	register_createWithPasskey: string
	/**
	 * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	register_sendCode: string
	/**
	 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​S​i​g​n​ ​i​n
	 */
	register_alreadyHaveAccount: string
	/**
	 * B​y​ ​c​r​e​a​t​i​n​g​ ​a​n​ ​a​c​c​o​u​n​t​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​o​u​r​ ​T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e​ ​a​n​d​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y
	 */
	register_termsAgreement: string
	/**
	 * N​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	register_errorNameRequired: string
	/**
	 * C​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l
	 */
	emailCode_title: string
	/**
	 * W​e​'​v​e​ ​s​e​n​t​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​t​o
	 */
	emailCode_subtitle: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​6​-​d​i​g​i​t​ ​c​o​d​e​ ​f​r​o​m​ ​y​o​u​r​ ​e​m​a​i​l​.​ ​T​h​e​ ​c​o​d​e​ ​w​i​l​l​ ​e​x​p​i​r​e​ ​i​n​ ​5​ ​m​i​n​u​t​e​s​.
	 */
	emailCode_instructions: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
	 */
	emailCode_codeLabel: string
	/**
	 * V​e​r​i​f​y
	 */
	emailCode_verifyButton: string
	/**
	 * R​e​s​e​n​d​ ​c​o​d​e
	 */
	emailCode_resendButton: string
	/**
	 * R​e​s​e​n​d​ ​i​n​ ​{​s​e​c​o​n​d​s​}​s
	 * @param {unknown} seconds
	 */
	emailCode_resendTimer: RequiredParams<'seconds'>
	/**
	 * C​o​d​e​ ​s​e​n​t​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	emailCode_resendSuccess: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​s​u​c​c​e​s​s​f​u​l​!​ ​R​e​d​i​r​e​c​t​i​n​g​.​.​.
	 */
	emailCode_success: string
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​c​o​d​e
	 */
	emailCode_errorInvalid: string
	/**
	 * S​e​s​s​i​o​n​ ​m​i​s​m​a​t​c​h​.​ ​P​l​e​a​s​e​ ​r​e​q​u​e​s​t​ ​a​ ​n​e​w​ ​c​o​d​e​.
	 */
	emailCode_errorSessionMismatch: string
	/**
	 * {​c​l​i​e​n​t​N​a​m​e​}​ ​w​a​n​t​s​ ​t​o​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 * @param {string} clientName
	 */
	consent_title: RequiredParams<'clientName'>
	/**
	 * T​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​r​e​q​u​e​s​t​i​n​g​ ​a​c​c​e​s​s​ ​t​o​ ​y​o​u​r​ ​A​u​t​h​r​i​m​ ​a​c​c​o​u​n​t
	 */
	consent_subtitle: string
	/**
	 * T​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​:
	 */
	consent_scopesTitle: string
	/**
	 * Y​o​u​ ​a​r​e​ ​s​i​g​n​e​d​ ​i​n​ ​a​s
	 */
	consent_userInfo: string
	/**
	 * N​o​t​ ​y​o​u​?​ ​S​w​i​t​c​h​ ​a​c​c​o​u​n​t
	 */
	consent_notYou: string
	/**
	 * A​l​l​o​w
	 */
	consent_allowButton: string
	/**
	 * D​e​n​y
	 */
	consent_denyButton: string
	/**
	 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
	 */
	consent_privacyPolicy: string
	/**
	 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
	 */
	consent_termsOfService: string
	/**
	 * V​e​r​i​f​y​ ​y​o​u​r​ ​i​d​e​n​t​i​t​y
	 */
	consent_scope_openid: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​(​n​a​m​e​,​ ​p​i​c​t​u​r​e​)
	 */
	consent_scope_profile: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	consent_scope_email: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r
	 */
	consent_scope_phone: string
	/**
	 * V​i​e​w​ ​y​o​u​r​ ​a​d​d​r​e​s​s
	 */
	consent_scope_address: string
	/**
	 * M​a​i​n​t​a​i​n​ ​a​c​c​e​s​s​ ​w​h​e​n​ ​y​o​u​'​r​e​ ​n​o​t​ ​u​s​i​n​g​ ​t​h​e​ ​a​p​p
	 */
	consent_scope_offline_access: string
	/**
	 * S​e​l​e​c​t​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	consent_organizationSelect: string
	/**
	 * P​r​i​m​a​r​y
	 */
	consent_primaryOrg: string
	/**
	 * C​u​r​r​e​n​t​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	consent_currentOrganization: string
	/**
	 * A​c​t​i​n​g​ ​o​n​ ​b​e​h​a​l​f​ ​o​f​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	consent_actingOnBehalfOf: RequiredParams<'name'>
	/**
	 * D​e​l​e​g​a​t​e​d​ ​A​c​c​e​s​s
	 */
	consent_delegatedAccess: string
	/**
	 * Y​o​u​ ​a​r​e​ ​a​u​t​h​o​r​i​z​i​n​g​ ​t​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​ ​t​o​ ​a​c​c​e​s​s​ ​{​n​a​m​e​}​'​s​ ​a​c​c​o​u​n​t​ ​o​n​ ​t​h​e​i​r​ ​b​e​h​a​l​f
	 * @param {unknown} name
	 */
	consent_delegatedAccessWarning: RequiredParams<'name'>
	/**
	 * Y​o​u​r​ ​r​o​l​e​s
	 */
	consent_yourRoles: string
	/**
	 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n
	 */
	consent_noOrganization: string
	/**
	 * T​r​u​s​t​e​d​ ​a​p​p​l​i​c​a​t​i​o​n
	 */
	consent_trustedClient: string
	/**
	 * R​e​q​u​i​r​e​d​ ​c​o​n​s​e​n​t​s
	 */
	consent_items_required_title: string
	/**
	 * O​p​t​i​o​n​a​l​ ​c​o​n​s​e​n​t​s
	 */
	consent_items_optional_title: string
	/**
	 * V​i​e​w​ ​d​o​c​u​m​e​n​t
	 */
	consent_item_view_document: string
	/**
	 * {​o​l​d​V​e​r​s​i​o​n​}​ ​→​ ​{​n​e​w​V​e​r​s​i​o​n​}​ ​u​p​d​a​t​e​d
	 * @param {string} newVersion
	 * @param {string} oldVersion
	 */
	consent_item_version_updated: RequiredParams<'newVersion' | 'oldVersion'>
	/**
	 * R​e​q​u​i​r​e​d
	 */
	consent_item_required_badge: string
	/**
	 * O​p​t​i​o​n​a​l
	 */
	consent_item_optional_badge: string
	/**
	 * R​e​q​u​e​s​t​ ​a​c​c​o​u​n​t​ ​d​e​l​e​t​i​o​n
	 */
	consent_delete_account_link: string
	/**
	 * Y​o​u​ ​m​u​s​t​ ​a​g​r​e​e​ ​t​o​ ​a​l​l​ ​r​e​q​u​i​r​e​d​ ​c​o​n​s​e​n​t​ ​i​t​e​m​s​ ​t​o​ ​c​o​n​t​i​n​u​e​.​ ​I​f​ ​y​o​u​ ​d​o​ ​n​o​t​ ​a​g​r​e​e​,​ ​y​o​u​ ​m​a​y​ ​r​e​q​u​e​s​t​ ​a​c​c​o​u​n​t​ ​d​e​l​e​t​i​o​n​.
	 */
	consent_block_message: string
	/**
	 * O​o​p​s​!​ ​S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	error_title: string
	/**
	 * W​e​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​n​ ​e​r​r​o​r​ ​w​h​i​l​e​ ​p​r​o​c​e​s​s​i​n​g​ ​y​o​u​r​ ​r​e​q​u​e​s​t
	 */
	error_subtitle: string
	/**
	 * I​f​ ​t​h​i​s​ ​p​r​o​b​l​e​m​ ​p​e​r​s​i​s​t​s​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​s​u​p​p​o​r​t
	 */
	error_contactSupport: string
	/**
	 * E​r​r​o​r​ ​c​o​d​e
	 */
	error_errorCode: string
	/**
	 * T​h​e​ ​r​e​q​u​e​s​t​ ​i​s​ ​m​i​s​s​i​n​g​ ​a​ ​r​e​q​u​i​r​e​d​ ​p​a​r​a​m​e​t​e​r​ ​o​r​ ​i​s​ ​o​t​h​e​r​w​i​s​e​ ​m​a​l​f​o​r​m​e​d
	 */
	error_invalid_request: string
	/**
	 * Y​o​u​ ​d​e​n​i​e​d​ ​t​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​r​e​q​u​e​s​t
	 */
	error_access_denied: string
	/**
	 * T​h​e​ ​c​l​i​e​n​t​ ​i​s​ ​n​o​t​ ​a​u​t​h​o​r​i​z​e​d​ ​t​o​ ​r​e​q​u​e​s​t​ ​a​n​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​c​o​d​e
	 */
	error_unauthorized_client: string
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​d​o​e​s​ ​n​o​t​ ​s​u​p​p​o​r​t​ ​t​h​i​s​ ​r​e​s​p​o​n​s​e​ ​t​y​p​e
	 */
	error_unsupported_response_type: string
	/**
	 * T​h​e​ ​r​e​q​u​e​s​t​e​d​ ​s​c​o​p​e​ ​i​s​ ​i​n​v​a​l​i​d​,​ ​u​n​k​n​o​w​n​,​ ​o​r​ ​m​a​l​f​o​r​m​e​d
	 */
	error_invalid_scope: string
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r
	 */
	error_server_error: string
	/**
	 * T​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​i​s​ ​t​e​m​p​o​r​a​r​i​l​y​ ​u​n​a​b​l​e​ ​t​o​ ​h​a​n​d​l​e​ ​t​h​e​ ​r​e​q​u​e​s​t
	 */
	error_temporarily_unavailable: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​q​u​i​r​e​d​.​ ​P​l​e​a​s​e​ ​s​i​g​n​ ​i​n​ ​t​o​ ​c​o​n​t​i​n​u​e​.
	 */
	error_login_required: string
	/**
	 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
	 */
	error_unknown: string
	/**
	 * D​e​v​i​c​e​ ​V​e​r​i​f​i​c​a​t​i​o​n
	 */
	device_title: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​c​o​d​e​ ​s​h​o​w​n​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e
	 */
	device_subtitle: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​8​-​c​h​a​r​a​c​t​e​r​ ​c​o​d​e​ ​d​i​s​p​l​a​y​e​d​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​t​o​ ​a​u​t​h​o​r​i​z​e​ ​i​t
	 */
	device_instructions: string
	/**
	 * S​c​a​n​ ​t​h​i​s​ ​Q​R​ ​c​o​d​e
	 */
	device_qrCodeLabel: string
	/**
	 * o​r​ ​e​n​t​e​r​ ​c​o​d​e​ ​m​a​n​u​a​l​l​y
	 */
	device_orManual: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
	 */
	device_codeLabel: string
	/**
	 * X​X​X​X​-​X​X​X​X
	 */
	device_codePlaceholder: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​8​-​c​h​a​r​a​c​t​e​r​ ​c​o​d​e​ ​f​r​o​m​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​(​f​o​r​m​a​t​:​ ​X​X​X​X​-​X​X​X​X​)
	 */
	device_codeHint: string
	/**
	 * V​e​r​i​f​y​ ​C​o​d​e
	 */
	device_verifyButton: string
	/**
	 * A​u​t​h​o​r​i​z​e​ ​D​e​v​i​c​e
	 */
	device_confirmTitle: string
	/**
	 * D​e​v​i​c​e​ ​a​u​t​h​o​r​i​z​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!​ ​Y​o​u​ ​c​a​n​ ​c​l​o​s​e​ ​t​h​i​s​ ​w​i​n​d​o​w​.
	 */
	device_successMessage: string
	/**
	 * R​e​q​u​e​s​t​e​d​ ​p​e​r​m​i​s​s​i​o​n​s
	 */
	device_requestedPermissions: string
	/**
	 * A​p​p​r​o​v​e
	 */
	device_approveButton: string
	/**
	 * D​e​n​y
	 */
	device_denyButton: string
	/**
	 * D​e​v​i​c​e​ ​a​u​t​h​o​r​i​z​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​c​l​o​s​e​ ​t​h​i​s​ ​w​i​n​d​o​w​.
	 */
	device_success: string
	/**
	 * D​e​v​i​c​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​d​e​n​i​e​d
	 */
	device_denied: string
	/**
	 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	device_errorInvalidCode: string
	/**
	 * T​h​i​s​ ​c​o​d​e​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​b​e​e​n​ ​u​s​e​d
	 */
	device_errorAlreadyUsed: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	device_errorGeneric: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​t​h​e​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e
	 */
	device_errorCodeRequired: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​R​e​q​u​e​s​t
	 */
	ciba_title: string
	/**
	 * A​n​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​r​e​q​u​e​s​t​i​n​g​ ​y​o​u​r​ ​a​p​p​r​o​v​a​l
	 */
	ciba_subtitle: string
	/**
	 * N​o​ ​p​e​n​d​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​r​e​q​u​e​s​t​s
	 */
	ciba_noPendingRequests: string
	/**
	 * V​e​r​i​f​i​c​a​t​i​o​n​ ​m​e​s​s​a​g​e
	 */
	ciba_bindingMessage: string
	/**
	 * R​e​q​u​e​s​t​e​d​ ​p​e​r​m​i​s​s​i​o​n​s
	 */
	ciba_requestedPermissions: string
	/**
	 * A​p​p​r​o​v​e
	 */
	ciba_approveButton: string
	/**
	 * R​e​j​e​c​t
	 */
	ciba_rejectButton: string
	/**
	 * R​e​q​u​e​s​t​ ​a​p​p​r​o​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	ciba_approvedSuccess: string
	/**
	 * R​e​q​u​e​s​t​ ​r​e​j​e​c​t​e​d
	 */
	ciba_rejectedSuccess: string
	/**
	 * E​x​p​i​r​e​d
	 */
	ciba_expired: string
	/**
	 * {​m​i​n​u​t​e​s​}​m​ ​{​s​e​c​o​n​d​s​}​s​ ​r​e​m​a​i​n​i​n​g
	 * @param {number} minutes
	 * @param {number} seconds
	 */
	ciba_remainingMinutes: RequiredParams<'minutes' | 'seconds'>
	/**
	 * {​s​e​c​o​n​d​s​}​s​ ​r​e​m​a​i​n​i​n​g
	 * @param {number} seconds
	 */
	ciba_remainingSeconds: RequiredParams<'seconds'>
	/**
	 * V​e​r​i​f​y​ ​Y​o​u​r​ ​I​d​e​n​t​i​t​y
	 */
	reauth_title: string
	/**
	 * F​o​r​ ​s​e​c​u​r​i​t​y​,​ ​p​l​e​a​s​e​ ​r​e​-​a​u​t​h​e​n​t​i​c​a​t​e​ ​t​o​ ​c​o​n​t​i​n​u​e
	 */
	reauth_subtitle: string
	/**
	 * V​e​r​i​f​y​ ​w​i​t​h​ ​P​a​s​s​k​e​y
	 */
	reauth_verifyWithPasskey: string
	/**
	 * V​e​r​i​f​y​ ​w​i​t​h​ ​E​m​a​i​l​ ​C​o​d​e
	 */
	reauth_verifyWithEmailCode: string
	/**
	 * S​i​g​n​i​n​g​ ​I​n
	 */
	callback_title: string
	/**
	 * P​r​o​c​e​s​s​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.​.​.
	 */
	callback_processing: string
	/**
	 * P​l​e​a​s​e​ ​w​a​i​t​ ​w​h​i​l​e​ ​w​e​ ​c​o​m​p​l​e​t​e​ ​y​o​u​r​ ​s​i​g​n​-​i​n​.
	 */
	callback_pleaseWait: string
	/**
	 * S​i​g​n​-​i​n​ ​s​u​c​c​e​s​s​f​u​l​!
	 */
	callback_success: string
	/**
	 * R​e​d​i​r​e​c​t​i​n​g​ ​y​o​u​ ​n​o​w​.​.​.
	 */
	callback_redirecting: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​F​a​i​l​e​d
	 */
	callback_errorTitle: string
	/**
	 * N​o​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​c​o​d​e​ ​r​e​c​e​i​v​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​a​g​a​i​n​.
	 */
	callback_errorMissingCode: string
	/**
	 * S​e​c​u​r​i​t​y​ ​v​a​l​i​d​a​t​i​o​n​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​a​g​a​i​n​.
	 */
	callback_errorStateMismatch: string
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	callback_errorExchangeFailed: string
	/**
	 * A​ ​n​e​t​w​o​r​k​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​c​o​n​n​e​c​t​i​o​n​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	callback_errorNetwork: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​l​o​g​g​i​n​g​ ​i​n​ ​a​g​a​i​n​.
	 */
	callback_errorMissingCodeVerifier: string
	/**
	 * Y​o​u​r​ ​b​r​o​w​s​e​r​ ​s​e​t​t​i​n​g​s​ ​p​r​e​v​e​n​t​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.​ ​P​l​e​a​s​e​ ​e​n​a​b​l​e​ ​c​o​o​k​i​e​s​ ​a​n​d​ ​s​t​o​r​a​g​e​.
	 */
	callback_errorStorageUnavailable: string
	/**
	 * Y​o​u​r​ ​b​r​o​w​s​e​r​ ​s​t​o​r​a​g​e​ ​i​s​ ​f​u​l​l​.​ ​P​l​e​a​s​e​ ​c​l​e​a​r​ ​s​o​m​e​ ​s​t​o​r​a​g​e​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	callback_errorStorageQuotaExceeded: string
	/**
	 * B​a​c​k​ ​t​o​ ​h​o​m​e
	 */
	common_backToHome: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	admin_sidebar_dashboard: string
	/**
	 * U​s​e​r​s
	 */
	admin_sidebar_users: string
	/**
	 * C​l​i​e​n​t​s
	 */
	admin_sidebar_clients: string
	/**
	 * S​e​s​s​i​o​n​s
	 */
	admin_sidebar_sessions: string
	/**
	 * A​u​d​i​t​ ​L​o​g
	 */
	admin_sidebar_audit_log: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	admin_sidebar_settings: string
	/**
	 * S​C​I​M​ ​T​o​k​e​n​s
	 */
	admin_sidebar_scim_tokens: string
	/**
	 * I​d​e​n​t​i​t​y​ ​P​r​o​v​i​d​e​r​s
	 */
	admin_sidebar_identity_providers: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	admin_dashboard_title: string
	/**
	 * A​c​t​i​v​e​ ​U​s​e​r​s
	 */
	admin_dashboard_activeUsers: string
	/**
	 * T​o​t​a​l​ ​U​s​e​r​s
	 */
	admin_dashboard_totalUsers: string
	/**
	 * O​A​u​t​h​ ​C​l​i​e​n​t​s
	 */
	admin_dashboard_clients: string
	/**
	 * T​o​d​a​y​'​s​ ​L​o​g​i​n​s
	 */
	admin_dashboard_todayLogins: string
	/**
	 * R​e​c​e​n​t​ ​A​c​t​i​v​i​t​y
	 */
	admin_dashboard_recentActivity: string
	/**
	 * U​s​e​r​ ​M​a​n​a​g​e​m​e​n​t
	 */
	admin_users_title: string
	/**
	 * S​e​a​r​c​h​ ​b​y​ ​e​m​a​i​l​ ​o​r​ ​n​a​m​e
	 */
	admin_users_search: string
	/**
	 * A​d​d​ ​U​s​e​r
	 */
	admin_users_addUser: string
	/**
	 * F​i​l​t​e​r
	 */
	admin_users_filter: string
	/**
	 * A​l​l
	 */
	admin_users_all: string
	/**
	 * V​e​r​i​f​i​e​d
	 */
	admin_users_verified: string
	/**
	 * U​n​v​e​r​i​f​i​e​d
	 */
	admin_users_unverified: string
	/**
	 * E​m​a​i​l
	 */
	admin_users_email: string
	/**
	 * N​a​m​e
	 */
	admin_users_name: string
	/**
	 * S​t​a​t​u​s
	 */
	admin_users_status: string
	/**
	 * C​r​e​a​t​e​d
	 */
	admin_users_created: string
	/**
	 * L​a​s​t​ ​L​o​g​i​n
	 */
	admin_users_lastLogin: string
	/**
	 * A​c​t​i​o​n​s
	 */
	admin_users_actions: string
	/**
	 * E​d​i​t
	 */
	admin_users_edit: string
	/**
	 * D​e​l​e​t​e
	 */
	admin_users_delete: string
	/**
	 * V​i​e​w
	 */
	admin_users_view: string
	/**
	 * U​s​e​r​ ​D​e​t​a​i​l​s
	 */
	admin_user_detail_title: string
	/**
	 * B​a​s​i​c​ ​I​n​f​o​r​m​a​t​i​o​n
	 */
	admin_user_detail_basicInfo: string
	/**
	 * C​u​s​t​o​m​ ​F​i​e​l​d​s
	 */
	admin_user_detail_customFields: string
	/**
	 * R​e​g​i​s​t​e​r​e​d​ ​P​a​s​s​k​e​y​s
	 */
	admin_user_detail_passkeys: string
	/**
	 * A​c​t​i​v​e​ ​S​e​s​s​i​o​n​s
	 */
	admin_user_detail_sessions: string
	/**
	 * S​a​v​e​ ​C​h​a​n​g​e​s
	 */
	admin_user_detail_save: string
	/**
	 * D​e​l​e​t​e​ ​U​s​e​r
	 */
	admin_user_detail_deleteUser: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​u​s​e​r​?
	 */
	admin_user_detail_deleteConfirm: string
	/**
	 * C​l​i​e​n​t​ ​M​a​n​a​g​e​m​e​n​t
	 */
	admin_clients_title: string
	/**
	 * S​e​a​r​c​h​ ​b​y​ ​c​l​i​e​n​t​ ​n​a​m​e​ ​o​r​ ​I​D
	 */
	admin_clients_search: string
	/**
	 * R​e​g​i​s​t​e​r​ ​C​l​i​e​n​t
	 */
	admin_clients_registerClient: string
	/**
	 * C​l​i​e​n​t​ ​I​D
	 */
	admin_clients_clientId: string
	/**
	 * C​l​i​e​n​t​ ​N​a​m​e
	 */
	admin_clients_clientName: string
	/**
	 * G​r​a​n​t​ ​T​y​p​e​s
	 */
	admin_clients_grantTypes: string
	/**
	 * C​r​e​a​t​e​d
	 */
	admin_clients_created: string
	/**
	 * A​c​t​i​o​n​s
	 */
	admin_clients_actions: string
	/**
	 * C​l​i​e​n​t​ ​D​e​t​a​i​l​s
	 */
	admin_client_detail_title: string
	/**
	 * B​a​s​i​c​ ​I​n​f​o​r​m​a​t​i​o​n
	 */
	admin_client_detail_basicInfo: string
	/**
	 * R​e​d​i​r​e​c​t​ ​U​R​I​s
	 */
	admin_client_detail_redirectUris: string
	/**
	 * G​r​a​n​t​ ​T​y​p​e​s
	 */
	admin_client_detail_grantTypes: string
	/**
	 * S​c​o​p​e​s
	 */
	admin_client_detail_scopes: string
	/**
	 * S​a​v​e​ ​C​h​a​n​g​e​s
	 */
	admin_client_detail_save: string
	/**
	 * R​e​g​e​n​e​r​a​t​e​ ​S​e​c​r​e​t
	 */
	admin_client_detail_regenerateSecret: string
	/**
	 * D​e​l​e​t​e​ ​C​l​i​e​n​t
	 */
	admin_client_detail_deleteClient: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	admin_settings_title: string
	/**
	 * G​e​n​e​r​a​l
	 */
	admin_settings_general: string
	/**
	 * A​p​p​e​a​r​a​n​c​e
	 */
	admin_settings_appearance: string
	/**
	 * S​e​c​u​r​i​t​y
	 */
	admin_settings_security: string
	/**
	 * E​m​a​i​l
	 */
	admin_settings_email: string
	/**
	 * A​d​v​a​n​c​e​d
	 */
	admin_settings_advanced: string
	/**
	 * A​u​d​i​t​ ​L​o​g
	 */
	admin_audit_title: string
	/**
	 * T​i​m​e​s​t​a​m​p
	 */
	admin_audit_timestamp: string
	/**
	 * U​s​e​r
	 */
	admin_audit_user: string
	/**
	 * A​c​t​i​o​n
	 */
	admin_audit_action: string
	/**
	 * R​e​s​o​u​r​c​e
	 */
	admin_audit_resource: string
	/**
	 * I​P​ ​A​d​d​r​e​s​s
	 */
	admin_audit_ip: string
	/**
	 * S​t​a​t​u​s
	 */
	admin_audit_status: string
	/**
	 * E​x​p​o​r​t
	 */
	admin_audit_export: string
	/**
	 * P​o​l​i​c​y
	 */
	admin_sidebar_policy: string
	/**
	 * P​o​l​i​c​y​ ​S​e​t​t​i​n​g​s
	 */
	admin_policy_title: string
	/**
	 * C​o​n​f​i​g​u​r​e​ ​p​o​l​i​c​y​ ​s​y​s​t​e​m​ ​f​e​a​t​u​r​e​s​ ​a​n​d​ ​t​o​k​e​n​ ​c​l​a​i​m​s
	 */
	admin_policy_subtitle: string
	/**
	 * S​a​v​e​ ​C​h​a​n​g​e​s
	 */
	admin_policy_save: string
	/**
	 * P​o​l​i​c​y​ ​s​e​t​t​i​n​g​s​ ​s​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	admin_policy_save_success: string
	/**
	 * O​I​D​C​ ​C​o​n​f​o​r​m​a​n​c​e​ ​N​o​t​i​c​e
	 */
	admin_policy_warning_title: string
	/**
	 * E​n​a​b​l​i​n​g​ ​p​o​l​i​c​y​ ​f​e​a​t​u​r​e​s​ ​m​a​y​ ​a​f​f​e​c​t​ ​O​I​D​C​ ​c​o​n​f​o​r​m​a​n​c​e​ ​t​e​s​t​i​n​g​.​ ​C​u​s​t​o​m​ ​c​l​a​i​m​s​ ​u​s​e​ ​t​h​e​ ​"​a​u​t​h​r​i​m​_​"​ ​p​r​e​f​i​x​ ​t​o​ ​a​v​o​i​d​ ​c​o​n​f​l​i​c​t​s​ ​w​i​t​h​ ​s​t​a​n​d​a​r​d​ ​c​l​a​i​m​s​.
	 */
	admin_policy_warning_desc: string
	/**
	 * F​e​a​t​u​r​e​ ​F​l​a​g​s
	 */
	admin_policy_feature_flags: string
	/**
	 * E​n​a​b​l​e​ ​A​B​A​C​ ​(​A​t​t​r​i​b​u​t​e​-​B​a​s​e​d​ ​A​c​c​e​s​s​ ​C​o​n​t​r​o​l​)
	 */
	admin_policy_enable_abac: string
	/**
	 * E​v​a​l​u​a​t​e​ ​a​c​c​e​s​s​ ​b​a​s​e​d​ ​o​n​ ​u​s​e​r​ ​a​t​t​r​i​b​u​t​e​s​ ​(​d​e​p​a​r​t​m​e​n​t​,​ ​c​l​e​a​r​a​n​c​e​ ​l​e​v​e​l​,​ ​e​t​c​.​)
	 */
	admin_policy_enable_abac_desc: string
	/**
	 * E​n​a​b​l​e​ ​R​e​B​A​C​ ​(​R​e​l​a​t​i​o​n​s​h​i​p​-​B​a​s​e​d​ ​A​c​c​e​s​s​ ​C​o​n​t​r​o​l​)
	 */
	admin_policy_enable_rebac: string
	/**
	 * E​v​a​l​u​a​t​e​ ​a​c​c​e​s​s​ ​b​a​s​e​d​ ​o​n​ ​r​e​l​a​t​i​o​n​s​h​i​p​s​ ​b​e​t​w​e​e​n​ ​e​n​t​i​t​i​e​s​ ​(​G​o​o​g​l​e​ ​Z​a​n​z​i​b​a​r​ ​s​t​y​l​e​)
	 */
	admin_policy_enable_rebac_desc: string
	/**
	 * E​n​a​b​l​e​ ​P​o​l​i​c​y​ ​L​o​g​g​i​n​g
	 */
	admin_policy_enable_logging: string
	/**
	 * L​o​g​ ​d​e​t​a​i​l​e​d​ ​p​o​l​i​c​y​ ​e​v​a​l​u​a​t​i​o​n​ ​r​e​s​u​l​t​s​ ​f​o​r​ ​d​e​b​u​g​g​i​n​g
	 */
	admin_policy_enable_logging_desc: string
	/**
	 * E​n​a​b​l​e​ ​V​e​r​i​f​i​e​d​ ​A​t​t​r​i​b​u​t​e​s
	 */
	admin_policy_enable_verified_attrs: string
	/**
	 * R​e​q​u​i​r​e​ ​c​r​y​p​t​o​g​r​a​p​h​i​c​ ​p​r​o​o​f​ ​o​f​ ​a​t​t​r​i​b​u​t​e​ ​c​l​a​i​m​s
	 */
	admin_policy_enable_verified_attrs_desc: string
	/**
	 * E​n​a​b​l​e​ ​C​u​s​t​o​m​ ​R​u​l​e​s
	 */
	admin_policy_enable_custom_rules: string
	/**
	 * A​l​l​o​w​ ​c​u​s​t​o​m​ ​p​o​l​i​c​y​ ​r​u​l​e​s​ ​b​e​y​o​n​d​ ​d​e​f​a​u​l​t​ ​R​B​A​C
	 */
	admin_policy_enable_custom_rules_desc: string
	/**
	 * E​n​a​b​l​e​ ​S​D​-​J​W​T​ ​(​S​e​l​e​c​t​i​v​e​ ​D​i​s​c​l​o​s​u​r​e​)
	 */
	admin_policy_enable_sd_jwt: string
	/**
	 * I​s​s​u​e​ ​I​D​ ​T​o​k​e​n​s​ ​i​n​ ​S​D​-​J​W​T​ ​f​o​r​m​a​t​ ​f​o​r​ ​s​e​l​e​c​t​i​v​e​ ​d​i​s​c​l​o​s​u​r​e​ ​(​R​F​C​ ​9​9​0​1​)
	 */
	admin_policy_enable_sd_jwt_desc: string
	/**
	 * E​n​a​b​l​e​ ​P​o​l​i​c​y​ ​E​m​b​e​d​d​i​n​g​ ​i​n​ ​A​c​c​e​s​s​ ​T​o​k​e​n
	 */
	admin_policy_enable_embedding: string
	/**
	 * E​v​a​l​u​a​t​e​ ​r​e​q​u​e​s​t​e​d​ ​s​c​o​p​e​s​ ​a​g​a​i​n​s​t​ ​p​o​l​i​c​y​ ​a​n​d​ ​e​m​b​e​d​ ​p​e​r​m​i​t​t​e​d​ ​a​c​t​i​o​n​s​ ​a​s​ ​a​u​t​h​r​i​m​_​p​e​r​m​i​s​s​i​o​n​s​ ​c​l​a​i​m
	 */
	admin_policy_enable_embedding_desc: string
	/**
	 * T​o​k​e​n​ ​C​l​a​i​m​s​ ​C​o​n​f​i​g​u​r​a​t​i​o​n
	 */
	admin_policy_token_claims: string
	/**
	 * A​c​c​e​s​s​ ​T​o​k​e​n​ ​C​l​a​i​m​s
	 */
	admin_policy_access_token_claims: string
	/**
	 * C​o​m​m​a​-​s​e​p​a​r​a​t​e​d​ ​l​i​s​t​ ​o​f​ ​c​l​a​i​m​s​ ​t​o​ ​i​n​c​l​u​d​e​ ​i​n​ ​A​c​c​e​s​s​ ​T​o​k​e​n​ ​(​p​r​e​f​i​x​e​d​ ​w​i​t​h​ ​a​u​t​h​r​i​m​_​)
	 */
	admin_policy_access_token_claims_desc: string
	/**
	 * I​D​ ​T​o​k​e​n​ ​C​l​a​i​m​s
	 */
	admin_policy_id_token_claims: string
	/**
	 * C​o​m​m​a​-​s​e​p​a​r​a​t​e​d​ ​l​i​s​t​ ​o​f​ ​c​l​a​i​m​s​ ​t​o​ ​i​n​c​l​u​d​e​ ​i​n​ ​I​D​ ​T​o​k​e​n​ ​(​p​r​e​f​i​x​e​d​ ​w​i​t​h​ ​a​u​t​h​r​i​m​_​)
	 */
	admin_policy_id_token_claims_desc: string
	/**
	 * A​v​a​i​l​a​b​l​e​ ​C​l​a​i​m​s
	 */
	admin_policy_available_claims: string
	/**
	 * P​o​l​i​c​y​ ​E​m​b​e​d​d​i​n​g​ ​I​n​f​o​r​m​a​t​i​o​n
	 */
	admin_policy_embedding_info: string
	/**
	 * W​h​e​n​ ​e​n​a​b​l​e​d​,​ ​t​h​e​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​s​e​r​v​e​r​ ​e​v​a​l​u​a​t​e​s​ ​r​e​q​u​e​s​t​e​d​ ​s​c​o​p​e​s​ ​a​g​a​i​n​s​t​ ​t​h​e​ ​u​s​e​r​'​s​ ​p​e​r​m​i​s​s​i​o​n​s​ ​a​n​d​ ​e​m​b​e​d​s​ ​o​n​l​y​ ​p​e​r​m​i​t​t​e​d​ ​a​c​t​i​o​n​s​ ​i​n​ ​t​h​e​ ​A​c​c​e​s​s​ ​T​o​k​e​n​.
	 */
	admin_policy_embedding_info_desc: string
	/**
	 * A​c​c​o​u​n​t​ ​A​l​r​e​a​d​y​ ​E​x​i​s​t​s
	 */
	login_extError_accountExists_title: string
	/**
	 * A​n​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​e​m​a​i​l​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.​ ​P​l​e​a​s​e​ ​l​o​g​ ​i​n​ ​w​i​t​h​ ​y​o​u​r​ ​e​x​i​s​t​i​n​g​ ​c​r​e​d​e​n​t​i​a​l​s​ ​f​i​r​s​t​.
	 */
	login_extError_accountExists_message: string
	/**
	 * A​f​t​e​r​ ​l​o​g​g​i​n​g​ ​i​n​,​ ​y​o​u​ ​c​a​n​ ​l​i​n​k​ ​y​o​u​r​ ​e​x​t​e​r​n​a​l​ ​a​c​c​o​u​n​t​ ​f​r​o​m​ ​t​h​e​ ​s​e​t​t​i​n​g​s​ ​p​a​g​e​.
	 */
	login_extError_accountExists_action: string
	/**
	 * E​m​a​i​l​ ​N​o​t​ ​V​e​r​i​f​i​e​d
	 */
	login_extError_emailNotVerified_title: string
	/**
	 * T​h​e​ ​e​m​a​i​l​ ​f​r​o​m​ ​y​o​u​r​ ​e​x​t​e​r​n​a​l​ ​a​c​c​o​u​n​t​ ​i​s​ ​n​o​t​ ​v​e​r​i​f​i​e​d​.​ ​P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​w​i​t​h​ ​t​h​e​ ​p​r​o​v​i​d​e​r​ ​f​i​r​s​t​.
	 */
	login_extError_emailNotVerified_message: string
	/**
	 * V​e​r​i​f​y​ ​Y​o​u​r​ ​E​m​a​i​l
	 */
	login_extError_localEmailNotVerified_title: string
	/**
	 * Y​o​u​r​ ​e​x​i​s​t​i​n​g​ ​a​c​c​o​u​n​t​ ​e​m​a​i​l​ ​i​s​ ​n​o​t​ ​v​e​r​i​f​i​e​d​.​ ​P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​f​i​r​s​t​ ​b​e​f​o​r​e​ ​l​i​n​k​i​n​g​ ​e​x​t​e​r​n​a​l​ ​a​c​c​o​u​n​t​s​.
	 */
	login_extError_localEmailNotVerified_message: string
	/**
	 * R​e​g​i​s​t​r​a​t​i​o​n​ ​N​o​t​ ​A​v​a​i​l​a​b​l​e
	 */
	login_extError_jitDisabled_title: string
	/**
	 * N​e​w​ ​a​c​c​o​u​n​t​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​v​i​a​ ​e​x​t​e​r​n​a​l​ ​p​r​o​v​i​d​e​r​s​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​.​ ​P​l​e​a​s​e​ ​r​e​g​i​s​t​e​r​ ​w​i​t​h​ ​e​m​a​i​l​ ​f​i​r​s​t​ ​o​r​ ​c​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
	 */
	login_extError_jitDisabled_message: string
	/**
	 * N​o​ ​A​c​c​o​u​n​t​ ​F​o​u​n​d
	 */
	login_extError_noAccount_title: string
	/**
	 * N​o​ ​a​c​c​o​u​n​t​ ​w​a​s​ ​f​o​u​n​d​.​ ​P​l​e​a​s​e​ ​r​e​g​i​s​t​e​r​ ​f​i​r​s​t​.
	 */
	login_extError_noAccount_message: string
	/**
	 * P​r​o​v​i​d​e​r​ ​E​r​r​o​r
	 */
	login_extError_providerError_title: string
	/**
	 * T​h​e​ ​e​x​t​e​r​n​a​l​ ​p​r​o​v​i​d​e​r​ ​r​e​t​u​r​n​e​d​ ​a​n​ ​e​r​r​o​r​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​.
	 */
	login_extError_providerError_message: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​F​a​i​l​e​d
	 */
	login_extError_callbackFailed_title: string
	/**
	 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​d​u​r​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	login_extError_callbackFailed_message: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​E​r​r​o​r
	 */
	login_extError_default_title: string
	/**
	 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​d​u​r​i​n​g​ ​e​x​t​e​r​n​a​l​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.
	 */
	login_extError_default_message: string
	/**
	 * S​i​g​n​i​n​g​ ​i​n​ ​t​o
	 */
	login_signingInTo: string
	/**
	 * C​o​n​t​a​c​t​ ​S​u​p​p​o​r​t
	 */
	common_contactSupport: string
	/**
	 * D​i​s​m​i​s​s​ ​a​l​e​r​t
	 */
	common_dismissAlert: string
	/**
	 * D​i​g​i​t​ ​{​p​o​s​i​t​i​o​n​}​ ​o​f​ ​6
	 * @param {number} position
	 */
	emailCode_digitLabel: RequiredParams<'position'>
}

export type TranslationFunctions = {
	/**
	 * Authrim
	 */
	app_title: () => LocalizedString
	/**
	 * OpenID Connect Provider on Cloudflare Workers
	 */
	app_subtitle: () => LocalizedString
	/**
	 * Frontend Stack Test
	 */
	test_title: () => LocalizedString
	/**
	 * Test Melt UI (Headless Components):
	 */
	test_meltui: () => LocalizedString
	/**
	 * Primary Button
	 */
	button_primary: () => LocalizedString
	/**
	 * Secondary Button
	 */
	button_secondary: () => LocalizedString
	/**
	 * Ghost Button
	 */
	button_ghost: () => LocalizedString
	/**
	 * Open Dialog
	 */
	button_openDialog: () => LocalizedString
	/**
	 * Email address
	 */
	form_email: () => LocalizedString
	/**
	 * you@example.com
	 */
	form_emailPlaceholder: () => LocalizedString
	/**
	 * Success
	 */
	badge_success: () => LocalizedString
	/**
	 * Warning
	 */
	badge_warning: () => LocalizedString
	/**
	 * Error
	 */
	badge_error: () => LocalizedString
	/**
	 * Info
	 */
	badge_info: () => LocalizedString
	/**
	 * Melt UI Dialog
	 */
	dialog_title: () => LocalizedString
	/**
	 * This is a test dialog using Melt UI, a headless, accessible component library for Svelte.
	 */
	dialog_description: () => LocalizedString
	/**
	 * Cancel
	 */
	dialog_cancel: () => LocalizedString
	/**
	 * Confirm
	 */
	dialog_confirm: () => LocalizedString
	/**
	 * Close
	 */
	dialog_close: () => LocalizedString
	/**
	 * SvelteKit v5 + UnoCSS + Melt UI + Cloudflare Pages
	 */
	footer_stack: () => LocalizedString
	/**
	 * Switch Language
	 */
	language_switch: () => LocalizedString
	/**
	 * English
	 */
	language_english: () => LocalizedString
	/**
	 * Japanese
	 */
	language_japanese: () => LocalizedString
	/**
	 * Email address
	 */
	common_email: () => LocalizedString
	/**
	 * you@example.com
	 */
	common_emailPlaceholder: () => LocalizedString
	/**
	 * Full name
	 */
	common_name: () => LocalizedString
	/**
	 * John Doe
	 */
	common_namePlaceholder: () => LocalizedString
	/**
	 * Continue
	 */
	common_continue: () => LocalizedString
	/**
	 * Cancel
	 */
	common_cancel: () => LocalizedString
	/**
	 * Back to login
	 */
	common_backToLogin: () => LocalizedString
	/**
	 * or
	 */
	common_or: () => LocalizedString
	/**
	 * Loading...
	 */
	common_loading: () => LocalizedString
	/**
	 * Welcome back
	 */
	login_title: () => LocalizedString
	/**
	 * Sign in to your account
	 */
	login_subtitle: () => LocalizedString
	/**
	 * Continue with Passkey
	 */
	login_continueWithPasskey: () => LocalizedString
	/**
	 * Sign in with Passkey
	 */
	login_signInWithPasskey: () => LocalizedString
	/**
	 * Send verification code
	 */
	login_sendCode: () => LocalizedString
	/**
	 * Don't have an account? Create one
	 */
	login_createAccount: () => LocalizedString
	/**
	 * Email address is required
	 */
	login_errorEmailRequired: () => LocalizedString
	/**
	 * Please enter a valid email address
	 */
	login_errorEmailInvalid: () => LocalizedString
	/**
	 * Or continue with
	 */
	login_orContinueWith: () => LocalizedString
	/**
	 * Continue with {provider}
	 */
	login_continueWith: (arg: { provider: string }) => LocalizedString
	/**
	 * Tenant Discovery
	 */
	discover_pageTitle: () => LocalizedString
	/**
	 * Tenant discovery
	 */
	discover_kicker: () => LocalizedString
	/**
	 * Find your tenant
	 */
	discover_title: () => LocalizedString
	/**
	 * Resolve the correct tenant first. Authentication methods are loaded after the tenant is confirmed.
	 */
	discover_subtitle: () => LocalizedString
	/**
	 * This entry point is disabled for this tenant. Use the tenant-specific login URL instead.
	 */
	discover_notice_disabled: () => LocalizedString
	/**
	 * Automatic tenant discovery is disabled. Enter your tenant code or tenant slug to continue.
	 */
	discover_notice_manualOnly: () => LocalizedString
	/**
	 * Recent tenant
	 */
	discover_recentTenant: () => LocalizedString
	/**
	 * Discovery method
	 */
	discover_methodLabel: () => LocalizedString
	/**
	 * Email address
	 */
	discover_method_email: () => LocalizedString
	/**
	 * Tenant code
	 */
	discover_method_tenantCode: () => LocalizedString
	/**
	 * Tenant slug
	 */
	discover_method_tenantSlug: () => LocalizedString
	/**
	 * you@example.com
	 */
	discover_placeholder_email: () => LocalizedString
	/**
	 * acme
	 */
	discover_placeholder_tenantCode: () => LocalizedString
	/**
	 * acme-corp
	 */
	discover_placeholder_tenantSlug: () => LocalizedString
	/**
	 * Select a tenant
	 */
	discover_selectTenant: () => LocalizedString
	/**
	 * No account matched that email address.
	 */
	discover_error_emailNotFound: () => LocalizedString
	/**
	 * This email domain is not mapped to a tenant.
	 */
	discover_error_emailDomainNotFound: () => LocalizedString
	/**
	 * No tenant matched that tenant code.
	 */
	discover_error_tenantCodeNotFound: () => LocalizedString
	/**
	 * No tenant matched that tenant slug.
	 */
	discover_error_tenantSlugNotFound: () => LocalizedString
	/**
	 * This invitation is invalid or has expired.
	 */
	discover_error_invitationNotFound: () => LocalizedString
	/**
	 * No tenant matched that application hint.
	 */
	discover_error_appHintNotFound: () => LocalizedString
	/**
	 * No tenant could be resolved.
	 */
	discover_error_notFound: () => LocalizedString
	/**
	 * A value is required.
	 */
	discover_error_valueRequired: () => LocalizedString
	/**
	 * Tenant could not be resolved automatically. Enter your tenant code or tenant slug to continue.
	 */
	discover_error_manualRequired: () => LocalizedString
	/**
	 * The invitation could not be resolved.
	 */
	discover_error_invitationUnresolved: () => LocalizedString
	/**
	 * Failed to resolve tenant
	 */
	discover_error_resolveFailed: () => LocalizedString
	/**
	 * Sign Up
	 */
	header_signUp: () => LocalizedString
	/**
	 * Login
	 */
	header_login: () => LocalizedString
	/**
	 * Logout
	 */
	header_logout: () => LocalizedString
	/**
	 * Create your account
	 */
	register_title: () => LocalizedString
	/**
	 * Get started with Authrim
	 */
	register_subtitle: () => LocalizedString
	/**
	 * Create Account with Passkey
	 */
	register_createWithPasskey: () => LocalizedString
	/**
	 * Sign up with verification code
	 */
	register_sendCode: () => LocalizedString
	/**
	 * Already have an account? Sign in
	 */
	register_alreadyHaveAccount: () => LocalizedString
	/**
	 * By creating an account, you agree to our Terms of Service and Privacy Policy
	 */
	register_termsAgreement: () => LocalizedString
	/**
	 * Name is required
	 */
	register_errorNameRequired: () => LocalizedString
	/**
	 * Check your email
	 */
	emailCode_title: () => LocalizedString
	/**
	 * We've sent a verification code to
	 */
	emailCode_subtitle: () => LocalizedString
	/**
	 * Enter the 6-digit code from your email. The code will expire in 5 minutes.
	 */
	emailCode_instructions: () => LocalizedString
	/**
	 * Verification Code
	 */
	emailCode_codeLabel: () => LocalizedString
	/**
	 * Verify
	 */
	emailCode_verifyButton: () => LocalizedString
	/**
	 * Resend code
	 */
	emailCode_resendButton: () => LocalizedString
	/**
	 * Resend in {seconds}s
	 */
	emailCode_resendTimer: (arg: { seconds: unknown }) => LocalizedString
	/**
	 * Code sent successfully
	 */
	emailCode_resendSuccess: () => LocalizedString
	/**
	 * Verification successful! Redirecting...
	 */
	emailCode_success: () => LocalizedString
	/**
	 * Invalid or expired code
	 */
	emailCode_errorInvalid: () => LocalizedString
	/**
	 * Session mismatch. Please request a new code.
	 */
	emailCode_errorSessionMismatch: () => LocalizedString
	/**
	 * {clientName} wants to access your account
	 */
	consent_title: (arg: { clientName: string }) => LocalizedString
	/**
	 * This application is requesting access to your Authrim account
	 */
	consent_subtitle: () => LocalizedString
	/**
	 * This application will be able to:
	 */
	consent_scopesTitle: () => LocalizedString
	/**
	 * You are signed in as
	 */
	consent_userInfo: () => LocalizedString
	/**
	 * Not you? Switch account
	 */
	consent_notYou: () => LocalizedString
	/**
	 * Allow
	 */
	consent_allowButton: () => LocalizedString
	/**
	 * Deny
	 */
	consent_denyButton: () => LocalizedString
	/**
	 * Privacy Policy
	 */
	consent_privacyPolicy: () => LocalizedString
	/**
	 * Terms of Service
	 */
	consent_termsOfService: () => LocalizedString
	/**
	 * Verify your identity
	 */
	consent_scope_openid: () => LocalizedString
	/**
	 * View your profile information (name, picture)
	 */
	consent_scope_profile: () => LocalizedString
	/**
	 * View your email address
	 */
	consent_scope_email: () => LocalizedString
	/**
	 * View your phone number
	 */
	consent_scope_phone: () => LocalizedString
	/**
	 * View your address
	 */
	consent_scope_address: () => LocalizedString
	/**
	 * Maintain access when you're not using the app
	 */
	consent_scope_offline_access: () => LocalizedString
	/**
	 * Select organization
	 */
	consent_organizationSelect: () => LocalizedString
	/**
	 * Primary
	 */
	consent_primaryOrg: () => LocalizedString
	/**
	 * Current organization
	 */
	consent_currentOrganization: () => LocalizedString
	/**
	 * Acting on behalf of {name}
	 */
	consent_actingOnBehalfOf: (arg: { name: string }) => LocalizedString
	/**
	 * Delegated Access
	 */
	consent_delegatedAccess: () => LocalizedString
	/**
	 * You are authorizing this application to access {name}'s account on their behalf
	 */
	consent_delegatedAccessWarning: (arg: { name: unknown }) => LocalizedString
	/**
	 * Your roles
	 */
	consent_yourRoles: () => LocalizedString
	/**
	 * No organization
	 */
	consent_noOrganization: () => LocalizedString
	/**
	 * Trusted application
	 */
	consent_trustedClient: () => LocalizedString
	/**
	 * Required consents
	 */
	consent_items_required_title: () => LocalizedString
	/**
	 * Optional consents
	 */
	consent_items_optional_title: () => LocalizedString
	/**
	 * View document
	 */
	consent_item_view_document: () => LocalizedString
	/**
	 * {oldVersion} → {newVersion} updated
	 */
	consent_item_version_updated: (arg: { newVersion: string, oldVersion: string }) => LocalizedString
	/**
	 * Required
	 */
	consent_item_required_badge: () => LocalizedString
	/**
	 * Optional
	 */
	consent_item_optional_badge: () => LocalizedString
	/**
	 * Request account deletion
	 */
	consent_delete_account_link: () => LocalizedString
	/**
	 * You must agree to all required consent items to continue. If you do not agree, you may request account deletion.
	 */
	consent_block_message: () => LocalizedString
	/**
	 * Oops! Something went wrong
	 */
	error_title: () => LocalizedString
	/**
	 * We encountered an error while processing your request
	 */
	error_subtitle: () => LocalizedString
	/**
	 * If this problem persists, please contact support
	 */
	error_contactSupport: () => LocalizedString
	/**
	 * Error code
	 */
	error_errorCode: () => LocalizedString
	/**
	 * The request is missing a required parameter or is otherwise malformed
	 */
	error_invalid_request: () => LocalizedString
	/**
	 * You denied the authorization request
	 */
	error_access_denied: () => LocalizedString
	/**
	 * The client is not authorized to request an authorization code
	 */
	error_unauthorized_client: () => LocalizedString
	/**
	 * The authorization server does not support this response type
	 */
	error_unsupported_response_type: () => LocalizedString
	/**
	 * The requested scope is invalid, unknown, or malformed
	 */
	error_invalid_scope: () => LocalizedString
	/**
	 * The authorization server encountered an unexpected error
	 */
	error_server_error: () => LocalizedString
	/**
	 * The authorization server is temporarily unable to handle the request
	 */
	error_temporarily_unavailable: () => LocalizedString
	/**
	 * Authentication required. Please sign in to continue.
	 */
	error_login_required: () => LocalizedString
	/**
	 * An unknown error occurred
	 */
	error_unknown: () => LocalizedString
	/**
	 * Device Verification
	 */
	device_title: () => LocalizedString
	/**
	 * Enter the code shown on your device
	 */
	device_subtitle: () => LocalizedString
	/**
	 * Enter the 8-character code displayed on your device to authorize it
	 */
	device_instructions: () => LocalizedString
	/**
	 * Scan this QR code
	 */
	device_qrCodeLabel: () => LocalizedString
	/**
	 * or enter code manually
	 */
	device_orManual: () => LocalizedString
	/**
	 * Verification Code
	 */
	device_codeLabel: () => LocalizedString
	/**
	 * XXXX-XXXX
	 */
	device_codePlaceholder: () => LocalizedString
	/**
	 * Enter the 8-character code from your device (format: XXXX-XXXX)
	 */
	device_codeHint: () => LocalizedString
	/**
	 * Verify Code
	 */
	device_verifyButton: () => LocalizedString
	/**
	 * Authorize Device
	 */
	device_confirmTitle: () => LocalizedString
	/**
	 * Device authorized successfully! You can close this window.
	 */
	device_successMessage: () => LocalizedString
	/**
	 * Requested permissions
	 */
	device_requestedPermissions: () => LocalizedString
	/**
	 * Approve
	 */
	device_approveButton: () => LocalizedString
	/**
	 * Deny
	 */
	device_denyButton: () => LocalizedString
	/**
	 * Device authorized successfully! You can now close this window.
	 */
	device_success: () => LocalizedString
	/**
	 * Device authorization denied
	 */
	device_denied: () => LocalizedString
	/**
	 * Invalid or expired verification code
	 */
	device_errorInvalidCode: () => LocalizedString
	/**
	 * This code has already been used
	 */
	device_errorAlreadyUsed: () => LocalizedString
	/**
	 * Verification failed. Please try again.
	 */
	device_errorGeneric: () => LocalizedString
	/**
	 * Please enter the verification code
	 */
	device_errorCodeRequired: () => LocalizedString
	/**
	 * Authentication Request
	 */
	ciba_title: () => LocalizedString
	/**
	 * An application is requesting your approval
	 */
	ciba_subtitle: () => LocalizedString
	/**
	 * No pending authentication requests
	 */
	ciba_noPendingRequests: () => LocalizedString
	/**
	 * Verification message
	 */
	ciba_bindingMessage: () => LocalizedString
	/**
	 * Requested permissions
	 */
	ciba_requestedPermissions: () => LocalizedString
	/**
	 * Approve
	 */
	ciba_approveButton: () => LocalizedString
	/**
	 * Reject
	 */
	ciba_rejectButton: () => LocalizedString
	/**
	 * Request approved successfully
	 */
	ciba_approvedSuccess: () => LocalizedString
	/**
	 * Request rejected
	 */
	ciba_rejectedSuccess: () => LocalizedString
	/**
	 * Expired
	 */
	ciba_expired: () => LocalizedString
	/**
	 * {minutes}m {seconds}s remaining
	 */
	ciba_remainingMinutes: (arg: { minutes: number, seconds: number }) => LocalizedString
	/**
	 * {seconds}s remaining
	 */
	ciba_remainingSeconds: (arg: { seconds: number }) => LocalizedString
	/**
	 * Verify Your Identity
	 */
	reauth_title: () => LocalizedString
	/**
	 * For security, please re-authenticate to continue
	 */
	reauth_subtitle: () => LocalizedString
	/**
	 * Verify with Passkey
	 */
	reauth_verifyWithPasskey: () => LocalizedString
	/**
	 * Verify with Email Code
	 */
	reauth_verifyWithEmailCode: () => LocalizedString
	/**
	 * Signing In
	 */
	callback_title: () => LocalizedString
	/**
	 * Processing authentication...
	 */
	callback_processing: () => LocalizedString
	/**
	 * Please wait while we complete your sign-in.
	 */
	callback_pleaseWait: () => LocalizedString
	/**
	 * Sign-in successful!
	 */
	callback_success: () => LocalizedString
	/**
	 * Redirecting you now...
	 */
	callback_redirecting: () => LocalizedString
	/**
	 * Authentication Failed
	 */
	callback_errorTitle: () => LocalizedString
	/**
	 * No authorization code received. Please try signing in again.
	 */
	callback_errorMissingCode: () => LocalizedString
	/**
	 * Security validation failed. Please try signing in again.
	 */
	callback_errorStateMismatch: () => LocalizedString
	/**
	 * Failed to complete authentication. Please try again.
	 */
	callback_errorExchangeFailed: () => LocalizedString
	/**
	 * A network error occurred. Please check your connection and try again.
	 */
	callback_errorNetwork: () => LocalizedString
	/**
	 * Authentication failed. Please try logging in again.
	 */
	callback_errorMissingCodeVerifier: () => LocalizedString
	/**
	 * Your browser settings prevent authentication. Please enable cookies and storage.
	 */
	callback_errorStorageUnavailable: () => LocalizedString
	/**
	 * Your browser storage is full. Please clear some storage and try again.
	 */
	callback_errorStorageQuotaExceeded: () => LocalizedString
	/**
	 * Back to home
	 */
	common_backToHome: () => LocalizedString
	/**
	 * Dashboard
	 */
	admin_sidebar_dashboard: () => LocalizedString
	/**
	 * Users
	 */
	admin_sidebar_users: () => LocalizedString
	/**
	 * Clients
	 */
	admin_sidebar_clients: () => LocalizedString
	/**
	 * Sessions
	 */
	admin_sidebar_sessions: () => LocalizedString
	/**
	 * Audit Log
	 */
	admin_sidebar_audit_log: () => LocalizedString
	/**
	 * Settings
	 */
	admin_sidebar_settings: () => LocalizedString
	/**
	 * SCIM Tokens
	 */
	admin_sidebar_scim_tokens: () => LocalizedString
	/**
	 * Identity Providers
	 */
	admin_sidebar_identity_providers: () => LocalizedString
	/**
	 * Dashboard
	 */
	admin_dashboard_title: () => LocalizedString
	/**
	 * Active Users
	 */
	admin_dashboard_activeUsers: () => LocalizedString
	/**
	 * Total Users
	 */
	admin_dashboard_totalUsers: () => LocalizedString
	/**
	 * OAuth Clients
	 */
	admin_dashboard_clients: () => LocalizedString
	/**
	 * Today's Logins
	 */
	admin_dashboard_todayLogins: () => LocalizedString
	/**
	 * Recent Activity
	 */
	admin_dashboard_recentActivity: () => LocalizedString
	/**
	 * User Management
	 */
	admin_users_title: () => LocalizedString
	/**
	 * Search by email or name
	 */
	admin_users_search: () => LocalizedString
	/**
	 * Add User
	 */
	admin_users_addUser: () => LocalizedString
	/**
	 * Filter
	 */
	admin_users_filter: () => LocalizedString
	/**
	 * All
	 */
	admin_users_all: () => LocalizedString
	/**
	 * Verified
	 */
	admin_users_verified: () => LocalizedString
	/**
	 * Unverified
	 */
	admin_users_unverified: () => LocalizedString
	/**
	 * Email
	 */
	admin_users_email: () => LocalizedString
	/**
	 * Name
	 */
	admin_users_name: () => LocalizedString
	/**
	 * Status
	 */
	admin_users_status: () => LocalizedString
	/**
	 * Created
	 */
	admin_users_created: () => LocalizedString
	/**
	 * Last Login
	 */
	admin_users_lastLogin: () => LocalizedString
	/**
	 * Actions
	 */
	admin_users_actions: () => LocalizedString
	/**
	 * Edit
	 */
	admin_users_edit: () => LocalizedString
	/**
	 * Delete
	 */
	admin_users_delete: () => LocalizedString
	/**
	 * View
	 */
	admin_users_view: () => LocalizedString
	/**
	 * User Details
	 */
	admin_user_detail_title: () => LocalizedString
	/**
	 * Basic Information
	 */
	admin_user_detail_basicInfo: () => LocalizedString
	/**
	 * Custom Fields
	 */
	admin_user_detail_customFields: () => LocalizedString
	/**
	 * Registered Passkeys
	 */
	admin_user_detail_passkeys: () => LocalizedString
	/**
	 * Active Sessions
	 */
	admin_user_detail_sessions: () => LocalizedString
	/**
	 * Save Changes
	 */
	admin_user_detail_save: () => LocalizedString
	/**
	 * Delete User
	 */
	admin_user_detail_deleteUser: () => LocalizedString
	/**
	 * Are you sure you want to delete this user?
	 */
	admin_user_detail_deleteConfirm: () => LocalizedString
	/**
	 * Client Management
	 */
	admin_clients_title: () => LocalizedString
	/**
	 * Search by client name or ID
	 */
	admin_clients_search: () => LocalizedString
	/**
	 * Register Client
	 */
	admin_clients_registerClient: () => LocalizedString
	/**
	 * Client ID
	 */
	admin_clients_clientId: () => LocalizedString
	/**
	 * Client Name
	 */
	admin_clients_clientName: () => LocalizedString
	/**
	 * Grant Types
	 */
	admin_clients_grantTypes: () => LocalizedString
	/**
	 * Created
	 */
	admin_clients_created: () => LocalizedString
	/**
	 * Actions
	 */
	admin_clients_actions: () => LocalizedString
	/**
	 * Client Details
	 */
	admin_client_detail_title: () => LocalizedString
	/**
	 * Basic Information
	 */
	admin_client_detail_basicInfo: () => LocalizedString
	/**
	 * Redirect URIs
	 */
	admin_client_detail_redirectUris: () => LocalizedString
	/**
	 * Grant Types
	 */
	admin_client_detail_grantTypes: () => LocalizedString
	/**
	 * Scopes
	 */
	admin_client_detail_scopes: () => LocalizedString
	/**
	 * Save Changes
	 */
	admin_client_detail_save: () => LocalizedString
	/**
	 * Regenerate Secret
	 */
	admin_client_detail_regenerateSecret: () => LocalizedString
	/**
	 * Delete Client
	 */
	admin_client_detail_deleteClient: () => LocalizedString
	/**
	 * Settings
	 */
	admin_settings_title: () => LocalizedString
	/**
	 * General
	 */
	admin_settings_general: () => LocalizedString
	/**
	 * Appearance
	 */
	admin_settings_appearance: () => LocalizedString
	/**
	 * Security
	 */
	admin_settings_security: () => LocalizedString
	/**
	 * Email
	 */
	admin_settings_email: () => LocalizedString
	/**
	 * Advanced
	 */
	admin_settings_advanced: () => LocalizedString
	/**
	 * Audit Log
	 */
	admin_audit_title: () => LocalizedString
	/**
	 * Timestamp
	 */
	admin_audit_timestamp: () => LocalizedString
	/**
	 * User
	 */
	admin_audit_user: () => LocalizedString
	/**
	 * Action
	 */
	admin_audit_action: () => LocalizedString
	/**
	 * Resource
	 */
	admin_audit_resource: () => LocalizedString
	/**
	 * IP Address
	 */
	admin_audit_ip: () => LocalizedString
	/**
	 * Status
	 */
	admin_audit_status: () => LocalizedString
	/**
	 * Export
	 */
	admin_audit_export: () => LocalizedString
	/**
	 * Policy
	 */
	admin_sidebar_policy: () => LocalizedString
	/**
	 * Policy Settings
	 */
	admin_policy_title: () => LocalizedString
	/**
	 * Configure policy system features and token claims
	 */
	admin_policy_subtitle: () => LocalizedString
	/**
	 * Save Changes
	 */
	admin_policy_save: () => LocalizedString
	/**
	 * Policy settings saved successfully
	 */
	admin_policy_save_success: () => LocalizedString
	/**
	 * OIDC Conformance Notice
	 */
	admin_policy_warning_title: () => LocalizedString
	/**
	 * Enabling policy features may affect OIDC conformance testing. Custom claims use the "authrim_" prefix to avoid conflicts with standard claims.
	 */
	admin_policy_warning_desc: () => LocalizedString
	/**
	 * Feature Flags
	 */
	admin_policy_feature_flags: () => LocalizedString
	/**
	 * Enable ABAC (Attribute-Based Access Control)
	 */
	admin_policy_enable_abac: () => LocalizedString
	/**
	 * Evaluate access based on user attributes (department, clearance level, etc.)
	 */
	admin_policy_enable_abac_desc: () => LocalizedString
	/**
	 * Enable ReBAC (Relationship-Based Access Control)
	 */
	admin_policy_enable_rebac: () => LocalizedString
	/**
	 * Evaluate access based on relationships between entities (Google Zanzibar style)
	 */
	admin_policy_enable_rebac_desc: () => LocalizedString
	/**
	 * Enable Policy Logging
	 */
	admin_policy_enable_logging: () => LocalizedString
	/**
	 * Log detailed policy evaluation results for debugging
	 */
	admin_policy_enable_logging_desc: () => LocalizedString
	/**
	 * Enable Verified Attributes
	 */
	admin_policy_enable_verified_attrs: () => LocalizedString
	/**
	 * Require cryptographic proof of attribute claims
	 */
	admin_policy_enable_verified_attrs_desc: () => LocalizedString
	/**
	 * Enable Custom Rules
	 */
	admin_policy_enable_custom_rules: () => LocalizedString
	/**
	 * Allow custom policy rules beyond default RBAC
	 */
	admin_policy_enable_custom_rules_desc: () => LocalizedString
	/**
	 * Enable SD-JWT (Selective Disclosure)
	 */
	admin_policy_enable_sd_jwt: () => LocalizedString
	/**
	 * Issue ID Tokens in SD-JWT format for selective disclosure (RFC 9901)
	 */
	admin_policy_enable_sd_jwt_desc: () => LocalizedString
	/**
	 * Enable Policy Embedding in Access Token
	 */
	admin_policy_enable_embedding: () => LocalizedString
	/**
	 * Evaluate requested scopes against policy and embed permitted actions as authrim_permissions claim
	 */
	admin_policy_enable_embedding_desc: () => LocalizedString
	/**
	 * Token Claims Configuration
	 */
	admin_policy_token_claims: () => LocalizedString
	/**
	 * Access Token Claims
	 */
	admin_policy_access_token_claims: () => LocalizedString
	/**
	 * Comma-separated list of claims to include in Access Token (prefixed with authrim_)
	 */
	admin_policy_access_token_claims_desc: () => LocalizedString
	/**
	 * ID Token Claims
	 */
	admin_policy_id_token_claims: () => LocalizedString
	/**
	 * Comma-separated list of claims to include in ID Token (prefixed with authrim_)
	 */
	admin_policy_id_token_claims_desc: () => LocalizedString
	/**
	 * Available Claims
	 */
	admin_policy_available_claims: () => LocalizedString
	/**
	 * Policy Embedding Information
	 */
	admin_policy_embedding_info: () => LocalizedString
	/**
	 * When enabled, the authorization server evaluates requested scopes against the user's permissions and embeds only permitted actions in the Access Token.
	 */
	admin_policy_embedding_info_desc: () => LocalizedString
	/**
	 * Account Already Exists
	 */
	login_extError_accountExists_title: () => LocalizedString
	/**
	 * An account with this email already exists. Please log in with your existing credentials first.
	 */
	login_extError_accountExists_message: () => LocalizedString
	/**
	 * After logging in, you can link your external account from the settings page.
	 */
	login_extError_accountExists_action: () => LocalizedString
	/**
	 * Email Not Verified
	 */
	login_extError_emailNotVerified_title: () => LocalizedString
	/**
	 * The email from your external account is not verified. Please verify your email with the provider first.
	 */
	login_extError_emailNotVerified_message: () => LocalizedString
	/**
	 * Verify Your Email
	 */
	login_extError_localEmailNotVerified_title: () => LocalizedString
	/**
	 * Your existing account email is not verified. Please verify your email first before linking external accounts.
	 */
	login_extError_localEmailNotVerified_message: () => LocalizedString
	/**
	 * Registration Not Available
	 */
	login_extError_jitDisabled_title: () => LocalizedString
	/**
	 * New account registration via external providers is not available. Please register with email first or contact your administrator.
	 */
	login_extError_jitDisabled_message: () => LocalizedString
	/**
	 * No Account Found
	 */
	login_extError_noAccount_title: () => LocalizedString
	/**
	 * No account was found. Please register first.
	 */
	login_extError_noAccount_message: () => LocalizedString
	/**
	 * Provider Error
	 */
	login_extError_providerError_title: () => LocalizedString
	/**
	 * The external provider returned an error. Please try again later.
	 */
	login_extError_providerError_message: () => LocalizedString
	/**
	 * Authentication Failed
	 */
	login_extError_callbackFailed_title: () => LocalizedString
	/**
	 * An error occurred during authentication. Please try again.
	 */
	login_extError_callbackFailed_message: () => LocalizedString
	/**
	 * Authentication Error
	 */
	login_extError_default_title: () => LocalizedString
	/**
	 * An error occurred during external authentication.
	 */
	login_extError_default_message: () => LocalizedString
	/**
	 * Signing in to
	 */
	login_signingInTo: () => LocalizedString
	/**
	 * Contact Support
	 */
	common_contactSupport: () => LocalizedString
	/**
	 * Dismiss alert
	 */
	common_dismissAlert: () => LocalizedString
	/**
	 * Digit {position} of 6
	 */
	emailCode_digitLabel: (arg: { position: number }) => LocalizedString
}

export type Formatters = {}
