#!/usr/bin/env tsx
/**
 * Generate Tenant ID Migration Script
 *
 * Automatically generates migration SQL to add tenant_id column to all tables.
 * This enables future multi-tenant support while keeping single-tenant mode working.
 *
 * Usage: npx tsx scripts/generate-tenant-migration.ts
 * Output: Writes to stdout, redirect to file:
 *         npx tsx scripts/generate-tenant-migration.ts > migrations/008_add_tenant_id_to_all_tables.sql
 *
 * Features:
 * - Auto-detects all tables from existing migration files
 * - Excludes system tables (schema_migrations)
 * - Creates indexes for frequently queried tables
 * - Updates unique constraints to be tenant-scoped
 */

import { readFileSync, readdirSync } from 'fs';
import { join } from 'path';

// Tables to exclude from tenant_id addition (system tables)
const EXCLUDED_TABLES = ['schema_migrations'];

// Tables that need an index on tenant_id for query performance
const TABLES_NEEDING_INDEX = ['users', 'oauth_clients', 'sessions', 'audit_log', 'passkeys', 'roles'];

// Unique constraints that need to become tenant-scoped
// Format: { table: 'table_name', columns: ['col1', 'col2'], indexName: 'idx_name' }
const TENANT_SCOPED_UNIQUE_CONSTRAINTS = [
	{ table: 'users', columns: ['email'], oldIndex: 'idx_users_email', newIndex: 'idx_users_tenant_email' },
];

/**
 * Parse CREATE TABLE statements from migration files
 */
function extractTables(): string[] {
	const migrationsDir = join(process.cwd(), 'migrations');
	const tables = new Set<string>();

	const files = readdirSync(migrationsDir)
		.filter((f) => f.endsWith('.sql'))
		.sort();

	for (const file of files) {
		const content = readFileSync(join(migrationsDir, file), 'utf-8');
		// Match CREATE TABLE statements, handling IF NOT EXISTS
		const matches = content.matchAll(/CREATE TABLE (?:IF NOT EXISTS )?["']?(\w+)["']?/gi);
		for (const match of matches) {
			const tableName = match[1];
			if (!EXCLUDED_TABLES.includes(tableName)) {
				tables.add(tableName);
			}
		}
	}

	return Array.from(tables).sort();
}

/**
 * Generate the migration SQL
 */
function generateMigration(tables: string[]): string {
	const now = new Date();
	const dateStr = now.toISOString().split('T')[0];

	const lines: string[] = [
		'-- Migration: 008_add_tenant_id_to_all_tables.sql',
		'-- Description: Add tenant_id column to all tables for future multi-tenant support',
		'-- Author: @authrim',
		`-- Date: ${dateStr}`,
		'-- Issue: Multi-tenant readiness',
		'',
		'-- =============================================================================',
		'-- Auto-generated by: npx tsx scripts/generate-tenant-migration.ts',
		`-- Generated at: ${now.toISOString()}`,
		`-- Tables detected: ${tables.length}`,
		'-- =============================================================================',
		'',
		'-- This migration adds tenant_id to all tables with DEFAULT \'default\'.',
		'-- In single-tenant mode, all data uses the \'default\' tenant.',
		'-- For future multi-tenant mode, the tenant resolver will set appropriate values.',
		'',
		'-- =============================================================================',
		'-- Up Migration (Forward)',
		'-- =============================================================================',
		'',
		'-- Add tenant_id column to all tables',
	];

	for (const table of tables) {
		lines.push(`ALTER TABLE ${table} ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'default';`);
	}

	lines.push('');
	lines.push('-- Create indexes for frequently queried tables');
	for (const table of tables) {
		if (TABLES_NEEDING_INDEX.includes(table)) {
			lines.push(`CREATE INDEX IF NOT EXISTS idx_${table}_tenant_id ON ${table}(tenant_id);`);
		}
	}

	lines.push('');
	lines.push('-- Update unique constraints to be tenant-scoped');
	for (const constraint of TENANT_SCOPED_UNIQUE_CONSTRAINTS) {
		lines.push(`-- ${constraint.table}: Make ${constraint.columns.join(', ')} unique per tenant`);
		lines.push(`DROP INDEX IF EXISTS ${constraint.oldIndex};`);
		lines.push(
			`CREATE UNIQUE INDEX ${constraint.newIndex} ON ${constraint.table}(tenant_id, ${constraint.columns.join(', ')});`
		);
	}

	lines.push('');
	lines.push('-- =============================================================================');
	lines.push('-- Down Migration (Rollback) - COMMENTED OUT');
	lines.push('-- =============================================================================');
	lines.push('-- This section documents how to rollback this migration if needed.');
	lines.push('-- WARNING: This will fail if any tenant_id values other than \'default\' exist.');
	lines.push('--');
	lines.push('-- -- Restore original unique constraints');

	for (const constraint of TENANT_SCOPED_UNIQUE_CONSTRAINTS) {
		lines.push(`-- DROP INDEX IF EXISTS ${constraint.newIndex};`);
		lines.push(
			`-- CREATE UNIQUE INDEX ${constraint.oldIndex} ON ${constraint.table}(${constraint.columns.join(', ')});`
		);
	}

	lines.push('--');
	lines.push('-- -- Drop tenant_id indexes');
	for (const table of tables) {
		if (TABLES_NEEDING_INDEX.includes(table)) {
			lines.push(`-- DROP INDEX IF EXISTS idx_${table}_tenant_id;`);
		}
	}

	lines.push('--');
	lines.push('-- -- Drop tenant_id columns');
	for (const table of tables) {
		lines.push(`-- ALTER TABLE ${table} DROP COLUMN tenant_id;`);
	}

	lines.push('--');
	lines.push('-- -- Remove migration record');
	lines.push('-- DELETE FROM schema_migrations WHERE version = 8;');

	lines.push('');
	lines.push('-- =============================================================================');
	lines.push('-- Migration Complete');
	lines.push('-- =============================================================================');
	lines.push('-- Version: 008');
	lines.push('-- =============================================================================');

	return lines.join('\n');
}

/**
 * Main execution
 */
function main() {
	const tables = extractTables();

	if (tables.length === 0) {
		console.error('❌ No tables found in migrations directory');
		process.exit(1);
	}

	// Output migration SQL to stdout
	console.log(generateMigration(tables));

	// Log info to stderr (so it doesn't pollute the SQL output when redirected)
	console.error('');
	console.error(`✅ Generated migration for ${tables.length} tables:`);
	console.error(`   ${tables.join(', ')}`);
	console.error('');
	console.error('📝 To apply this migration:');
	console.error('   1. Review the generated SQL above');
	console.error(
		'   2. Save to file: npx tsx scripts/generate-tenant-migration.ts > migrations/008_add_tenant_id_to_all_tables.sql'
	);
	console.error('   3. Test: pnpm migrate:dry-run');
	console.error('   4. Apply: pnpm migrate:up');
}

main();
