#!/bin/bash
#
# Authrim Local Development Variables Setup Script
# Creates .dev.vars file for local development with Wrangler
#
# Usage:
#   ./setup-local-vars.sh [--env=ENV]
#
# Options:
#   --env=ENV   Environment name (default: "default")
#               Keys are searched in:
#                 1. .authrim-keys/{env}/ (external - recommended)
#                 2. .authrim/{env}/keys/ (internal)
#                 3. .keys/ (legacy)
#

set -e

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
ENV=""
for arg in "$@"; do
    if [[ $arg == --env=* ]]; then
        ENV="${arg#--env=}"
    fi
done

# Default environment name
if [ -z "$ENV" ]; then
    ENV="default"
fi

# Validate environment name (prevent path traversal)
if [[ "$ENV" =~ \.\. ]] || [[ "$ENV" =~ / ]] || [[ "$ENV" =~ \\ ]]; then
    echo -e "${RED}❌ Error: Invalid environment name '${ENV}': path traversal characters not allowed${NC}"
    exit 1
fi
if ! [[ "$ENV" =~ ^[a-z][a-z0-9-]*$ ]]; then
    echo -e "${RED}❌ Error: Invalid environment name '${ENV}': must be lowercase alphanumeric with hyphens, starting with a letter${NC}"
    exit 1
fi

echo -e "${BLUE}⚙️  Authrim Local Development Variables Setup${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Environment: $ENV"
echo ""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 3-tier Key Search
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

KEYS_DIR=""

# 1. External: .authrim-keys/{env}/
if [ -f ".authrim-keys/$ENV/private.pem" ]; then
    KEYS_DIR=".authrim-keys/$ENV"
    echo -e "${GREEN}✅ Keys found in .authrim-keys/$ENV/ (external)${NC}"
# 2. Internal: .authrim/{env}/keys/
elif [ -f ".authrim/$ENV/keys/private.pem" ]; then
    KEYS_DIR=".authrim/$ENV/keys"
    echo -e "${GREEN}✅ Keys found in .authrim/$ENV/keys/ (internal)${NC}"
# 3. Legacy: .keys/
elif [ -f ".keys/private.pem" ]; then
    KEYS_DIR=".keys"
    echo -e "${YELLOW}⚠️  Keys found in .keys/ (legacy)${NC}"
    echo "   Consider migrating to .authrim-keys/$ENV/ with:"
    echo "   ./scripts/setup-keys.sh --env=$ENV"
else
    echo -e "${RED}❌ Error: Keys not found${NC}"
    echo ""
    echo "Searched locations:"
    echo "  1. .authrim-keys/$ENV/private.pem (external)"
    echo "  2. .authrim/$ENV/keys/private.pem (internal)"
    echo "  3. .keys/private.pem (legacy)"
    echo ""
    echo "Please run setup-keys.sh first:"
    echo "  ./scripts/setup-keys.sh --env=$ENV"
    echo ""
    exit 1
fi

echo ""
echo "📦 Loading keys from $KEYS_DIR/..."
PRIVATE_KEY=$(cat "$KEYS_DIR/private.pem")
PUBLIC_JWK=$(cat "$KEYS_DIR/public.jwk.json" | jq -c .)
KEY_ID=$(cat "$KEYS_DIR/metadata.json" | jq -r '.kid')

if [ -z "$PRIVATE_KEY" ] || [ -z "$KEY_ID" ]; then
    echo -e "${RED}❌ Error: Failed to load keys${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Keys loaded successfully${NC}"
echo "   Key ID: $KEY_ID"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Creating .dev.vars file..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if .dev.vars already exists
if [ -f ".dev.vars" ]; then
    echo "⚠️  .dev.vars already exists"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}❌ Setup cancelled${NC}"
        exit 0
    fi
fi

# Load RP Token Encryption Key if available
RP_TOKEN_ENCRYPTION_KEY=""
if [ -f "$KEYS_DIR/rp_token_encryption_key.txt" ]; then
    RP_TOKEN_ENCRYPTION_KEY=$(cat "$KEYS_DIR/rp_token_encryption_key.txt")
fi

# Create base .dev.vars file
cat > .dev.vars << EOF
# Local development environment variables
# Generated by setup-local-vars.sh (env: $ENV)

# JWT Keys (required)
PRIVATE_KEY_PEM="$PRIVATE_KEY"
PUBLIC_JWK_JSON='$PUBLIC_JWK'
KEY_ID="$KEY_ID"

# RP Token Encryption Key
RP_TOKEN_ENCRYPTION_KEY="$RP_TOKEN_ENCRYPTION_KEY"

# Local development configuration
ALLOW_HTTP_REDIRECT="true"
UI_BASE_URL="http://localhost:5173"

# Optional: Email configuration
# Cloudflare Email Service: set EMAIL_FROM (and optionally EMAIL_FROM_NAME)
# Resend: set RESEND_API_KEY and EMAIL_FROM
# If not set, magic links will return URLs instead
# RESEND_API_KEY=""
# EMAIL_FROM="noreply@yourdomain.com"
# EMAIL_FROM_NAME="Authrim"
EOF

echo -e "${GREEN}✅ Base .dev.vars file created${NC}"
echo "   Location: .dev.vars"
echo ""

# Ask if user wants to add email configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📧 Email Configuration (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Authrim can send magic link emails via Cloudflare Email Service or Resend."
echo "  1) Cloudflare Email Service"
echo "  2) Resend"
echo "  3) Skip"
read -p "Select provider (1-3): " -r provider_choice
echo ""

if [[ "$provider_choice" == "1" ]]; then
    echo "Cloudflare prerequisites: Workers Paid Plan + Cloudflare DNS + dashboard onboarding"
    read -p "Email From address (default: noreply@yourdomain.com): " EMAIL_FROM_INPUT
    EMAIL_FROM=${EMAIL_FROM_INPUT:-"noreply@yourdomain.com"}
    read -p "Email From display name (optional): " EMAIL_FROM_NAME

    cat >> .dev.vars << EOF

# Email configuration
EMAIL_FROM="$EMAIL_FROM"
EOF

    if [ -n "$EMAIL_FROM_NAME" ]; then
        cat >> .dev.vars << EOF
EMAIL_FROM_NAME="$EMAIL_FROM_NAME"
EOF
    fi

    echo -e "${GREEN}✅ Email configuration added:${NC}"
    echo "   • Provider: Cloudflare Email Service"
    echo "   • Email From: $EMAIL_FROM"
elif [[ "$provider_choice" == "2" ]]; then
    read -p "Enter Resend API Key: " RESEND_API_KEY
    echo ""

    if [ -n "$RESEND_API_KEY" ]; then
        read -p "Email From address (default: noreply@yourdomain.com): " EMAIL_FROM_INPUT
        EMAIL_FROM=${EMAIL_FROM_INPUT:-"noreply@yourdomain.com"}

        # Append email configuration to .dev.vars
        cat >> .dev.vars << EOF

# Email configuration
RESEND_API_KEY="$RESEND_API_KEY"
EMAIL_FROM="$EMAIL_FROM"
EOF

        echo -e "${GREEN}✅ Email configuration added:${NC}"
        echo "   • Email From: $EMAIL_FROM"
        echo "   • Resend API Key: ${RESEND_API_KEY:0:10}..."
    else
        echo -e "${YELLOW}⊗ Email configuration skipped${NC}"
    fi
else
    echo -e "${YELLOW}⊗ Email configuration skipped${NC}"
    echo "   (Magic links will return URLs instead)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}🎉 Setup complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Next steps:"
echo ""
echo "1. Generate wrangler.toml files:"
echo "   ./scripts/setup-local-wrangler.sh"
echo ""
echo "2. Setup KV, D1, and Durable Objects:"
echo "   ./scripts/setup-kv.sh"
echo "   ./scripts/setup-d1.sh"
echo "   ./scripts/setup-durable-objects.sh"
echo ""
echo "3. Start local development:"
echo "   pnpm run dev"
echo ""
echo "📄 Files created/updated:"
echo "   • .dev.vars (loaded automatically by Wrangler)"
echo ""
echo -e "${YELLOW}⚠️  Security Note:${NC}"
echo "   • .dev.vars is gitignored - never commit it"
echo "   • Keep your Resend API key private"
echo ""
