#!/bin/bash
#
# Authrim Local Development Variables Setup Script
# Creates .dev.vars file for local development with Wrangler
#
# Usage:
#   ./setup-local-vars.sh
#

set -e

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}⚙️  Authrim Local Development Variables Setup${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if keys exist
if [ ! -f ".keys/private.pem" ]; then
    echo -e "${RED}❌ Error: Keys not found in .keys/ directory${NC}"
    echo ""
    echo "Please run setup-keys.sh first:"
    echo "  ./scripts/setup-keys.sh"
    echo ""
    exit 1
fi

echo "📦 Loading keys..."
PRIVATE_KEY=$(cat .keys/private.pem)
PUBLIC_JWK=$(cat .keys/public.jwk.json | jq -c .)
KEY_ID=$(cat .keys/metadata.json | jq -r '.kid')

if [ -z "$PRIVATE_KEY" ] || [ -z "$KEY_ID" ]; then
    echo -e "${RED}❌ Error: Failed to load keys${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Keys loaded successfully${NC}"
echo "   Key ID: $KEY_ID"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Creating .dev.vars file..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if .dev.vars already exists
if [ -f ".dev.vars" ]; then
    echo "⚠️  .dev.vars already exists"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}❌ Setup cancelled${NC}"
        exit 0
    fi
fi

# Create base .dev.vars file
cat > .dev.vars << EOF
# Local development environment variables
# Generated by setup-local-vars.sh

# JWT Keys (required)
PRIVATE_KEY_PEM="$PRIVATE_KEY"
PUBLIC_JWK_JSON='$PUBLIC_JWK'
KEY_ID="$KEY_ID"

# Local development configuration
ALLOW_HTTP_REDIRECT="true"
UI_BASE_URL="http://localhost:5173"

# Optional: Email configuration
# To enable email, set RESEND_API_KEY below and update EMAIL_FROM
# If not set, magic links will return URLs instead
# RESEND_API_KEY=""
# EMAIL_FROM="noreply@yourdomain.com"
EOF

echo -e "${GREEN}✅ Base .dev.vars file created${NC}"
echo "   Location: .dev.vars"
echo ""

# Ask if user wants to add Resend configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📧 Email Configuration (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Authrim can send magic link emails via Resend."
echo "Do you have a Resend API key? (y/N): " | tr -d '\n'
read -n 1 -r
echo
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    read -p "Enter Resend API Key: " RESEND_API_KEY
    echo ""

    if [ -n "$RESEND_API_KEY" ]; then
        read -p "Email From address (default: noreply@yourdomain.com): " EMAIL_FROM_INPUT
        EMAIL_FROM=${EMAIL_FROM_INPUT:-"noreply@yourdomain.com"}

        # Append email configuration to .dev.vars
        cat >> .dev.vars << EOF

# Email configuration
RESEND_API_KEY="$RESEND_API_KEY"
EMAIL_FROM="$EMAIL_FROM"
EOF

        echo -e "${GREEN}✅ Email configuration added:${NC}"
        echo "   • Email From: $EMAIL_FROM"
        echo "   • Resend API Key: ${RESEND_API_KEY:0:10}..."
    else
        echo -e "${YELLOW}⊗ Email configuration skipped${NC}"
    fi
else
    echo -e "${YELLOW}⊗ Email configuration skipped${NC}"
    echo "   (Magic links will return URLs instead)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}🎉 Setup complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Next steps:"
echo ""
echo "1. Generate wrangler.toml files:"
echo "   ./scripts/setup-local-wrangler.sh"
echo ""
echo "2. Setup KV, D1, and Durable Objects:"
echo "   ./scripts/setup-kv.sh"
echo "   ./scripts/setup-d1.sh"
echo "   ./scripts/setup-durable-objects.sh"
echo ""
echo "3. Start local development:"
echo "   pnpm run dev"
echo ""
echo "📄 Files created/updated:"
echo "   • .dev.vars (loaded automatically by Wrangler)"
echo ""
echo -e "${YELLOW}⚠️  Security Note:${NC}"
echo "   • .dev.vars is gitignored - never commit it"
echo "   • Keep your Resend API key private"
echo ""
