/**
 * Local development paths.
 *
 * Everything the local mode owns lives under `.authrim-local/<env>/` so it can never be mistaken
 * for (or overwrite) a Cloudflare environment kept under `.authrim/<env>/`. Generated Wrangler
 * files sit next to each package as `wrangler.local.toml` / `.dev.vars.<env>`; both are covered
 * by the repository .gitignore.
 */

import { join, resolve } from 'node:path';

export const LOCAL_STATE_DIRECTORY = '.authrim-local';
export const DEFAULT_LOCAL_ENVIRONMENT = 'local';

const LOCAL_ENVIRONMENT_PATTERN = /^[a-z][a-z0-9-]{0,23}$/u;

export interface LocalEnvironmentPaths {
  /** Repository root every local command runs from. */
  rootDir: string;
  /** `.authrim-local/<env>` */
  root: string;
  /** Key bundle generated by `generateAllSecrets`. */
  keys: string;
  /** Miniflare persistence shared by `wrangler dev --persist-to` and the seeding commands. */
  state: string;
  /** Wrangler config that only declares D1/KV bindings; used by the seeding commands. */
  seedConfig: string;
  /** Persisted AuthrimConfig used to regenerate every file. */
  config: string;
  /** Process logs written by `local up`. */
  logs: string;
  /** Lock directory for this environment (one entry file per holder); a sibling of `root` so `reset` can delete `root`. */
  lock: string;
}

export function assertValidLocalEnvironmentName(env: string): void {
  if (!LOCAL_ENVIRONMENT_PATTERN.test(env)) {
    throw new Error(
      `Invalid local environment name "${env}": use lowercase letters, digits and hyphens ` +
        '(start with a letter, at most 24 characters).'
    );
  }
}

export function getLocalEnvironmentPaths(rootDir: string, env: string): LocalEnvironmentPaths {
  assertValidLocalEnvironmentName(env);
  const absoluteRoot = resolve(rootDir);
  const root = join(absoluteRoot, LOCAL_STATE_DIRECTORY, env);
  return {
    rootDir: absoluteRoot,
    root,
    keys: join(root, 'keys'),
    state: join(root, 'state'),
    seedConfig: join(root, 'seed', 'wrangler.toml'),
    config: join(root, 'config.json'),
    logs: join(root, 'logs'),
    lock: join(absoluteRoot, LOCAL_STATE_DIRECTORY, `${env}.lock`),
  };
}

/**
 * Per-package Wrangler config produced for a local session. The file name carries the
 * environment so two environments never overwrite (or delete) each other's configs.
 */
export function getLocalWorkerConfigPath(rootDir: string, component: string, env: string): string {
  assertValidLocalEnvironmentName(env);
  return join(resolve(rootDir), 'packages', component, `wrangler.local.${env}.toml`);
}

/** Wrangler loads `.dev.vars.<env>` from the config directory when started with `--env <env>`. */
export function getLocalWorkerDevVarsPath(rootDir: string, component: string, env: string): string {
  return join(resolve(rootDir), 'packages', component, `.dev.vars.${env}`);
}
