/**
 * Generated Wrangler inputs for a local session.
 *
 * Worker configs come from the same `generateWranglerConfig` / `toToml` the Cloudflare flow uses,
 * fed with the synthetic lock from `environment.ts`. They are always regenerated, never edited.
 */

import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { AuthrimConfig } from '../config.js';
import type { AuthrimLock } from '../lock.js';
import type { WorkerComponent } from '../naming.js';
import { getSecretNamesForWorker, SECRET_KEY_FILES, type SecretName } from '../secrets.js';
import {
  buildResourceIdsFromLock,
  generateWranglerConfig,
  toToml,
  type ResourceIds,
} from '../wrangler.js';
import { listLocalD1Databases, listLocalKvNamespaces } from './environment.js';

export interface LocalWorkerFiles {
  component: WorkerComponent;
  /** Contents of `packages/<component>/wrangler.local.toml`. */
  toml: string;
  /** Contents of `packages/<component>/.dev.vars.<env>`. */
  devVars: string;
}

/**
 * Quote a value for a dotenv file as Wrangler parses it. dotenv only unescapes `\n` inside double
 * quotes, so single-line values (including JSON, which is compacted first) use single quotes and
 * only multi-line values such as PEM keys use double quotes with `\n` escapes.
 */
export function formatDevVarsValue(value: string): string {
  let normalized = value.replace(/\r\n/gu, '\n').replace(/\n+$/u, '');
  if (normalized.includes('\n')) {
    try {
      normalized = JSON.stringify(JSON.parse(normalized));
    } catch {
      // Not JSON: keep the multi-line text.
    }
  }
  if (normalized.includes('\n')) {
    if (/["\\]/u.test(normalized)) throw new Error('dev_vars_multiline_value_unsupported');
    return `"${normalized.replace(/\n/gu, '\\n')}"`;
  }
  if (!normalized.includes("'")) return `'${normalized}'`;
  if (!normalized.includes('`')) return `\`${normalized}\``;
  throw new Error('dev_vars_value_unsupported');
}

export function formatDevVars(secrets: Readonly<Record<string, string>>): string {
  const lines = [
    '# Generated by `authrim-setup local init`. Local development secrets only; never commit.',
    ...Object.entries(secrets)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([name, value]) => `${name}=${formatDevVarsValue(value)}`),
  ];
  return `${lines.join('\n')}\n`;
}

/**
 * Secrets that stay unset locally on purpose. With a tenant backup wrapping key configured,
 * every covered settings mutation must acquire a permit from the Control Worker, which local
 * mode does not run; without it the mutation proceeds directly and backups are unavailable.
 */
const LOCAL_UNSUPPORTED_SECRETS: ReadonlySet<string> = new Set(['TENANT_BACKUP_WRAPPING_KEY']);

/** Read every secret the component needs from the local key bundle. */
export async function loadLocalSecretsForComponent(
  keysDir: string,
  component: WorkerComponent
): Promise<Record<string, string>> {
  const secrets: Record<string, string> = {};
  for (const name of getSecretNamesForWorker(component) as readonly SecretName[]) {
    const fileName = SECRET_KEY_FILES[name];
    // Cloudflare API tokens and Resend credentials have no local equivalent.
    if (!fileName || name.startsWith('CLOUDFLARE_') || name === 'RESEND_API_KEY') continue;
    if (LOCAL_UNSUPPORTED_SECRETS.has(name)) continue;
    const path = join(keysDir, fileName);
    if (!existsSync(path)) continue;
    secrets[name] = await readFile(path, 'utf-8');
  }
  return secrets;
}

export function buildLocalResourceIds(lock: AuthrimLock, config: AuthrimConfig): ResourceIds {
  // Queues and R2 buckets do not exist locally: bindings that depend on them are omitted.
  return { ...buildResourceIdsFromLock({ ...lock, queues: undefined, r2: undefined }, config) };
}

export async function buildLocalWorkerFiles(input: {
  config: AuthrimConfig;
  lock: AuthrimLock;
  keysDir: string;
  running: readonly WorkerComponent[];
  excluded: readonly WorkerComponent[];
}): Promise<LocalWorkerFiles[]> {
  const env = input.config.environment.prefix;
  const resourceIds = buildLocalResourceIds(input.lock, input.config);
  const files: LocalWorkerFiles[] = [];
  for (const component of input.running) {
    const wranglerConfig = generateWranglerConfig(component, input.config, resourceIds, undefined, {
      local: { excludedComponents: input.excluded },
    });
    files.push({
      component,
      toml: toToml(wranglerConfig, env),
      devVars: formatDevVars(await loadLocalSecretsForComponent(input.keysDir, component)),
    });
  }
  return files;
}

/**
 * Wrangler config that only declares bindings. `wrangler d1 execute --local` and
 * `wrangler kv key put --local` resolve databases by name from it, using the same identifiers as
 * the Worker configs so every command touches the state `wrangler dev` reads.
 */
export function buildLocalSeedConfigToml(env: string): string {
  const lines = [
    `name = "${env}-authrim-local-seed"`,
    'compatibility_date = "2024-09-23"',
    '',
    '# Generated by `authrim-setup local init`. Declares bindings for seeding commands only.',
    '',
  ];
  for (const { binding, name } of listLocalD1Databases(env)) {
    lines.push('[[d1_databases]]', `binding = "${binding}"`);
    lines.push(`database_name = "${name}"`, `database_id = "${name}"`, '');
  }
  for (const { binding, title } of listLocalKvNamespaces(env)) {
    lines.push('[[kv_namespaces]]', `binding = "${binding}"`, `id = "${title}"`, '');
  }
  return `${lines.join('\n')}`;
}
